// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	pbkdf2 "crypto/pbkdf2"
	"hash"
	"reflect"
)

func init() {
	Symbols["crypto/pbkdf2"] = map[string]reflect.Value{"Key": reflect.ValueOf(pbkdf2.Key[hash.Hash])}
}
