// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	rc4 "crypto/rc4"
	"reflect"
)

func init() {
	Symbols["crypto/rc4"] = map[string]reflect.Value{"Cipher": reflect.ValueOf((*rc4.Cipher)(nil)), "KeySizeError": reflect.ValueOf((*rc4.KeySizeError)(nil)), "NewCipher": reflect.ValueOf(rc4.NewCipher)}
}
