// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	des "crypto/des"
	"reflect"
)

func init() {
	Symbols["crypto/des"] = map[string]reflect.Value{"BlockSize": reflect.ValueOf(des.BlockSize), "KeySizeError": reflect.ValueOf((*des.KeySizeError)(nil)), "NewCipher": reflect.ValueOf(des.NewCipher), "NewTripleDESCipher": reflect.ValueOf(des.NewTripleDESCipher)}
}
