// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	subtle "crypto/subtle"
	"reflect"
)

func init() {
	Symbols["crypto/subtle"] = map[string]reflect.Value{"ConstantTimeByteEq": reflect.ValueOf(subtle.ConstantTimeByteEq), "ConstantTimeCompare": reflect.ValueOf(subtle.ConstantTimeCompare), "ConstantTimeCopy": reflect.ValueOf(subtle.ConstantTimeCopy), "ConstantTimeEq": reflect.ValueOf(subtle.ConstantTimeEq), "ConstantTimeLessOrEq": reflect.ValueOf(subtle.ConstantTimeLessOrEq), "ConstantTimeSelect": reflect.ValueOf(subtle.ConstantTimeSelect), "WithDataIndependentTiming": reflect.ValueOf(subtle.WithDataIndependentTiming), "XORBytes": reflect.ValueOf(subtle.XORBytes)}
}
