// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	hpke "crypto/hpke"
	"reflect"
)

func init() {
	Symbols["crypto/hpke"] = map[string]reflect.Value{"AEAD": reflect.ValueOf((*hpke.AEAD)(nil)), "AES128GCM": reflect.ValueOf(hpke.AES128GCM), "AES256GCM": reflect.ValueOf(hpke.AES256GCM), "ChaCha20Poly1305": reflect.ValueOf(hpke.ChaCha20Poly1305), "DHKEM": reflect.ValueOf(hpke.DHKEM), "ExportOnly": reflect.ValueOf(hpke.ExportOnly), "HKDFSHA256": reflect.ValueOf(hpke.HKDFSHA256), "HKDFSHA384": reflect.ValueOf(hpke.HKDFSHA384), "HKDFSHA512": reflect.ValueOf(hpke.HKDFSHA512), "KDF": reflect.ValueOf((*hpke.KDF)(nil)), "KEM": reflect.ValueOf((*hpke.KEM)(nil)), "MLKEM1024": reflect.ValueOf(hpke.MLKEM1024), "MLKEM1024P384": reflect.ValueOf(hpke.MLKEM1024P384), "MLKEM768": reflect.ValueOf(hpke.MLKEM768), "MLKEM768P256": reflect.ValueOf(hpke.MLKEM768P256), "MLKEM768X25519": reflect.ValueOf(hpke.MLKEM768X25519), "NewAEAD": reflect.ValueOf(hpke.NewAEAD), "NewDHKEMPrivateKey": reflect.ValueOf(hpke.NewDHKEMPrivateKey), "NewDHKEMPublicKey": reflect.ValueOf(hpke.NewDHKEMPublicKey), "NewHybridPrivateKey": reflect.ValueOf(hpke.NewHybridPrivateKey), "NewHybridPublicKey": reflect.ValueOf(hpke.NewHybridPublicKey), "NewKDF": reflect.ValueOf(hpke.NewKDF), "NewKEM": reflect.ValueOf(hpke.NewKEM), "NewMLKEMPrivateKey": reflect.ValueOf(hpke.NewMLKEMPrivateKey), "NewMLKEMPublicKey": reflect.ValueOf(hpke.NewMLKEMPublicKey), "NewRecipient": reflect.ValueOf(hpke.NewRecipient), "NewSender": reflect.ValueOf(hpke.NewSender), "Open": reflect.ValueOf(hpke.Open), "PrivateKey": reflect.ValueOf((*hpke.PrivateKey)(nil)), "PublicKey": reflect.ValueOf((*hpke.PublicKey)(nil)), "Recipient": reflect.ValueOf((*hpke.Recipient)(nil)), "SHAKE128": reflect.ValueOf(hpke.SHAKE128), "SHAKE256": reflect.ValueOf(hpke.SHAKE256), "Seal": reflect.ValueOf(hpke.Seal), "Sender": reflect.ValueOf((*hpke.Sender)(nil))}
}
