// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	mlkemtest "crypto/mlkem/mlkemtest"
	"reflect"
)

func init() {
	Symbols["crypto/mlkem/mlkemtest"] = map[string]reflect.Value{"Encapsulate1024": reflect.ValueOf(mlkemtest.Encapsulate1024), "Encapsulate768": reflect.ValueOf(mlkemtest.Encapsulate768)}
}
