// Code generated by 'pipit extract'. DO NOT EDIT.

package crypto

import (
	aes "crypto/aes"
	"reflect"
)

func init() {
	Symbols["crypto/aes"] = map[string]reflect.Value{"BlockSize": reflect.ValueOf(aes.BlockSize), "KeySizeError": reflect.ValueOf((*aes.KeySizeError)(nil)), "NewCipher": reflect.ValueOf(aes.NewCipher)}
}
