// Code generated by 'pipit extract'. DO NOT EDIT.

package system

import (
	ioutil "io/ioutil"
	"reflect"
)

func init() {
	Symbols["io/ioutil"] = map[string]reflect.Value{"Discard": reflect.ValueOf(&ioutil.Discard).Elem(), "NopCloser": reflect.ValueOf(ioutil.NopCloser), "ReadAll": reflect.ValueOf(ioutil.ReadAll), "ReadDir": reflect.ValueOf(ioutil.ReadDir), "ReadFile": reflect.ValueOf(ioutil.ReadFile), "TempDir": reflect.ValueOf(ioutil.TempDir), "TempFile": reflect.ValueOf(ioutil.TempFile), "WriteFile": reflect.ValueOf(ioutil.WriteFile)}
}
