// Code generated by 'pipit extract'. DO NOT EDIT.

package system

import (
	user "os/user"
	"reflect"
)

func init() {
	Symbols["os/user"] = map[string]reflect.Value{"Current": reflect.ValueOf(user.Current), "Group": reflect.ValueOf((*user.Group)(nil)), "Lookup": reflect.ValueOf(user.Lookup), "LookupGroup": reflect.ValueOf(user.LookupGroup), "LookupGroupId": reflect.ValueOf(user.LookupGroupId), "LookupId": reflect.ValueOf(user.LookupId), "UnknownGroupError": reflect.ValueOf((*user.UnknownGroupError)(nil)), "UnknownGroupIdError": reflect.ValueOf((*user.UnknownGroupIdError)(nil)), "UnknownUserError": reflect.ValueOf((*user.UnknownUserError)(nil)), "UnknownUserIdError": reflect.ValueOf((*user.UnknownUserIdError)(nil)), "User": reflect.ValueOf((*user.User)(nil))}
}
