// Code generated by 'pipit extract'. DO NOT EDIT.

package image

import (
	draw "image/draw"
	"reflect"
)

func init() {
	Symbols["image/draw"] = map[string]reflect.Value{"Draw": reflect.ValueOf(draw.Draw), "DrawMask": reflect.ValueOf(draw.DrawMask), "Drawer": reflect.ValueOf((*draw.Drawer)(nil)), "FloydSteinberg": reflect.ValueOf(&draw.FloydSteinberg).Elem(), "Image": reflect.ValueOf((*draw.Image)(nil)), "Op": reflect.ValueOf((*draw.Op)(nil)), "Over": reflect.ValueOf(draw.Over), "Quantizer": reflect.ValueOf((*draw.Quantizer)(nil)), "RGBA64Image": reflect.ValueOf((*draw.RGBA64Image)(nil)), "Src": reflect.ValueOf(draw.Src)}
}
