// Code generated by 'pipit extract'. DO NOT EDIT.

package image

import (
	color "image/color"
	"reflect"
)

func init() {
	Symbols["image/color"] = map[string]reflect.Value{"Alpha": reflect.ValueOf((*color.Alpha)(nil)), "Alpha16": reflect.ValueOf((*color.Alpha16)(nil)), "Alpha16Model": reflect.ValueOf(&color.Alpha16Model).Elem(), "AlphaModel": reflect.ValueOf(&color.AlphaModel).Elem(), "Black": reflect.ValueOf(&color.Black).Elem(), "CMYK": reflect.ValueOf((*color.CMYK)(nil)), "CMYKModel": reflect.ValueOf(&color.CMYKModel).Elem(), "CMYKToRGB": reflect.ValueOf(color.CMYKToRGB), "Color": reflect.ValueOf((*color.Color)(nil)), "Gray": reflect.ValueOf((*color.Gray)(nil)), "Gray16": reflect.ValueOf((*color.Gray16)(nil)), "Gray16Model": reflect.ValueOf(&color.Gray16Model).Elem(), "GrayModel": reflect.ValueOf(&color.GrayModel).Elem(), "Model": reflect.ValueOf((*color.Model)(nil)), "ModelFunc": reflect.ValueOf(color.ModelFunc), "NRGBA": reflect.ValueOf((*color.NRGBA)(nil)), "NRGBA64": reflect.ValueOf((*color.NRGBA64)(nil)), "NRGBA64Model": reflect.ValueOf(&color.NRGBA64Model).Elem(), "NRGBAModel": reflect.ValueOf(&color.NRGBAModel).Elem(), "NYCbCrA": reflect.ValueOf((*color.NYCbCrA)(nil)), "NYCbCrAModel": reflect.ValueOf(&color.NYCbCrAModel).Elem(), "Opaque": reflect.ValueOf(&color.Opaque).Elem(), "Palette": reflect.ValueOf((*color.Palette)(nil)), "RGBA": reflect.ValueOf((*color.RGBA)(nil)), "RGBA64": reflect.ValueOf((*color.RGBA64)(nil)), "RGBA64Model": reflect.ValueOf(&color.RGBA64Model).Elem(), "RGBAModel": reflect.ValueOf(&color.RGBAModel).Elem(), "RGBToCMYK": reflect.ValueOf(color.RGBToCMYK), "RGBToYCbCr": reflect.ValueOf(color.RGBToYCbCr), "Transparent": reflect.ValueOf(&color.Transparent).Elem(), "White": reflect.ValueOf(&color.White).Elem(), "YCbCr": reflect.ValueOf((*color.YCbCr)(nil)), "YCbCrModel": reflect.ValueOf(&color.YCbCrModel).Elem(), "YCbCrToRGB": reflect.ValueOf(color.YCbCrToRGB)}
}
