// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	appendlower "pipit.sh/pipit/internal/compile/appendlower"
)

func init() {
	Symbols["pipit.sh/pipit/internal/compile/appendlower"] = map[string]reflect.Value{"CollectAliases": reflect.ValueOf(appendlower.CollectAliases), "ElementKind": reflect.ValueOf(appendlower.ElementKind), "MatchShape": reflect.ValueOf(appendlower.MatchShape), "SameSlice": reflect.ValueOf(appendlower.SameSlice)}
}
