// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	asmgen_arch_amd64 "pipit.sh/pipit/internal/engine/asm/asmgen_arch_amd64"
)

func init() {
	Symbols["pipit.sh/pipit/internal/engine/asm/asmgen_arch_amd64"] = map[string]reflect.Value{"BytecodeAMD64Arch": reflect.ValueOf((*asmgen_arch_amd64.BytecodeAMD64Arch)(nil)), "JumpTableEntry": reflect.ValueOf((*asmgen_arch_amd64.JumpTableEntry)(nil)), "New": reflect.ValueOf(asmgen_arch_amd64.New)}
}
