// Code generated by 'pipit extract'. DO NOT EDIT.

//go:build !js || !wasm

package selfhost

// typesExportGoVersion is the toolchain that produced the embedded export data.
const typesExportGoVersion = "go1.27.0"

// typesExportEntry describes one embedded gcexportdata blob.
type typesExportEntry struct {
	// Path is the Go import path the blob describes.
	Path string

	// File is the blob's path within the embedded file system.
	File string

	// Dependencies lists the import paths in this set that must be decoded first.
	Dependencies []string
}

// typesExportManifest lists every embedded blob sorted by import path.
var typesExportManifest = []typesExportEntry{
	{Path: "pipit.sh/pipit/internal/compile/appendlower", File: "gen_types_export/pipit.sh_pipit_internal_compile_appendlower.bin.gz"},
	{Path: "pipit.sh/pipit/internal/compile/astpattern", File: "gen_types_export/pipit.sh_pipit_internal_compile_astpattern.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/compile/patterns", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/safeconv"}},
	{Path: "pipit.sh/pipit/internal/compile/escape", File: "gen_types_export/pipit.sh_pipit_internal_compile_escape.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/compile/inline", "pipit.sh/pipit/internal/compile/passes", "pipit.sh/pipit/internal/compile/typemap", "pipit.sh/pipit/internal/engine", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/isa"}},
	{Path: "pipit.sh/pipit/internal/compile/fieldlayout", File: "gen_types_export/pipit.sh_pipit_internal_compile_fieldlayout.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/safeconv"}},
	{Path: "pipit.sh/pipit/internal/compile/inline", File: "gen_types_export/pipit.sh_pipit_internal_compile_inline.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/compile/passes", "pipit.sh/pipit/internal/engine", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/safeconv", "pipit.sh/pipit/internal/symtab/descriptor"}},
	{Path: "pipit.sh/pipit/internal/compile/isaselect", File: "gen_types_export/pipit.sh_pipit_internal_compile_isaselect.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/isa"}},
	{Path: "pipit.sh/pipit/internal/compile/liveness", File: "gen_types_export/pipit.sh_pipit_internal_compile_liveness.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/compile/typemap"}},
	{Path: "pipit.sh/pipit/internal/compile/passes", File: "gen_types_export/pipit.sh_pipit_internal_compile_passes.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/engine", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/safeconv"}},
	{Path: "pipit.sh/pipit/internal/compile/patterns", File: "gen_types_export/pipit.sh_pipit_internal_compile_patterns.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/compile/passes", "pipit.sh/pipit/internal/compile/scope", "pipit.sh/pipit/internal/engine/program"}},
	{Path: "pipit.sh/pipit/internal/compile/scope", File: "gen_types_export/pipit.sh_pipit_internal_compile_scope.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/isa"}},
	{Path: "pipit.sh/pipit/internal/compile/typemap", File: "gen_types_export/pipit.sh_pipit_internal_compile_typemap.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/engine", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/logging", "pipit.sh/pipit/internal/symtab", "pipit.sh/pipit/internal/symtab/typemodel"}},
	{Path: "pipit.sh/pipit/internal/engine", File: "gen_types_export/pipit.sh_pipit_internal_engine.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/engine/asm", "pipit.sh/pipit/internal/engine/goversion", "pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/hostmem", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/link", "pipit.sh/pipit/internal/logging", "pipit.sh/pipit/internal/mem", "pipit.sh/pipit/internal/policy", "pipit.sh/pipit/internal/safeconv", "pipit.sh/pipit/internal/stablepool", "pipit.sh/pipit/internal/symtab", "pipit.sh/pipit/internal/symtab/typemodel"}},
	{Path: "pipit.sh/pipit/internal/engine/asm", File: "gen_types_export/pipit.sh_pipit_internal_engine_asm.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/engine/asm/asmgen_arch_amd64", "pipit.sh/pipit/internal/engine/asm/asmgen_arch_arm64"}},
	{Path: "pipit.sh/pipit/internal/engine/asm/asmgen_arch_amd64", File: "gen_types_export/pipit.sh_pipit_internal_engine_asm_asmgen_arch_amd64.bin.gz"},
	{Path: "pipit.sh/pipit/internal/engine/asm/asmgen_arch_arm64", File: "gen_types_export/pipit.sh_pipit_internal_engine_asm_asmgen_arch_arm64.bin.gz"},
	{Path: "pipit.sh/pipit/internal/engine/goversion", File: "gen_types_export/pipit.sh_pipit_internal_engine_goversion.bin.gz"},
	{Path: "pipit.sh/pipit/internal/engine/program", File: "gen_types_export/pipit.sh_pipit_internal_engine_program.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/policy", "pipit.sh/pipit/internal/safeconv", "pipit.sh/pipit/internal/symtab", "pipit.sh/pipit/internal/symtab/descriptor"}},
	{Path: "pipit.sh/pipit/internal/fault", File: "gen_types_export/pipit.sh_pipit_internal_fault.bin.gz"},
	{Path: "pipit.sh/pipit/internal/hostmem", File: "gen_types_export/pipit.sh_pipit_internal_hostmem.bin.gz"},
	{Path: "pipit.sh/pipit/internal/isa", File: "gen_types_export/pipit.sh_pipit_internal_isa.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/safeconv"}},
	{Path: "pipit.sh/pipit/internal/link", File: "gen_types_export/pipit.sh_pipit_internal_link.bin.gz"},
	{Path: "pipit.sh/pipit/internal/logging", File: "gen_types_export/pipit.sh_pipit_internal_logging.bin.gz"},
	{Path: "pipit.sh/pipit/internal/mem", File: "gen_types_export/pipit.sh_pipit_internal_mem.bin.gz"},
	{Path: "pipit.sh/pipit/internal/policy", File: "gen_types_export/pipit.sh_pipit_internal_policy.bin.gz"},
	{Path: "pipit.sh/pipit/internal/safeconv", File: "gen_types_export/pipit.sh_pipit_internal_safeconv.bin.gz"},
	{Path: "pipit.sh/pipit/internal/stablepool", File: "gen_types_export/pipit.sh_pipit_internal_stablepool.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/safeconv"}},
	{Path: "pipit.sh/pipit/internal/symtab", File: "gen_types_export/pipit.sh_pipit_internal_symtab.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/link", "pipit.sh/pipit/internal/policy", "pipit.sh/pipit/internal/symtab/descriptor", "pipit.sh/pipit/internal/symtab/typemodel"}},
	{Path: "pipit.sh/pipit/internal/symtab/descriptor", File: "gen_types_export/pipit.sh_pipit_internal_symtab_descriptor.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/safeconv", "pipit.sh/pipit/internal/symtab/typemodel"}},
	{Path: "pipit.sh/pipit/internal/symtab/typemodel", File: "gen_types_export/pipit.sh_pipit_internal_symtab_typemodel.bin.gz", Dependencies: []string{"pipit.sh/pipit/internal/link"}},
}
