// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	liveness "pipit.sh/pipit/internal/compile/liveness"
)

func init() {
	Symbols["pipit.sh/pipit/internal/compile/liveness"] = map[string]reflect.Value{"ComputeLastUseIndices": reflect.ValueOf(liveness.ComputeLastUseIndices), "ExtractDeclaredNames": reflect.ValueOf(liveness.ExtractDeclaredNames)}
}
