// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	scope "pipit.sh/pipit/internal/compile/scope"
)

func init() {
	Symbols["pipit.sh/pipit/internal/compile/scope"] = map[string]reflect.Value{"NewScopeStack": reflect.ValueOf(scope.NewScopeStack), "RegisterAllocator": reflect.ValueOf((*scope.RegisterAllocator)(nil)), "ScopeStack": reflect.ValueOf((*scope.ScopeStack)(nil)), "SyntheticNamePrefix": reflect.ValueOf(scope.SyntheticNamePrefix)}
}
