// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	descriptor "pipit.sh/pipit/internal/symtab/descriptor"
)

func init() {
	Symbols["pipit.sh/pipit/internal/symtab/descriptor"] = map[string]reflect.Value{"BasicKindToReflect": reflect.ValueOf(descriptor.BasicKindToReflect), "GeneralConstantCompositeZero": reflect.ValueOf(descriptor.GeneralConstantCompositeZero), "GeneralConstantDescriptor": reflect.ValueOf((*descriptor.GeneralConstantDescriptor)(nil)), "GeneralConstantKind": reflect.ValueOf((*descriptor.GeneralConstantKind)(nil)), "GeneralConstantNamedTypeZero": reflect.ValueOf(descriptor.GeneralConstantNamedTypeZero), "GeneralConstantPackageSymbol": reflect.ValueOf(descriptor.GeneralConstantPackageSymbol), "GeneralConstantPackageSymbolAddress": reflect.ValueOf(descriptor.GeneralConstantPackageSymbolAddress), "KindArray": reflect.ValueOf(descriptor.KindArray), "KindBasic": reflect.ValueOf(descriptor.KindBasic), "KindChan": reflect.ValueOf(descriptor.KindChan), "KindFunc": reflect.ValueOf(descriptor.KindFunc), "KindInterface": reflect.ValueOf(descriptor.KindInterface), "KindMap": reflect.ValueOf(descriptor.KindMap), "KindNamed": reflect.ValueOf(descriptor.KindNamed), "KindNil": reflect.ValueOf(descriptor.KindNil), "KindPtr": reflect.ValueOf(descriptor.KindPtr), "KindSlice": reflect.ValueOf(descriptor.KindSlice), "KindStruct": reflect.ValueOf(descriptor.KindStruct), "MaxTypeDescriptorDepth": reflect.ValueOf(descriptor.MaxTypeDescriptorDepth), "ReflectTypeToDescriptor": reflect.ValueOf(descriptor.ReflectTypeToDescriptor), "TypeDescriptor": reflect.ValueOf((*descriptor.TypeDescriptor)(nil)), "TypeDescriptorData": reflect.ValueOf((*descriptor.TypeDescriptorData)(nil)), "TypeDescriptorField": reflect.ValueOf((*descriptor.TypeDescriptorField)(nil)), "TypeDescriptorFieldData": reflect.ValueOf((*descriptor.TypeDescriptorFieldData)(nil)), "TypeDescriptorKind": reflect.ValueOf((*descriptor.TypeDescriptorKind)(nil))}
}
