// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	astpattern "pipit.sh/pipit/internal/compile/astpattern"
)

func init() {
	Symbols["pipit.sh/pipit/internal/compile/astpattern"] = map[string]reflect.Value{"DefaultRegistry": reflect.ValueOf(astpattern.DefaultRegistry)}
}
