// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	hostmem "pipit.sh/pipit/internal/hostmem"
)

func init() {
	Symbols["pipit.sh/pipit/internal/hostmem"] = map[string]reflect.Value{"DetectCgroupMemoryLimitBytes": reflect.ValueOf(hostmem.DetectCgroupMemoryLimitBytes), "DetectHostMemoryBytes": reflect.ValueOf(hostmem.DetectHostMemoryBytes)}
}
