// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	asm "pipit.sh/pipit/internal/engine/asm"
)

func init() {
	Symbols["pipit.sh/pipit/internal/engine/asm"] = map[string]reflect.Value{"ABITypeKindByteOffset": reflect.ValueOf(asm.ABITypeKindByteOffset), "ABITypePointerElemOffset": reflect.ValueOf(asm.ABITypePointerElemOffset), "ASMCallInfoOffsets": reflect.ValueOf((*asm.ASMCallInfoOffsets)(nil)), "AsmHandlerJumpTableEntry": reflect.ValueOf((*asm.AsmHandlerJumpTableEntry)(nil)), "BytecodeArchitecturePort": reflect.ValueOf((*asm.BytecodeArchitecturePort)(nil)), "CallFrameOffsets": reflect.ValueOf((*asm.CallFrameOffsets)(nil)), "DirectExitHandlerSpec": reflect.ValueOf((*asm.DirectExitHandlerSpec)(nil)), "DirectExitHandlers": reflect.ValueOf(asm.DirectExitHandlers), "DispatchContextOffsets": reflect.ValueOf((*asm.DispatchContextOffsets)(nil)), "FileGroups": reflect.ValueOf(asm.FileGroups), "GoFiles": reflect.ValueOf(asm.GoFiles), "HeaderFiles": reflect.ValueOf(asm.HeaderFiles), "PathBShimSpec": reflect.ValueOf((*asm.PathBShimSpec)(nil)), "PathBShims": reflect.ValueOf(asm.PathBShims), "RegisterDirectExit": reflect.ValueOf(asm.RegisterDirectExit), "RegisterPathBShim": reflect.ValueOf(asm.RegisterPathBShim), "VarLocationOffsets": reflect.ValueOf((*asm.VarLocationOffsets)(nil))}
}
