// Code generated by 'pipit extract'. DO NOT EDIT.

package selfhost

import (
	"reflect"

	mem "pipit.sh/pipit/internal/mem"
)

func init() {
	Symbols["pipit.sh/pipit/internal/mem"] = map[string]reflect.Value{"Bytes": reflect.ValueOf(mem.Bytes), "String": reflect.ValueOf(mem.String)}
}
