//go:build linux && (amd64 || arm64)

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package sandboxlinux

import (
	"fmt"
	"runtime"
	"unsafe"

	"golang.org/x/sys/unix"

	"pipit.sh/pipit/internal/safeconv"
)

const (
	// workerIPCFD is the fixed descriptor number for the worker IPC socket.
	workerIPCFD = 3

	// seccompArchitectureOffset is the BPF data offset for the audit architecture.
	seccompArchitectureOffset = 4

	// seccompArgumentsOffset is the BPF data offset for syscall arguments.
	seccompArgumentsOffset = 16

	// seccompArgumentBytes is the byte width of one syscall argument.
	seccompArgumentBytes = 8

	// seccompHighWordOffset is the byte offset of the upper 32 bits within an argument.
	seccompHighWordOffset = 4

	// maximumFilterInstructions is the upper bound on BPF filter length.
	maximumFilterInstructions = 4096

	// maximumRuleInstructions is the upper bound on instructions per syscall rule.
	maximumRuleInstructions = 255

	// seccompArgumentCount is the number of syscall arguments available.
	seccompArgumentCount = 6

	// goThreadCloneFlags is the common clone flag set for Go runtime threads.
	goThreadCloneFlags = unix.CLONE_VM | unix.CLONE_FS | unix.CLONE_FILES |
		unix.CLONE_SIGHAND | unix.CLONE_SYSVSEM | unix.CLONE_THREAD

	// denySyscall is the seccomp return value that denies with EPERM.
	denySyscall = unix.SECCOMP_RET_ERRNO | uint32(unix.EPERM)
)

// argumentRule restricts both the upper word and selected lower-word argument bits.
type argumentRule struct {
	// allowed holds the permitted masked argument values.
	allowed []uint32

	// index holds the zero-based syscall argument position.
	index uint32

	// mask holds the bitmask applied before comparison.
	mask uint32
}

// syscallRule permits one syscall only when every argument predicate matches.
type syscallRule struct {
	// arguments holds the argument predicates for this syscall.
	arguments []argumentRule

	// number holds the Linux syscall number.
	number uint32
}

// installSyscallFilter irreversibly restricts the entire current worker process. Call
// only after namespace and descriptor setup, before receiving untrusted input.
//
// Returns error unless no_new_privs and thread-synchronised filtering succeed. The worker
// must exit on any error, never continue with weaker restrictions.
func installSyscallFilter() error {
	filter, err := workerFilter(unix.Getpid())
	if err != nil {
		return err
	}
	return installWorkerFilter(filter)
}

// installWorkerFilter installs a validated profile on every worker thread.
//
// Takes filter ([]unix.SockFilter) which was generated by the private compiler.
//
// Returns error unless privilege reduction and thread synchronisation succeed.
func installWorkerFilter(filter []unix.SockFilter) error {
	if err := unix.Setrlimit(unix.RLIMIT_CORE, &unix.Rlimit{Cur: 0, Max: 0}); err != nil {
		return fmt.Errorf("%w: disabling worker core dumps: %w", ErrUnavailable, err)
	}
	runtime.LockOSThread()
	defer runtime.UnlockOSThread()
	if err := restrictWorkerPrivileges(); err != nil {
		return err
	}
	program := unix.SockFprog{Len: safeconv.IntToUint16(len(filter)), Filter: &filter[0]}
	result, _, errno := unix.RawSyscall(unix.SYS_SECCOMP, unix.SECCOMP_SET_MODE_FILTER,
		unix.SECCOMP_FILTER_FLAG_TSYNC, uintptr(unsafe.Pointer(&program)))
	runtime.KeepAlive(filter)
	if errno != 0 {
		return fmt.Errorf("%w: seccomp thread synchronisation: %w", ErrUnavailable, errno)
	}
	if result != 0 {
		return fmt.Errorf("%w: seccomp could not synchronise thread %d", ErrUnavailable, result)
	}
	return nil
}

// workerFilter constructs the fixed, architecture-checked pure-Go syscall profile.
//
// Takes processID (int) which is the worker's own PID in its current PID namespace.
//
// Returns []unix.SockFilter which defaults to EPERM and kills foreign ABIs.
// Returns error when the identity or generated program is invalid.
func workerFilter(processID int) ([]unix.SockFilter, error) {
	return workerFilterWithWakeDescriptors(processID, nil)
}

// workerFilterWithWakeDescriptors includes verified runtime eventfd handles.
//
// Takes processID (int) which is the current worker identity.
// Takes wakeDescriptors ([]uint32) which were privately verified during bootstrap.
//
// Returns []unix.SockFilter which permits only explicit I/O descriptor roles.
// Returns error when the identity or descriptor list is invalid.
func workerFilterWithWakeDescriptors(processID int, wakeDescriptors []uint32) ([]unix.SockFilter, error) {
	if processID <= 0 {
		return nil, ErrUnavailable
	}
	if err := validateWakeDescriptors(wakeDescriptors); err != nil {
		return nil, err
	}
	rules := runtimeRules(safeconv.IntToUint32(processID), wakeDescriptors)
	return compileSyscallRules(rules, killRules())
}

// compileSyscallRules compiles one reviewed profile with a mandatory architecture guard.
//
// Takes rules ([]syscallRule) which are supplied only by trusted profile construction.
// Takes kill ([]uint32) which holds the syscall numbers that terminate the process.
//
// Returns a bounded default-deny filter, or an error for invalid rules.
func compileSyscallRules(rules []syscallRule, kill []uint32) ([]unix.SockFilter, error) {
	filter := []unix.SockFilter{
		instruction(unix.BPF_LD|unix.BPF_W|unix.BPF_ABS, seccompArchitectureOffset),
		{Code: unix.BPF_JMP | unix.BPF_JEQ | unix.BPF_K, Jt: 1, Jf: 0, K: workerAuditArchitecture},
		instruction(unix.BPF_RET|unix.BPF_K, unix.SECCOMP_RET_KILL_PROCESS),
		instruction(unix.BPF_LD|unix.BPF_W|unix.BPF_ABS, 0),
	}
	for _, rule := range rules {
		body, err := ruleBody(rule.arguments)
		if err != nil {
			return nil, err
		}
		if len(body) > maximumRuleInstructions {
			return nil, ErrUnavailable
		}
		filter = append(filter, unix.SockFilter{
			Code: unix.BPF_JMP | unix.BPF_JEQ | unix.BPF_K, Jt: 0,
			Jf: safeconv.IntToUint8(len(body)), K: rule.number,
		})
		filter = append(filter, body...)
	}

	for _, number := range kill {
		filter = append(filter,
			unix.SockFilter{Code: unix.BPF_JMP | unix.BPF_JEQ | unix.BPF_K, Jt: 0, Jf: 1, K: number},
			instruction(unix.BPF_RET|unix.BPF_K, unix.SECCOMP_RET_KILL_PROCESS),
		)
	}
	filter = append(filter, instruction(unix.BPF_RET|unix.BPF_K, denySyscall))
	if len(filter) > maximumFilterInstructions {
		return nil, ErrUnavailable
	}
	return filter, nil
}

// ruleBody builds argument guards that terminate rather than falling through.
//
// Takes arguments ([]argumentRule) which must all pass for the syscall to run.
//
// Returns []unix.SockFilter which ends with an allow verdict.
// Returns error when an argument or branch cannot be represented safely.
func ruleBody(arguments []argumentRule) ([]unix.SockFilter, error) {
	var body []unix.SockFilter
	for _, argument := range arguments {
		if argument.index >= seccompArgumentCount || len(argument.allowed) == 0 || len(argument.allowed) > maximumRuleInstructions {
			return nil, ErrUnavailable
		}
		offset := seccompArgumentsOffset + argument.index*seccompArgumentBytes
		body = append(body,
			instruction(unix.BPF_LD|unix.BPF_W|unix.BPF_ABS, offset+seccompHighWordOffset),
			unix.SockFilter{Code: unix.BPF_JMP | unix.BPF_JEQ | unix.BPF_K, Jt: 1, Jf: 0, K: 0},
			instruction(unix.BPF_RET|unix.BPF_K, denySyscall),
			instruction(unix.BPF_LD|unix.BPF_W|unix.BPF_ABS, offset),
			instruction(unix.BPF_ALU|unix.BPF_AND|unix.BPF_K, argument.mask),
		)
		for index, allowed := range argument.allowed {
			body = append(body, unix.SockFilter{
				Code: unix.BPF_JMP | unix.BPF_JEQ | unix.BPF_K,
				Jt:   safeconv.IntToUint8(len(argument.allowed) - index), Jf: 0, K: allowed,
			})
		}
		body = append(body, instruction(unix.BPF_RET|unix.BPF_K, denySyscall))
	}
	return append(body, instruction(unix.BPF_RET|unix.BPF_K, unix.SECCOMP_RET_ALLOW)), nil
}

// instruction constructs a non-branching classic BPF instruction.
//
// Takes code (uint16) which is the opcode.
// Takes value (uint32) which is the immediate operand.
//
// Returns unix.SockFilter with both jump offsets initialised to zero.
func instruction(code uint16, value uint32) unix.SockFilter {
	return unix.SockFilter{Code: code, Jt: 0, Jf: 0, K: value}
}
