// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package codec_test

var compiledFunctionSerialised = map[string]string{
	"Body":                       "carried in bytecode.fbs",
	"BoolConstants":              "carried in bytecode.fbs",
	"CallSites":                  "carried in bytecode.fbs",
	"ComplexConstants":           "carried in bytecode.fbs",
	"FloatConstants":             "carried in bytecode.fbs",
	"Functions":                  "carried in bytecode.fbs",
	"GeneralConstantDescriptors": "carried in bytecode.fbs",
	"GeneralConstants":           "carried in bytecode.fbs",
	"HasRecover":                 "carried in bytecode.fbs",
	"IntConstants":               "carried in bytecode.fbs",
	"IsPointerReceiver":          "carried in bytecode.fbs",
	"IsVariadic":                 "carried in bytecode.fbs",
	"Name":                       "carried in bytecode.fbs",
	"NamedResultLocations":       "carried in bytecode.fbs",
	"NumRegisters":               "carried in bytecode.fbs",
	"ParameterKinds":             "carried in bytecode.fbs",
	"ParameterRegisters":         "carried in bytecode.fbs",
	"ResultKinds":                "carried in bytecode.fbs",
	"SourceFile":                 "carried in bytecode.fbs",
	"StringConstants":            "carried in bytecode.fbs",
	"StructLayoutTable":          "carried in bytecode.fbs",
	"TypeNames":                  "carried in bytecode.fbs",
	"TypeTable":                  "carried in bytecode.fbs",
	"TypeTableDescriptors":       "carried in bytecode.fbs",
	"TypeTableInterfaceMethods":  "carried in bytecode.fbs",
	"UintConstants":              "carried in bytecode.fbs",
	"UpvalueDescriptors":         "carried in bytecode.fbs",
	"VariableInitFunction":       "carried in bytecode.fbs",
}

var compiledFunctionNotSerialised = map[string]string{
	"AliasInfo":                   "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ArenaSafeAllocPCs":           "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"FieldStoreArenaSafePCs":      "escape-pass annotation recomputed by RunEscapeAnalysisPass; a function loaded without it copies every field-store value out of the arena, which is correct and merely slower",
	"CachedInlineRefusal":         "runtime cache, populated lazily on first use",
	"MarshalShadowMemo":           "runtime cache, populated lazily on first use",
	"ComplexConstIndex":           "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"DebugEmitHook":               "debug-only side table, carried out of band rather than in the bytecode payload",
	"DebugSourceMap":              "debug-only side table, carried out of band rather than in the bytecode payload",
	"DebugVarTable":               "debug-only side table, carried out of band rather than in the bytecode payload",
	"EmittedInlineBlocker":        "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"EvalShape":                   "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"FloatConstIndex":             "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"GenericDeclaration":          "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"GenericTypeParams":           "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"GenericRecvTypeParams":       "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"GetMethodReceiverTypeNames":  "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"HasReceiver":                 "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"HeapMutationClass":           "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"InPlaceHeaderReusePCs":       "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"InRecursionCycle":            "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"IntConstIndex":               "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"IsGenericFunction":           "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"JumpRangeExceeded":           "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"NamedResultNames":            "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ParameterEscapes":            "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ParameterIsGeneric":          "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"RequiresSpecialisation":      "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"ParameterTypeRefs":           "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ParameterTypedSlicePromoted": "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"PeepholeProvenance":          "debug-only side table, carried out of band rather than in the bytecode payload",
	"PrecomputedAllocCountsValid": "runtime cache, populated lazily on first use",
	"ResultTypeRefs":              "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"SpecialisationOrigin":        "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"Specialisations":             "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"StringConstIndex":            "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"StructLiteralTable":          "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"TinyLeafLayout":              "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"TinyLeafShape":               "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"TypeRefIndex":                "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"UintConstIndex":              "compile-time dedup index into a constant pool; the pool it indexes is serialised, the index is not needed once emission is finished",
	"ASMCallInfoBase":             "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"ASMCallInfoBases":            "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"ASMCallInfoTables":           "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"ASMCallInfoTablesOnce":       "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalChildALayout":            "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalChildBLayout":            "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalChildCLayout":            "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalShapeOnce":               "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalSiteA":                   "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalSiteB":                   "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"EvalSiteC":                   "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"GlobalBases":                 "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"LayoutTypeWords":             "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"LayoutTypeWordsOnce":         "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"NonEmptyConstantMask":        "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"NonZeroBankMask":             "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"PrecomputedAllocCounts":      "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"StructLiteralTableBase":      "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"StructLiteralTableLength":    "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"StructLiteralTableOnce":      "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"SignatureReflectType":        "the function's static Go type for closure type assertions and %T; in-memory only, a loaded bundle falls back to the erased shape built from the register kinds",
	"MethodSignatures":            "method shapes derived from go/types for signature-aware interface checks; in-memory only, a loaded bundle falls back to the arity recorded in the requirement strings",
	"ResultReflectTypes":          "exact static result types consulted when a value leaves the interpreter or a reflect signature is built; in-memory only, a loaded bundle falls back to the bank canonical types",
	"VariadicSliceType":           "the variadic parameter's slice type, used to pack a deferred call's trailing arguments; in-memory only, a loaded bundle packs into []any",
	"InspectsCallStack":           "compile-time flag that keeps calls to a stack-inspecting function out of tail-call and inlining rewrites; a loaded bundle is not rewritten",
	"RuntimeName":                 "the Go-style qualified name runtime.FuncForPC and stack dumps report; in-memory only, a loaded bundle reports the table name",
	"MethodReceiverReflectType":   "the receiver's exact type, giving a method expression a precise callable type; in-memory only, a loaded bundle falls back to the erased shape",
}

var callSiteSerialised = map[string]string{
	"Arguments":              "carried in bytecode.fbs",
	"BlocksHostGoroutine":    "carried in bytecode.fbs",
	"ClosureRegister":        "carried in bytecode.fbs",
	"FunctionIndex":          "carried in bytecode.fbs",
	"IsClosure":              "carried in bytecode.fbs",
	"IsEllipsisSpread":       "carried in bytecode.fbs",
	"IsMethod":               "carried in bytecode.fbs",
	"IsNative":               "carried in bytecode.fbs",
	"MethodReceiverRegister": "carried in bytecode.fbs",
	"NativeRegister":         "carried in bytecode.fbs",
	"Returns":                "carried in bytecode.fbs",
}

var callSiteNotSerialised = map[string]string{
	"ArgCopyProgram":             "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ArgumentStaticTypeNames":    "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"ArgumentStaticTypeStrings":  "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"CachedCallee":               "runtime cache, populated lazily on first use",
	"LinkedTypeArgs":             "generic declaration state derived from go/types, which is not available to a loaded bundle and not needed by it",
	"ParameterInterfaceFlags":    "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"RecursionUnrolled":          "runtime cache, populated lazily on first use",
	"RuntimeVariadicNumFixed":    "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"RuntimeVariadicSliceType":   "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"TailArgsAlias":              "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"TailReuseFrameInPlace":      "optimisation or analysis result whose zero value selects a correct but slower path. Absent from the format; see TestUnreviewedNotSerialisedFieldsAreTracked",
	"AsmMethodRejectedTypeWords": "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"CachedClosureCallee":        "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"CachedClosurePtr":           "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"CachedClosureRoot":          "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"CachedClosureUpvalues":      "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"InlineDescriptorSlots":      "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"InlineDescriptorVictim":     "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"LastReceiverCallee":         "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"LastReceiverTypeWord":       "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"MethodICSlots":              "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"MethodICVictim":             "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"NativeFastPath":             "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"NativeFunctionPath":         "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
	"VariadicArgumentsBuffer":    "runtime cache or dispatch state rebuilt at first execution; unexported until the program-package split and never serialised",
}

var unreviewedNotSerialisedFields = map[string]bool{
	"AliasInfo":                   true,
	"ArenaSafeAllocPCs":           true,
	"ArgCopyProgram":              true,
	"ArgumentStaticTypeNames":     true,
	"ArgumentStaticTypeStrings":   true,
	"EmittedInlineBlocker":        true,
	"EvalShape":                   true,
	"GetMethodReceiverTypeNames":  true,
	"HasReceiver":                 true,
	"HeapMutationClass":           true,
	"InPlaceHeaderReusePCs":       true,
	"InRecursionCycle":            true,
	"JumpRangeExceeded":           true,
	"NamedResultNames":            true,
	"ParameterEscapes":            true,
	"ParameterInterfaceFlags":     true,
	"ParameterTypeRefs":           true,
	"ParameterTypedSlicePromoted": true,
	"ResultTypeRefs":              true,
	"RuntimeVariadicNumFixed":     true,
	"RuntimeVariadicSliceType":    true,
	"StructLiteralTable":          true,
	"TailArgsAlias":               true,
	"TailReuseFrameInPlace":       true,
	"TinyLeafLayout":              true,
	"TinyLeafShape":               true,
}
