// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package extract

import (
	"fmt"
	"go/ast"
	"go/token"
	"path"
	"slices"
	"strings"

	"encoding/json"

	"piko.sh/goastutil"
)

const (
	// DefaultTool is the command named in the generated-file header when a Generator does
	// not set Tool.
	DefaultTool = "pipit extract"

	// reflectPackage is the package name used in AST nodes for the reflect import.
	reflectPackage = "reflect"

	// interpLinkPackage is the short name used in AST nodes for the link import. The full
	// import path is interpLinkImportPath.
	interpLinkPackage = "link"

	// interpLinkImportPath is the public path holding the LinkedFunction sentinel and the
	// Wrap helper. A manifest's link_import_path overrides it.
	interpLinkImportPath = "pipit.sh/pipit/sdk/link"
)

// fileImports says which optional imports a generated symbol file needs.
type fileImports struct {
	// linkPath is the import path of the link package.
	linkPath string

	// fmt is true when wrapper declarations use the fmt package.
	fmt bool

	// sort is true when a fallback helper uses the sort package.
	sort bool

	// link is true when linked generic entries use the link package.
	link bool
}

// wrapperMeta holds metadata about a generated wrapper function for registration in the
// init() symbol map.
type wrapperMeta struct {
	// OriginalName is the original function name from the source package.
	OriginalName string

	// FuncName is the generated wrapper function name.
	FuncName string

	// reflectHelperName, when non-empty, names a hand-written reflective fallback helper in
	// the driven_system_symbols package (see wrapped_generic_fallbacks.go). The wrapper's
	// default type-switch clause emits a call to this helper instead of a panic, eliminating
	// the "unsupported type %T" footgun for any element type that meets the generic's
	// constraint.
	//
	// Takes precedence over fallback when both are set; in practice they don't overlap
	// because reflective fallbacks fire on bare generic functions (slices.Sort, cmp.Compare)
	// while comparator fallbacks fire on *Func variants (slices.SortFunc, MinFunc).
	reflectHelperName string

	// fallback records which reflect-based comparator fallback the wrapper's default
	// type-switch clause uses (slices.SortFunc / MinFunc / MaxFunc shape), so the file
	// generator can emit the required helper functions and imports.
	fallback comparatorFallbackKind
}

// symbolEntry pairs a symbol name with its AST expression for use in the generated init()
// map literal.
type symbolEntry struct {
	// expression is the AST expression for the symbol's reflect.ValueOf call.
	expression ast.Expr

	// name is the symbol name used as the map key.
	name string
}

// defaultGenerator is the Generator the package-level Generate functions use.
var defaultGenerator = Generator{Tool: DefaultTool}

// Generator writes generated files whose header names the command that produced them. The
// zero value names DefaultTool.
type Generator struct {
	// Tool is the command named in the "Code generated by" header, for example "pipit
	// extract". Empty selects DefaultTool.
	Tool string
}

// GenerateFile calls Generator.GenerateFile with the default tool name.
//
// Takes extractedPackage (ExtractedPackage) which provides the package and its symbols.
// Takes outputPackage (string) which is the Go package name of the generated file.
// Takes generatorConfig (PackageConfig) which provides the generic configuration.
//
// Returns []byte which is the formatted Go source, nil when the package has no symbols.
// Returns error when generation fails.
func GenerateFile(extractedPackage ExtractedPackage, outputPackage string, generatorConfig PackageConfig) ([]byte, error) {
	return defaultGenerator.GenerateFile(extractedPackage, outputPackage, generatorConfig)
}

// GenerateFile produces the Go source code for a single package's symbol file. For
// packages with generic configuration, it also generates dispatch wrapper functions.
//
// Takes extractedPackage (ExtractedPackage) which provides the extracted package metadata
// and symbols.
// Takes outputPackage (string) which specifies the Go package name for the generated
// file.
// Takes generatorConfig (PackageConfig) which provides the generic type configuration for
// wrapper generation.
//
// Returns the formatted Go source bytes or an error if generation fails.
func (g Generator) GenerateFile(extractedPackage ExtractedPackage, outputPackage string, generatorConfig PackageConfig) ([]byte, error) {
	alias := importAlias(extractedPackage)
	symbols := buildSymbolEntries(extractedPackage, alias)

	var wrapperDecls []*ast.FuncDecl
	var wrapperMetas []wrapperMeta
	if generatorConfig.IsGeneric() && len(extractedPackage.GenericFuncs) > 0 {
		var err error
		wrapperDecls, wrapperMetas, err = generateWrappers(extractedPackage, alias, generatorConfig)
		if err != nil {
			return nil, fmt.Errorf("generating wrappers for %s: %w", extractedPackage.ImportPath, err)
		}
	}

	linkedEntries := buildLinkedEntries(extractedPackage, alias)
	linkedEntries = append(linkedEntries, buildLinkedTypeEntries(extractedPackage)...)
	linkedEntries = append(linkedEntries, buildNativeBackedTypeEntries(extractedPackage, alias)...)

	instantiationEntries, err := buildGenericInstantiationEntries(extractedPackage, alias, generatorConfig)
	if err != nil {
		return nil, fmt.Errorf("instantiating generics for %s: %w", extractedPackage.ImportPath, err)
	}

	if len(symbols) == 0 && len(wrapperDecls) == 0 && len(linkedEntries) == 0 && len(instantiationEntries) == 0 {
		return nil, nil
	}

	fallbackHelperDecls, needSortImport, err := buildFallbackHelperDecls(wrapperMetas)
	if err != nil {
		return nil, fmt.Errorf("building fallback helpers for %s: %w", extractedPackage.ImportPath, err)
	}

	mapEntries := buildMapEntries(symbols, wrapperMetas, append(linkedEntries, instantiationEntries...))
	initFunc := buildInitFuncAST(extractedPackage.ImportPath, mapEntries)

	fset := token.NewFileSet()
	file := &ast.File{
		Name:  goastutil.CachedIdent(outputPackage),
		Decls: assembleFileDecls(wrapperDecls, fallbackHelperDecls, initFunc),
	}

	linkImportPath := generatorConfig.LinkImportPath
	if linkImportPath == "" {
		linkImportPath = interpLinkImportPath
	}
	addGeneratedFileImports(fset, file, extractedPackage, alias, fileImports{
		linkPath: linkImportPath,
		fmt:      len(wrapperDecls) > 0 || len(fallbackHelperDecls) > 0,
		sort:     needSortImport,
		link:     len(linkedEntries) > 0,
	})

	formatted, err := goastutil.FormatAST(fset, file)
	if err != nil {
		return nil, fmt.Errorf("formatting generated code for %s: %w", extractedPackage.ImportPath, err)
	}

	return append([]byte(g.generatedHeader(generatorConfig.BuildTag)), formatted...), nil
}

// assembleFileDecls orders the wrapper, fallback helper, and init declarations into a
// single declaration slice for the generated file.
//
// Takes wrapperDecls ([]*ast.FuncDecl) which provides the dispatch wrapper declarations.
// Takes fallbackHelperDecls ([]*ast.FuncDecl) which provides the reflect-based fallback
// helper declarations.
// Takes initFunc (*ast.FuncDecl) which is the symbol map init function.
//
// Returns the ordered declaration slice.
func assembleFileDecls(wrapperDecls, fallbackHelperDecls []*ast.FuncDecl, initFunc *ast.FuncDecl) []ast.Decl {
	decls := make([]ast.Decl, 0, len(wrapperDecls)+len(fallbackHelperDecls)+1)
	for _, d := range wrapperDecls {
		decls = append(decls, d)
	}
	for _, d := range fallbackHelperDecls {
		decls = append(decls, d)
	}
	return append(decls, initFunc)
}

// addGeneratedFileImports adds the import declarations the generated file requires,
// conditionally including fmt, sort, and the interp_link import based on which features
// the file uses.
//
// Takes fset (*token.FileSet) which positions the added imports.
// Takes file (*ast.File) which receives the import declarations.
// Takes extractedPackage (ExtractedPackage) which supplies the target package import
// path.
// Takes alias (string) which is the import alias for the target package.
// Takes needs (fileImports) which says which optional imports the file uses.
func addGeneratedFileImports(
	fset *token.FileSet,
	file *ast.File,
	extractedPackage ExtractedPackage,
	alias string,
	needs fileImports,
) {
	goastutil.AddImport(fset, file, reflectPackage)
	if strings.Contains(extractedPackage.ImportPath, "/") {
		goastutil.AddNamedImport(fset, file, alias, extractedPackage.ImportPath)
	} else {
		goastutil.AddImport(fset, file, extractedPackage.ImportPath)
	}
	if needs.fmt {
		goastutil.AddImport(fset, file, "fmt")
	}
	if needs.sort {
		goastutil.AddImport(fset, file, "sort")
	}
	if needs.link {
		goastutil.AddImport(fset, file, needs.linkPath)
	}
}

// OutputFileName returns the generated file name for a package. For example,
// "encoding/json" becomes "gen_encoding_json.go".
//
// Takes importPath (string) which specifies the Go import path to convert.
//
// Returns the generated file name with slashes replaced by underscores.
func OutputFileName(importPath string) string {
	safe := strings.ReplaceAll(importPath, "/", "_")
	return "gen_" + safe + ".go"
}

// GenerateRegisterFile calls Generator.GenerateRegisterFile with the default tool name.
//
// Takes outputPackage (string) which is the Go package name of the generated file.
//
// Returns the formatted Go source bytes or an error if formatting fails.
func GenerateRegisterFile(outputPackage string) ([]byte, error) {
	return defaultGenerator.GenerateRegisterFile(outputPackage)
}

// GenerateRegisterFile produces the bootstrapping Go source that declares the
// package-level Symbols map that every gen_*.go file's init() populates. Without this
// file the per-package generated files fail to compile with "undefined: Symbols".
//
// Takes outputPackage (string) which specifies the Go package name for the generated
// file.
//
// Returns the formatted Go source bytes or an error if formatting fails.
func (g Generator) GenerateRegisterFile(outputPackage string) ([]byte, error) {
	fset := token.NewFileSet()
	file := &ast.File{
		Name: goastutil.CachedIdent(outputPackage),
		Decls: []ast.Decl{
			&ast.GenDecl{
				Tok: token.VAR,
				Specs: []ast.Spec{
					&ast.ValueSpec{
						Names: []*ast.Ident{goastutil.CachedIdent("Symbols")},
						Values: []ast.Expr{
							&ast.CallExpr{
								Fun: goastutil.CachedIdent("make"),
								Args: []ast.Expr{
									&ast.MapType{
										Key: goastutil.CachedIdent("string"),
										Value: &ast.MapType{
											Key: goastutil.CachedIdent("string"),
											Value: &ast.SelectorExpr{
												X:   goastutil.CachedIdent(reflectPackage),
												Sel: goastutil.CachedIdent("Value"),
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
	}

	goastutil.AddImport(fset, file, reflectPackage)

	formatted, err := goastutil.FormatAST(fset, file)
	if err != nil {
		return nil, fmt.Errorf("formatting register file: %w", err)
	}
	return append([]byte(g.generatedHeader("")), formatted...), nil
}

// marker returns the "Code generated" comment that marks a file as generated, so tools
// such as go vet and editors treat it as read-only.
//
// Returns string which is the comment line, without a trailing newline.
func (g Generator) marker() string {
	tool := g.Tool
	if tool == "" {
		tool = DefaultTool
	}
	return "// Code generated by '" + tool + "'. DO NOT EDIT."
}

// generatedHeader returns the code-generation header comment for a generated file,
// appending a build constraint when buildTag is set.
//
// Takes buildTag (string) which is an optional Go build constraint, or empty for no
// constraint.
//
// Returns the header string to prepend to the formatted source.
func (g Generator) generatedHeader(buildTag string) string {
	if buildTag != "" {
		return g.marker() + "\n\n//go:build " + buildTag + "\n\n"
	}
	return g.marker() + "\n\n"
}

// buildSymbolEntries filters typed symbols and builds symbolEntry values for each, using
// the given import alias.
//
// Takes extractedPackage (ExtractedPackage) which provides the extracted package with its
// symbols.
// Takes alias (string) which specifies the import alias for qualified references.
//
// Returns a slice of symbolEntry values for non-untyped symbols.
func buildSymbolEntries(extractedPackage ExtractedPackage, alias string) []symbolEntry {
	var symbols []symbolEntry
	for _, symbol := range extractedPackage.Symbols {
		if symbol.IsUntypedConst {
			continue
		}
		symbols = append(symbols, symbolEntry{
			name:       symbol.Name,
			expression: symbolExpressionAST(symbol, alias),
		})
	}
	return symbols
}

// buildMapEntries constructs the AST key-value expressions for the symbol map literal
// from regular symbols, generated wrappers, and //piko:link-backed linked generics.
//
// Takes symbols ([]symbolEntry) which provides the regular symbol entries.
// Takes wrapperMetas ([]wrapperMeta) which provides the generated wrapper metadata.
// Takes linkedEntries ([]symbolEntry) which provides linked generic entries
// (reflect.ValueOf(interp_link.WrapFunc(...)) calls).
//
// Returns a slice of AST key-value expressions for the map literal.
func buildMapEntries(symbols []symbolEntry, wrapperMetas []wrapperMeta, linkedEntries []symbolEntry) []ast.Expr {
	mapEntries := make([]ast.Expr, 0, len(symbols)+len(wrapperMetas)+len(linkedEntries))
	for _, s := range symbols {
		mapEntries = append(mapEntries, goastutil.KeyValueExpr(goastutil.StrLit(s.name), s.expression))
	}
	for _, meta := range wrapperMetas {
		mapEntries = append(mapEntries, goastutil.KeyValueExpr(
			goastutil.StrLit(meta.OriginalName),
			goastutil.CallExpr(
				goastutil.SelectorExpr(reflectPackage, "ValueOf"),
				goastutil.CachedIdent(meta.FuncName),
			),
		))
	}
	for _, link := range linkedEntries {
		mapEntries = append(mapEntries, goastutil.KeyValueExpr(
			goastutil.StrLit(link.name),
			link.expression,
		))
	}
	return mapEntries
}

// buildLinkedEntries produces symbolEntry values for every generic function annotated
// with //piko:link in the source package. Each expression evaluates to
// reflect.ValueOf(interp_link.WrapFunc(N, pkg.Sibling, params, results, variadic)).
//
// Takes extractedPackage (ExtractedPackage) which holds the parsed LinkedGenericFuncInfo
// entries for the package.
// Takes alias (string) which is the import alias for the target package used to qualify
// the sibling reference.
//
// Returns a slice of symbolEntry values keyed by the generic's exported name so user .pk
// code calling pkg.Name[T] resolves through the linked symbol.
func buildLinkedEntries(extractedPackage ExtractedPackage, alias string) []symbolEntry {
	if len(extractedPackage.LinkedGenericFuncs) == 0 {
		return nil
	}
	entries := make([]symbolEntry, 0, len(extractedPackage.LinkedGenericFuncs))
	for _, link := range extractedPackage.LinkedGenericFuncs {
		reflectValueOf := goastutil.SelectorExpr(reflectPackage, "ValueOf")
		wrapCall := goastutil.CallExpr(
			goastutil.SelectorExpr(interpLinkPackage, "WrapFunc"),
			goastutil.IntLit(link.TypeArgCount),
			goastutil.SelectorExpr(alias, link.LinkTarget),
			buildGenericFieldTypeSliceExpr(link.Params),
			buildGenericFieldTypeSliceExpr(link.Results),
			goastutil.CachedIdent(boolLiteral(link.Variadic)),
		)
		entries = append(entries, symbolEntry{
			name:       link.Name,
			expression: goastutil.CallExpr(reflectValueOf, wrapCall),
		})
	}
	return entries
}

// buildInitFuncAST constructs the init() function declaration that populates the Symbols
// map for a given import path.
//
// Takes importPath (string) which specifies the key for the Symbols map.
// Takes mapEntries ([]ast.Expr) which provides the key-value expressions for the map
// literal.
//
// Returns the AST function declaration for the init function.
func buildInitFuncAST(importPath string, mapEntries []ast.Expr) *ast.FuncDecl {
	initBody := &ast.AssignStmt{
		Lhs: []ast.Expr{
			&ast.IndexExpr{
				X:     goastutil.CachedIdent("Symbols"),
				Index: goastutil.StrLit(importPath),
			},
		},
		Tok: token.ASSIGN,
		Rhs: []ast.Expr{
			goastutil.CompositeLit(
				&ast.MapType{
					Key:   goastutil.CachedIdent("string"),
					Value: goastutil.SelectorExpr(reflectPackage, "Value"),
				},
				mapEntries...,
			),
		},
	}
	return goastutil.FuncDecl("init", nil, nil, goastutil.BlockStmt(initBody))
}

// symbolExpressionAST returns the AST expression for registering a symbol via
// reflect.ValueOf.
//
// Takes symbol (ExtractedSymbol) which provides the extracted symbol metadata.
// Takes alias (string) which specifies the import alias for the package reference.
//
// Returns the AST expression wrapping the symbol in reflect.ValueOf.
func symbolExpressionAST(symbol ExtractedSymbol, alias string) ast.Expr {
	qualified := goastutil.SelectorExpr(alias, symbol.Name)
	reflectValueOf := goastutil.SelectorExpr(reflectPackage, "ValueOf")

	switch symbol.Kind {
	case SymbolVar:
		return goastutil.CallExpr(
			goastutil.SelectorExprFrom(
				goastutil.CallExpr(reflectValueOf, goastutil.AddressExpr(qualified)),
				"Elem",
			),
		)

	case SymbolType:
		castExpr := &ast.CallExpr{
			Fun:  &ast.ParenExpr{X: goastutil.StarExpr(qualified)},
			Args: []ast.Expr{goastutil.NilIdent()},
		}
		return goastutil.CallExpr(reflectValueOf, castExpr)

	default:
		return goastutil.CallExpr(reflectValueOf, qualified)
	}
}

// importAlias returns the import alias to use for a package, handling collision avoidance
// with the reflect package.
//
// Takes extractedPackage (ExtractedPackage) which provides the extracted package
// metadata.
//
// Returns the alias string for use in import declarations.
func importAlias(extractedPackage ExtractedPackage) string {
	baseName := path.Base(extractedPackage.ImportPath)

	if !strings.Contains(extractedPackage.ImportPath, "/") {
		return baseName
	}

	alias := extractedPackage.Name
	if alias == reflectPackage {
		alias = "_reflect"
	}

	return alias
}

// typesDescriptor is the JSON structure for the types descriptor file.
type typesDescriptor struct {
	// ImportPaths lists the Go import paths included in the descriptor.
	ImportPaths []string `json:"import_paths"`
}

// GenerateTypesDescriptorFile produces a JSON descriptor listing all extracted import
// paths. The descriptor enables piko bytecode to load types.Package objects for these
// packages at compile time.
//
// Takes importPaths ([]string) which lists the import paths to include.
//
// Returns the JSON bytes or an error if marshalling fails.
func GenerateTypesDescriptorFile(importPaths []string) ([]byte, error) {
	sorted := make([]string, len(importPaths))
	copy(sorted, importPaths)
	slices.Sort(sorted)

	descriptor := typesDescriptor{ImportPaths: sorted}
	output, err := json.MarshalIndent(descriptor, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshalling types descriptor: %w", err)
	}

	return append(output, '\n'), nil
}

// ReadTypesDescriptor parses a types descriptor JSON file and returns the import paths
// listed within it.
//
// Takes data ([]byte) which is the raw JSON content.
//
// Returns []string which lists the import paths from the descriptor.
// Returns error when the JSON is malformed.
func ReadTypesDescriptor(data []byte) ([]string, error) {
	var descriptor typesDescriptor
	if err := json.Unmarshal(data, &descriptor); err != nil {
		return nil, fmt.Errorf("parsing types descriptor: %w", err)
	}
	return descriptor.ImportPaths, nil
}
