// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

package isa

// tierSub1Specs holds the tier-1 rows (two-operand operations).
var tierSub1Specs = []OpSpec{
	sub1(SubOpDrillTier2, "DRILL_TIER2").flags(specMeta),
	sub1(SubOpMathSin, "MATH_SIN").cost(costMedium).handler("handleFlatSubOpMathSin").asmIn("tier1JumpTable", "handlerSubOpMathSin").pure(),
	sub1(SubOpMathCos, "MATH_COS").cost(costMedium).handler("handleFlatSubOpMathCos").asmIn("tier1JumpTable", "handlerSubOpMathCos").pure(),
	sub1(SubOpMathExp, "MATH_EXP").cost(costMedium).handler("handleFlatSubOpMathExp").asmIn("tier1JumpTable", "handlerSubOpMathExp").pure(),
	sub1(SubOpMathTan, "MATH_TAN").cost(costMedium).handler("handleFlatSubOpMathTan").asmIn("tier1JumpTable", "handlerSubOpMathTan").pure(),
	sub1(SubOpMathMod, "MATH_MOD").cost(costMedium).handler("handleFlatSubOpMathMod").asmIn("tier1JumpTable", "handlerSubOpMathMod").pure(),
	sub1(SubOpStrconvFormatBool, "STRCONV_FORMAT_BOOL").cost(costMedium).handler("handleFlatSubOpStrconvFormatBool").asmIn("tier1JumpTable", "handlerSubOpStrconvFormatBool").pure(),
	sub1(SubOpStrconvFormatInt, "STRCONV_FORMAT_INT").cost(costMedium).handler("handleFlatSubOpStrconvFormatInt").asmIn("tier1JumpTable", "handlerSubOpStrconvFormatInt").pure(),
	sub1(SubOpStrconvItoa, "STRCONV_ITOA").cost(costMedium).handler("handleFlatSubOpStrconvItoa").asmIn("tier1JumpTable", "handlerSubOpStrconvItoa").pure(),
	sub1(SubOpRealComplex, "REAL_COMPLEX").cost(costCheap).handler("handleFlatSubOpRealComplex").asmIn("tier1JumpTable", "handlerSubOpRealComplex").pure(),
	sub1(SubOpImagComplex, "IMAG_COMPLEX").cost(costCheap).handler("handleFlatSubOpImagComplex").asmIn("tier1JumpTable", "handlerSubOpImagComplex").pure(),
	sub1(SubOpBytesToString, "BYTES_TO_STRING").cost(costMedium).handler("handleFlatSubOpBytesToString").asmIn("tier1JumpTable", "handlerSubOpBytesToString").pure(),
	sub1(SubOpMakeMethodExpr, "MAKE_METHOD_EXPR").cost(costModerate).handler("runMakeMethodExpr").pure(),
	sub1(SubOpCap, "CAP").cost(costCheap).handler("handleFlatSubOpCap").asmIn("tier1JumpTable", "handlerSubOpCap").pure(),
	sub1(SubOpNegComplex, "NEG_COMPLEX").cost(costCheap).handler("handleFlatSubOpNegComplex").asmIn("tier1JumpTable", "handlerSubOpNegComplex").pure(),
	sub1(SubOpMoveComplex, "MOVE_COMPLEX").cost(costFree).handler("handleFlatSubOpMoveComplex").asmIn("tier1JumpTable", "handlerSubOpMoveComplex").pure(),
	sub1(SubOpMakeSliceInt, "MAKE_SLICE_INT").cost(costVeryHeavy).handler("handleSubOpMakeSliceInt").asmIn("tier1JumpTable", "handlerSubOpMakeSliceInt").pure(),
	sub1(SubOpLenSliceIntDirect, "LEN_SLICE_INT_DIRECT").cost(costCheap).handler("handleSubOpLenSliceIntDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceIntDirect").pure(),
	sub1(SubOpMakeSliceFloat, "MAKE_SLICE_FLOAT").cost(costVeryHeavy).handler("handleSubOpMakeSliceFloat").asmIn("tier1JumpTable", "handlerSubOpMakeSliceFloat").pure(),
	sub1(SubOpSliceGetFloatDirect, "SLICE_GET_FLOAT_DIRECT").cost(costModerate).handler("handleSubOpSliceGetFloatDirect").asmIn("tier1JumpTable", "handlerSubOpSliceGetFloatDirect").pure(),
	sub1(SubOpSliceSetFloatDirect, "SLICE_SET_FLOAT_DIRECT").cost(costModerate).handler("handleSubOpSliceSetFloatDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSetFloatDirect").mutates(),
	sub1(SubOpLenSliceFloatDirect, "LEN_SLICE_FLOAT_DIRECT").cost(costCheap).handler("handleSubOpLenSliceFloatDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceFloatDirect").pure(),
	sub1(SubOpMakeSliceString, "MAKE_SLICE_STRING").cost(costVeryHeavy).handler("handleSubOpMakeSliceString").asmIn("tier1JumpTable", "handlerSubOpMakeSliceString").pure(),
	sub1(SubOpSliceGetStringDirect, "SLICE_GET_STRING_DIRECT").cost(costModerate).handler("handleSubOpSliceGetStringDirect").asmIn("tier1JumpTable", "handlerSubOpSliceGetStringDirect").pure(),
	sub1(SubOpSliceSetStringDirect, "SLICE_SET_STRING_DIRECT").cost(costModerate).
		handler("handleSubOpSliceSetStringDirect").exit("handlerSubOpSliceSetStringDirectExit", "exitSliceSetStringDirect").mutates(),
	sub1(SubOpLenSliceStringDirect, "LEN_SLICE_STRING_DIRECT").cost(costCheap).handler("handleSubOpLenSliceStringDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceStringDirect").pure(),
	sub1(SubOpMakeSliceBool, "MAKE_SLICE_BOOL").cost(costVeryHeavy).handler("handleSubOpMakeSliceBool").asmIn("tier1JumpTable", "handlerSubOpMakeSliceBool").pure(),
	sub1(SubOpSliceGetBoolDirect, "SLICE_GET_BOOL_DIRECT").cost(costModerate).handler("handleSubOpSliceGetBoolDirect").asmIn("tier1JumpTable", "handlerSubOpSliceGetBoolDirect").pure(),
	sub1(SubOpSliceSetBoolDirect, "SLICE_SET_BOOL_DIRECT").cost(costModerate).handler("handleSubOpSliceSetBoolDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSetBoolDirect").mutates(),
	sub1(SubOpLenSliceBoolDirect, "LEN_SLICE_BOOL_DIRECT").cost(costCheap).handler("handleSubOpLenSliceBoolDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceBoolDirect").pure(),
	sub1(SubOpMakeSliceUint, "MAKE_SLICE_UINT").cost(costVeryHeavy).handler("handleSubOpMakeSliceUint").asmIn("tier1JumpTable", "handlerSubOpMakeSliceUint").pure(),
	sub1(SubOpSliceGetUintDirect, "SLICE_GET_UINT_DIRECT").cost(costModerate).handler("handleSubOpSliceGetUintDirect").asmIn("tier1JumpTable", "handlerSubOpSliceGetUintDirect").pure(),
	sub1(SubOpSliceSetUintDirect, "SLICE_SET_UINT_DIRECT").cost(costModerate).handler("handleSubOpSliceSetUintDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSetUintDirect").mutates(),
	sub1(SubOpLenSliceUintDirect, "LEN_SLICE_UINT_DIRECT").cost(costCheap).handler("handleSubOpLenSliceUintDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceUintDirect").pure(),
	sub1(SubOpBoxSliceInt, "BOX_SLICE_INT").cost(costFree).handler("handleSubOpBoxSliceInt").asmIn("tier1JumpTable", "handlerSubOpBoxSliceInt").pure(),
	sub1(SubOpMoveInt, "MOVE_INT").cost(costFree).handler("handleFlatSubOpMoveInt").asmIn("tier1JumpTable", "handlerSubOpMoveInt").pure(),
	sub1(SubOpMoveFloat, "MOVE_FLOAT").cost(costFree).handler("handleFlatSubOpMoveFloat").asmIn("tier1JumpTable", "handlerSubOpMoveFloat").pure(),
	sub1(SubOpMoveString, "MOVE_STRING").cost(costFree).handler("handleFlatSubOpMoveString").asmIn("tier1JumpTable", "handlerSubOpMoveString").pure(),
	sub1(SubOpMoveBool, "MOVE_BOOL").cost(costFree).handler("handleFlatSubOpMoveBool").asmIn("tier1JumpTable", "handlerSubOpMoveBool").pure(),
	sub1(SubOpMoveUint, "MOVE_UINT").cost(costFree).handler("handleFlatSubOpMoveUint").asmIn("tier1JumpTable", "handlerSubOpMoveUint").pure(),
	sub1(SubOpMoveIntToGeneral, "MOVE_INT_TO_GENERAL").cost(costFree).handler("handleFlatSubOpMoveIntToGeneral").pure(),
	sub1(SubOpMoveGeneralToInt, "MOVE_GENERAL_TO_INT").cost(costFree).handler("handleFlatSubOpMoveGeneralToInt").pure(),
	sub1(SubOpMoveFloatToGeneral, "MOVE_FLOAT_TO_GENERAL").cost(costFree).handler("handleFlatSubOpMoveFloatToGeneral").pure(),
	sub1(SubOpMoveGeneralToFloat, "MOVE_GENERAL_TO_FLOAT").cost(costFree).handler("handleFlatSubOpMoveGeneralToFloat").pure(),
	sub1(SubOpMoveStringToGeneral, "MOVE_STRING_TO_GENERAL").cost(costFree).handler("handleFlatSubOpMoveStringToGeneral").pure(),
	sub1(SubOpMoveGeneralToString, "MOVE_GENERAL_TO_STRING").cost(costFree).handler("handleFlatSubOpMoveGeneralToString").pure(),
	sub1(SubOpNegInt, "NEG_INT").cost(costCheap).handler("handleFlatSubOpNegInt").asmIn("tier1JumpTable", "handlerSubOpNegInt").pure(),
	sub1(SubOpNegFloat, "NEG_FLOAT").cost(costCheap).handler("handleFlatSubOpNegFloat").asmIn("tier1JumpTable", "handlerSubOpNegFloat").pure(),
	sub1(SubOpBitNot, "BIT_NOT").cost(costCheap).handler("handleFlatSubOpBitNot").asmIn("tier1JumpTable", "handlerSubOpBitNot").pure(),
	sub1(SubOpBitNotUint, "BIT_NOT_UINT").cost(costCheap).handler("handleFlatSubOpBitNotUint").pure(),
	sub1(SubOpIntToFloat, "INT_TO_FLOAT").cost(costCheap).handler("handleFlatSubOpIntToFloat").asmIn("tier1JumpTable", "handlerSubOpIntToFloat").pure(),
	sub1(SubOpFloatToInt, "FLOAT_TO_INT").cost(costCheap).handler("handleFlatSubOpFloatToInt").asmIn("tier1JumpTable", "handlerSubOpFloatToInt").pure(),
	sub1(SubOpNot, "NOT").cost(costCheap).handler("handleFlatSubOpNot").pure(),
	sub1(SubOpBoolToInt, "BOOL_TO_INT").cost(costCheap).handler("handleFlatSubOpBoolToInt").pure(),
	sub1(SubOpIntToBool, "INT_TO_BOOL").cost(costCheap).handler("handleFlatSubOpIntToBool").pure(),
	sub1(SubOpIntToUint, "INT_TO_UINT").cost(costCheap).handler("handleFlatSubOpIntToUint").pure(),
	sub1(SubOpUintToInt, "UINT_TO_INT").cost(costCheap).handler("handleFlatSubOpUintToInt").pure(),
	sub1(SubOpUintToFloat, "UINT_TO_FLOAT").cost(costCheap).handler("handleFlatSubOpUintToFloat").asmIn("tier1JumpTable", "handlerSubOpUintToFloat").pure(),
	sub1(SubOpFloatToUint, "FLOAT_TO_UINT").cost(costCheap).handler("handleFlatSubOpFloatToUint").asmIn("tier1JumpTable", "handlerSubOpFloatToUint").pure(),
	sub1(SubOpMathSqrt, "MATH_SQRT").cost(costMedium).handler("handleFlatSubOpMathSqrt").asmIn("tier1JumpTable", "handlerSubOpMathSqrt").pure(),
	sub1(SubOpMathAbs, "MATH_ABS").cost(costMedium).handler("handleFlatSubOpMathAbs").asmIn("tier1JumpTable", "handlerSubOpMathAbs").pure(),
	sub1(SubOpMathFloor, "MATH_FLOOR").cost(costMedium).handler("handleFlatSubOpMathFloor").asmIn("tier1JumpTable", "handlerSubOpMathFloor").pure(),
	sub1(SubOpMathCeil, "MATH_CEIL").cost(costMedium).handler("handleFlatSubOpMathCeil").asmIn("tier1JumpTable", "handlerSubOpMathCeil").pure(),
	sub1(SubOpMathTrunc, "MATH_TRUNC").cost(costMedium).handler("handleFlatSubOpMathTrunc").asmIn("tier1JumpTable", "handlerSubOpMathTrunc").pure(),
	sub1(SubOpMathRound, "MATH_ROUND").cost(costMedium).handler("handleFlatSubOpMathRound").asmIn("tier1JumpTable", "handlerSubOpMathRound").pure(),
	sub1(SubOpLenString, "LEN_STRING").cost(costMedium).handler("handleFlatSubOpLenString").asmIn("tier1JumpTable", "handlerSubOpLenString").pure(),
	sub1(SubOpRuneToString, "RUNE_TO_STRING").cost(costMedium).handler("handleFlatSubOpRuneToString").pure(),
	sub1(SubOpStrToUpper, "STR_TO_UPPER").cost(costMedium).handler("handleFlatSubOpStrToUpper").pure(),
	sub1(SubOpStrToLower, "STR_TO_LOWER").cost(costMedium).handler("handleFlatSubOpStrToLower").pure(),
	sub1(SubOpStrTrimSpace, "STR_TRIM_SPACE").cost(costMedium).handler("handleFlatSubOpStrTrimSpace").pure(),
	sub1(SubOpLen, "LEN").cost(costCheap).handler("handleFlatSubOpLen").pure(),
	sub1(SubOpStringToBytes, "STRING_TO_BYTES").cost(costMedium).handler("handleFlatSubOpStringToBytes").pure(),
	sub1(SubOpUnsafeStringData, "UNSAFE_STRING_DATA").cost(costFree).handler("handleFlatSubOpUnsafeStringData").mutates(),
	sub1(SubOpUnsafeSliceData, "UNSAFE_SLICE_DATA").cost(costFree).handler("handleFlatSubOpUnsafeSliceData").mutates(),
	sub1(SubOpJump, "JUMP").cost(costCheap).handler("handleJump").asmIn("tier1JumpTable", "handlerJump").flags(SpecJump).pure(),
	sub1(SubOpLoadIntConstSmall, "LOAD_INT_CONST_SMALL").cost(costFree).handler("handleFlatSubOpLoadIntConstSmall").asmIn("tier1JumpTable", "handlerLoadIntConstSmall").pure(),
	sub1(SubOpLoadBool, "LOAD_BOOL").cost(costFree).handler("handleFlatSubOpLoadIntConstSmall").asmIn("tier1JumpTable", "handlerLoadBool").pure(),
	sub1(SubOpIncIntJumpLt, "INC_INT_JUMP_LT").cost(costCheap).handler("handleFlatSubOpIncIntJumpLt").asmIn("tier1JumpTable", "handlerIncIntJumpLt").flags(SpecJump).pure(),
	sub1(SubOpLenStringLtJumpFalse, "LEN_STRING_LT_JUMP_FALSE").cost(costMedium).handler("handleFlatSubOpLenStringLtJumpFalse").
		asmIn("tier1JumpTable", "handlerLenStringLtJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpLoadZero, "LOAD_ZERO").cost(costFree).handler("handleFlatSubOpLoadZero").pure(),
	sub1(SubOpMakeChannel, "MAKE_CHANNEL").cost(costVeryHeavy).handler("handleFlatSubOpMakeChannel").pure(),
	sub1(SubOpMapDelete, "MAP_DELETE").cost(costModerate).handler("handleFlatSubOpMapDelete").mutates(),
	sub1(SubOpChannelReceive, "CHANNEL_RECEIVE").cost(costModerate).handler("handleFlatSubOpChannelReceive").mutates(),
	sub1(SubOpGetMethod, "GET_METHOD").cost(costModerate).handler("handleFlatSubOpGetMethod").pure(),
	sub1(SubOpSpill, "SPILL").cost(costFree).handler("handleFlatSubOpSpill").pure(),
	sub1(SubOpReload, "RELOAD").cost(costFree).handler("handleFlatSubOpReload").pure(),
	sub1(SubOpGetStructFieldInt, "GET_STRUCT_FIELD_INT").cost(costMedium).handler("handleGetStructFieldUnsafeInt").pure(),
	sub1(SubOpGetStructFieldUint, "GET_STRUCT_FIELD_UINT").cost(costMedium).handler("handleGetStructFieldUnsafeUint").pure(),
	sub1(SubOpGetStructFieldFloat, "GET_STRUCT_FIELD_FLOAT").cost(costMedium).handler("handleGetStructFieldUnsafeFloat").pure(),
	sub1(SubOpGetStructFieldBool, "GET_STRUCT_FIELD_BOOL").cost(costMedium).handler("handleGetStructFieldUnsafeBool").pure(),
	sub1(SubOpGetStructFieldString, "GET_STRUCT_FIELD_STRING").cost(costMedium).handler("handleGetStructFieldUnsafeString").pure(),
	sub1(SubOpSetStructFieldInt, "SET_STRUCT_FIELD_INT").cost(costMedium).handler("handleSetStructFieldUnsafeInt").mutates(),
	sub1(SubOpSetStructFieldUint, "SET_STRUCT_FIELD_UINT").cost(costMedium).handler("handleSetStructFieldUnsafeUint").mutates(),
	sub1(SubOpSetStructFieldFloat, "SET_STRUCT_FIELD_FLOAT").cost(costMedium).handler("handleSetStructFieldUnsafeFloat").mutates(),
	sub1(SubOpSetStructFieldBool, "SET_STRUCT_FIELD_BOOL").cost(costMedium).handler("handleSetStructFieldUnsafeBool").mutates(),
	sub1(SubOpSetStructFieldString, "SET_STRUCT_FIELD_STRING").cost(costMedium).handler("handleSetStructFieldUnsafeString").mutates(),
	sub1(SubOpAddUintConst, "ADD_UINT_CONST").cost(costCheap).handler("handleFlatSubOpAddUintConst").asmIn("tier1JumpTable", "handlerSubOpAddUintConst").pure(),
	sub1(SubOpSubUintConst, "SUB_UINT_CONST").cost(costCheap).handler("handleFlatSubOpSubUintConst").asmIn("tier1JumpTable", "handlerSubOpSubUintConst").pure(),
	sub1(SubOpBitAndUintConst, "BIT_AND_UINT_CONST").cost(costCheap).handler("handleFlatSubOpBitAndUintConst").asmIn("tier1JumpTable", "handlerSubOpBitAndUintConst").pure(),
	sub1(SubOpLoadUintConstSmall, "LOAD_UINT_CONST_SMALL").cost(costFree).handler("handleFlatSubOpLoadUintConstSmall").asmIn("tier1JumpTable", "handlerSubOpLoadUintConstSmall").pure(),
	sub1(SubOpAppendUint, "APPEND_UINT").cost(costExpensive).handler("handleSubOpAppendUint").mutates(),
	sub1(SubOpAppendInt, "APPEND_INT").cost(costExpensive).handler("handleSubOpAppendInt").mutates(),
	sub1(SubOpAppendString, "APPEND_STRING").cost(costExpensive).handler("handleSubOpAppendString").mutates(),
	sub1(SubOpAppendFloat, "APPEND_FLOAT").cost(costExpensive).handler("handleSubOpAppendFloat").mutates(),
	sub1(SubOpAppendBool, "APPEND_BOOL").cost(costExpensive).handler("handleSubOpAppendBool").mutates(),
	sub1(SubOpStarAppendByteFast, "STAR_APPEND_BYTE_FAST").cost(costExpensive).handler("handleSubOpStarAppendByteFast").mutates(),
	sub1(SubOpStarAppendByteSpread, "STAR_APPEND_BYTE_SPREAD").cost(costExpensive).handler("handleSubOpStarAppendByteSpread").mutates(),
	sub1(SubOpIncStructFieldInt, "INC_STRUCT_FIELD_INT").cost(costMedium).handler("handleSubOpIncStructFieldInt").asmIn("tier1JumpTable", "handlerSubOpIncStructFieldInt").mutates(),
	sub1(SubOpDecStructFieldInt, "DEC_STRUCT_FIELD_INT").cost(costMedium).handler("handleSubOpDecStructFieldInt").asmIn("tier1JumpTable", "handlerSubOpDecStructFieldInt").mutates(),
	sub1(SubOpIncStructFieldUint, "INC_STRUCT_FIELD_UINT").cost(costMedium).handler("handleSubOpIncStructFieldUint").asmIn("tier1JumpTable", "handlerSubOpIncStructFieldUint").mutates(),
	sub1(SubOpDecStructFieldUint, "DEC_STRUCT_FIELD_UINT").cost(costMedium).handler("handleSubOpDecStructFieldUint").asmIn("tier1JumpTable", "handlerSubOpDecStructFieldUint").mutates(),
	sub1(SubOpMakeSliceByte, "MAKE_SLICE_BYTE").cost(costVeryHeavy).handler("handleSubOpMakeSliceByte").asmIn("tier1JumpTable", "handlerSubOpMakeSliceByte").pure(),
	sub1(SubOpSliceGetByteDirect, "SLICE_GET_BYTE_DIRECT").cost(costModerate).handler("handleSliceGetByteDirect").asmIn("tier1JumpTable", "handlerSubOpSliceGetByteDirect").pure(),
	sub1(SubOpSliceSetByteDirect, "SLICE_SET_BYTE_DIRECT").cost(costModerate).handler("handleSliceSetByteDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSetByteDirect").mutates(),
	sub1(SubOpLenSliceByteDirect, "LEN_SLICE_BYTE_DIRECT").cost(costCheap).handler("handleSubOpLenSliceByteDirect").asmIn("tier1JumpTable", "handlerSubOpLenSliceByteDirect").pure(),
	sub1(SubOpSliceByteSlice, "SLICE_BYTE_SLICE").cost(costModerate).handler("handleSubOpSliceByteSlice").asmIn("tier1JumpTable", "handlerSubOpSliceByteSlice").pure(),
	sub1(SubOpLtIntJumpFalse, "LT_INT_JUMP_FALSE").cost(costCheap).handler("handleLtIntJumpFalse").asmIn("tier1JumpTable", "handlerLtIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpLeIntJumpFalse, "LE_INT_JUMP_FALSE").cost(costCheap).handler("handleLeIntJumpFalse").asmIn("tier1JumpTable", "handlerLeIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpGtIntJumpFalse, "GT_INT_JUMP_FALSE").cost(costCheap).handler("handleGtIntJumpFalse").asmIn("tier1JumpTable", "handlerGtIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpGeIntJumpFalse, "GE_INT_JUMP_FALSE").cost(costCheap).handler("handleGeIntJumpFalse").asmIn("tier1JumpTable", "handlerGeIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpEqIntJumpFalse, "EQ_INT_JUMP_FALSE").cost(costCheap).handler("handleEqIntJumpFalse").asmIn("tier1JumpTable", "handlerEqIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpNeIntJumpFalse, "NE_INT_JUMP_FALSE").cost(costCheap).handler("handleNeIntJumpFalse").asmIn("tier1JumpTable", "handlerNeIntJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpLeIntConstJumpFalse, "LE_INT_CONST_JUMP_FALSE").cost(costCheap).handler("handleLeIntConstJumpFalse").asmIn("tier1JumpTable", "handlerLeIntConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpLtIntConstJumpFalse, "LT_INT_CONST_JUMP_FALSE").cost(costCheap).handler("handleLtIntConstJumpFalse").asmIn("tier1JumpTable", "handlerLtIntConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpEqIntConstJumpFalse, "EQ_INT_CONST_JUMP_FALSE").cost(costCheap).handler("handleEqIntConstJumpFalse").asmIn("tier1JumpTable", "handlerEqIntConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpEqIntConstJumpTrue, "EQ_INT_CONST_JUMP_TRUE").cost(costCheap).handler("handleEqIntConstJumpTrue").asmIn("tier1JumpTable", "handlerEqIntConstJumpTrue").flags(SpecJump).pure(),
	sub1(SubOpGeIntConstJumpFalse, "GE_INT_CONST_JUMP_FALSE").cost(costCheap).handler("handleGeIntConstJumpFalse").asmIn("tier1JumpTable", "handlerGeIntConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpGtIntConstJumpFalse, "GT_INT_CONST_JUMP_FALSE").cost(costCheap).handler("handleGtIntConstJumpFalse").asmIn("tier1JumpTable", "handlerGtIntConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpCall, "CALL").cost(costExpensive).handler("handleCall").asmIn("tier1JumpTable", "handlerCallInline").pure(),
	sub1(SubOpTailCall, "TAIL_CALL").cost(costExpensive).handler("handleTailCall").asmIn("tier1JumpTable", "handlerTailCallInline").pure(),
	sub1(SubOpCallNative, "CALL_NATIVE").cost(costExpensive).handler("handleCallNative").pure(),
	sub1(SubOpCallBuiltin, "CALL_BUILTIN").cost(costExpensive).handler("handleCallBuiltin").pure(),
	sub1(SubOpCallMethod, "CALL_METHOD").cost(costExpensive).handler("handleCallMethod").asmIn("tier1JumpTable", "handlerCallMethodInline").pure(),
	sub1(SubOpCallIIFE, "CALL_IIFE").cost(costExpensive).handler("handleCallIIFE").pure(),
	sub1(SubOpCallScalar, "CALL_SCALAR").handler("handleCallScalar").asmIn("tier1JumpTable", "handlerCallInlineScalar").pure(),
	sub1(SubOpCallMethodInlineable, "CALL_METHOD_INLINEABLE").cost(costExpensive).handler("handleCallMethodInlineable").pure(),
	sub1(SubOpEqStringConstJumpFalse, "EQ_STRING_CONST_JUMP_FALSE").cost(costModerate).handler("handleEqStringConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpSelect, "SELECT").cost(costExpensive).handler("handleSelect").pure(),
	sub1(SubOpLoadBoolConst, "LOAD_BOOL_CONST").cost(costFree).handler("handleLoadBoolConst").asmIn("tier1JumpTable", "handlerLoadBoolConst").pure(),
	sub1(SubOpResetSharedCell, "RESET_SHARED_CELL").cost(costModerate).handler("handleResetSharedCell").shim("HandleResetSharedCell", "ResetSharedCell").mutates(),
	sub1(SubOpWriteSharedCell, "WRITE_SHARED_CELL").cost(costModerate).handler("handleWriteSharedCell").shim("HandleWriteSharedCell", "WriteSharedCell").mutates(),
	sub1(SubOpSliceOp, "SLICE_OP").cost(costModerate).handler("handleSliceOp").shim("HandleSliceOp", "SliceOp").pure(),
	sub1(SubOpRangeInit, "RANGE_INIT").cost(costModerate).handler("handleRangeInit").shim("HandleRangeInit", "RangeInit").pure(),
	sub1(SubOpRangeNext, "RANGE_NEXT").cost(costModerate).handler("handleRangeNext").shim("HandleRangeNext", "RangeNext").pure(),
	sub1(SubOpGetGlobalWide, "GET_GLOBAL_WIDE").cost(costModerate).handler("handleGetGlobalWide").shim("HandleGetGlobalWide", "GetGlobalWide").pure(),
	sub1(SubOpSetGlobalWide, "SET_GLOBAL_WIDE").cost(costModerate).handler("handleSetGlobalWide").shim("HandleSetGlobalWide", "SetGlobalWide").mutates(),
	sub1(SubOpEqInterfaceNil, "EQ_INTERFACE_NIL").cost(costCheap).handler("handleEqInterfaceNil").shim("HandleEqInterfaceNil", "EqInterfaceNil").pure(),
	sub1(SubOpNeInterfaceNil, "NE_INTERFACE_NIL").cost(costCheap).handler("handleNeInterfaceNil").shim("HandleNeInterfaceNil", "NeInterfaceNil").pure(),
	sub1(SubOpBoxSliceByte, "BOX_SLICE_BYTE").cost(costFree).handler("handleSubOpBoxSliceByte").pure(),
	sub1(SubOpSliceByteToString, "SLICE_BYTE_TO_STRING").cost(costMedium).handler("handleSubOpSliceByteToString").pure(),
	sub1(SubOpEqUintConstJumpFalse, "EQ_UINT_CONST_JUMP_FALSE").cost(costCheap).handler("handleSubOpEqUintConstJumpFalse").
		asmIn("tier1JumpTable", "handlerSubOpEqUintConstJumpFalse").flags(SpecJump).pure(),
	sub1(SubOpSimdDotProductFloat64, "SIMD_DOT_PRODUCT_FLOAT64").cost(costExpensive).handler("handleFlatSubOpSimdDotProductFloat64").pure(),
	sub1(SubOpSimdSumSliceFloat64, "SIMD_SUM_SLICE_FLOAT64").cost(costExpensive).handler("handleFlatSubOpSimdSumSliceFloat64").pure(),
	sub1(SubOpSimdAddSliceFloat64, "SIMD_ADD_SLICE_FLOAT64").cost(costExpensive).handler("handleFlatSubOpSimdAddSliceFloat64").mutates(),
	sub1(SubOpSimdScaleSliceFloat64, "SIMD_SCALE_SLICE_FLOAT64").cost(costExpensive).handler("handleFlatSubOpSimdScaleSliceFloat64").mutates(),
	sub1(SubOpAdoptGeneralToSlicesFloat, "ADOPT_GENERAL_TO_SLICES_FLOAT").cost(costFree).handler("handleFlatSubOpAdoptGeneralToSlicesFloat").pure(),
	sub1(SubOpAdoptGeneralToSlicesInt, "ADOPT_GENERAL_TO_SLICES_INT").cost(costFree).handler("handleSubOpAdoptGeneralToSlicesInt").pure(),
	sub1(SubOpAdoptGeneralToSlicesString, "ADOPT_GENERAL_TO_SLICES_STRING").cost(costFree).handler("handleSubOpAdoptGeneralToSlicesString").pure(),
	sub1(SubOpAdoptGeneralToSlicesBool, "ADOPT_GENERAL_TO_SLICES_BOOL").cost(costFree).handler("handleSubOpAdoptGeneralToSlicesBool").pure(),
	sub1(SubOpAdoptGeneralToSlicesUint, "ADOPT_GENERAL_TO_SLICES_UINT").cost(costFree).handler("handleSubOpAdoptGeneralToSlicesUint").pure(),
	sub1(SubOpAdoptGeneralToSlicesByte, "ADOPT_GENERAL_TO_SLICES_BYTE").cost(costFree).handler("handleSubOpAdoptGeneralToSlicesByte").pure(),
	sub1(SubOpBoxSliceFloat, "BOX_SLICE_FLOAT").cost(costFree).handler("handleSubOpBoxSliceFloat").pure(),
	sub1(SubOpBoxSliceString, "BOX_SLICE_STRING").cost(costFree).handler("handleSubOpBoxSliceString").pure(),
	sub1(SubOpBoxSliceBool, "BOX_SLICE_BOOL").cost(costFree).handler("handleSubOpBoxSliceBool").pure(),
	sub1(SubOpBoxSliceUint, "BOX_SLICE_UINT").cost(costFree).handler("handleSubOpBoxSliceUint").pure(),
	sub1(SubOpMoveSliceInt, "MOVE_SLICE_INT").cost(costFree).handler("handleFlatSubOpMoveSliceInt").asmIn("tier1JumpTable", "handlerSubOpMoveSliceInt").pure(),
	sub1(SubOpMoveSliceFloat, "MOVE_SLICE_FLOAT").cost(costFree).handler("handleFlatSubOpMoveSliceFloat").asmIn("tier1JumpTable", "handlerSubOpMoveSliceFloat").pure(),
	sub1(SubOpMoveSliceString, "MOVE_SLICE_STRING").cost(costFree).handler("handleFlatSubOpMoveSliceString").asmIn("tier1JumpTable", "handlerSubOpMoveSliceString").pure(),
	sub1(SubOpMoveSliceBool, "MOVE_SLICE_BOOL").cost(costFree).handler("handleFlatSubOpMoveSliceBool").asmIn("tier1JumpTable", "handlerSubOpMoveSliceBool").pure(),
	sub1(SubOpMoveSliceUint, "MOVE_SLICE_UINT").cost(costFree).handler("handleFlatSubOpMoveSliceUint").asmIn("tier1JumpTable", "handlerSubOpMoveSliceUint").pure(),
	sub1(SubOpMoveSliceByte, "MOVE_SLICE_BYTE").cost(costFree).handler("handleFlatSubOpMoveSliceByte").asmIn("tier1JumpTable", "handlerSubOpMoveSliceByte").pure(),
	sub1(SubOpAppendSliceIntDirect, "APPEND_SLICE_INT_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceIntDirect").asmIn("tier1JumpTable", "handlerSubOpAppendSliceIntDirect").mutates(),
	sub1(SubOpAppendSliceFloatDirect, "APPEND_SLICE_FLOAT_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceFloatDirect").
		asmIn("tier1JumpTable", "handlerSubOpAppendSliceFloatDirect").mutates(),
	sub1(SubOpAppendSliceStringDirect, "APPEND_SLICE_STRING_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceStringDirect").
		asmIn("tier1JumpTable", "handlerSubOpAppendSliceStringDirect").mutates(),
	sub1(SubOpAppendSliceBoolDirect, "APPEND_SLICE_BOOL_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceBoolDirect").asmIn("tier1JumpTable", "handlerSubOpAppendSliceBoolDirect").mutates(),
	sub1(SubOpAppendSliceUintDirect, "APPEND_SLICE_UINT_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceUintDirect").asmIn("tier1JumpTable", "handlerSubOpAppendSliceUintDirect").mutates(),
	sub1(SubOpAppendSliceByteDirect, "APPEND_SLICE_BYTE_DIRECT").cost(costExpensive).handler("handleSubOpAppendSliceByteDirect").asmIn("tier1JumpTable", "handlerSubOpAppendSliceByteDirect").mutates(),
	sub1(SubOpSliceSliceIntDirect, "SLICE_SLICE_INT_DIRECT").cost(costModerate).handler("handleSubOpSliceSliceIntDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSliceIntDirect").pure(),
	sub1(SubOpSliceSliceFloatDirect, "SLICE_SLICE_FLOAT_DIRECT").cost(costModerate).handler("handleSubOpSliceSliceFloatDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSliceFloatDirect").pure(),
	sub1(SubOpSliceSliceStringDirect, "SLICE_SLICE_STRING_DIRECT").cost(costModerate).handler("handleSubOpSliceSliceStringDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSliceStringDirect").pure(),
	sub1(SubOpSliceSliceBoolDirect, "SLICE_SLICE_BOOL_DIRECT").cost(costModerate).handler("handleSubOpSliceSliceBoolDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSliceBoolDirect").pure(),
	sub1(SubOpSliceSliceUintDirect, "SLICE_SLICE_UINT_DIRECT").cost(costModerate).handler("handleSubOpSliceSliceUintDirect").asmIn("tier1JumpTable", "handlerSubOpSliceSliceUintDirect").pure(),
	sub1(SubOpCopySliceIntDirect, "COPY_SLICE_INT_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceIntDirect").mutates(),
	sub1(SubOpCopySliceFloatDirect, "COPY_SLICE_FLOAT_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceFloatDirect").mutates(),
	sub1(SubOpCopySliceStringDirect, "COPY_SLICE_STRING_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceStringDirect").mutates(),
	sub1(SubOpCopySliceBoolDirect, "COPY_SLICE_BOOL_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceBoolDirect").mutates(),
	sub1(SubOpCopySliceUintDirect, "COPY_SLICE_UINT_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceUintDirect").mutates(),
	sub1(SubOpCopySliceByteDirect, "COPY_SLICE_BYTE_DIRECT").cost(costExpensive).handler("handleSubOpCopySliceByteDirect").mutates(),
	sub1(SubOpAppendUintInPlace, "APPEND_UINT_INPLACE").cost(costExpensive).handler("handleSubOpAppendUintInPlace").mutates(),
	sub1(SubOpAppendByteSpreadInPlace, "APPEND_BYTE_SPREAD_INPLACE").cost(costExpensive).handler("handleSubOpAppendByteSpreadInPlace").mutates(),
	sub1(SubOpGetStructFieldSliceInt, "GET_STRUCT_FIELD_SLICE_INT").cost(costMedium).handler("handleGetStructFieldUnsafeSliceInt").pure(),
	sub1(SubOpGetStructFieldSliceFloat, "GET_STRUCT_FIELD_SLICE_FLOAT").cost(costMedium).handler("handleGetStructFieldUnsafeSliceFloat").pure(),
	sub1(SubOpGetStructFieldSliceUint, "GET_STRUCT_FIELD_SLICE_UINT").cost(costMedium).handler("handleGetStructFieldUnsafeSliceUint").pure(),
	sub1(SubOpGetStructFieldSliceString, "GET_STRUCT_FIELD_SLICE_STRING").cost(costMedium).handler("handleGetStructFieldUnsafeSliceString").pure(),
	sub1(SubOpGetStructFieldSliceBool, "GET_STRUCT_FIELD_SLICE_BOOL").cost(costMedium).handler("handleGetStructFieldUnsafeSliceBool").pure(),
	sub1(SubOpGetStructFieldSliceByte, "GET_STRUCT_FIELD_SLICE_BYTE").cost(costMedium).handler("handleGetStructFieldUnsafeSliceByte").pure(),
	sub1(SubOpSetStructFieldSliceInt, "SET_STRUCT_FIELD_SLICE_INT").cost(costMedium).handler("handleSetStructFieldUnsafeSliceInt").mutates(),
	sub1(SubOpSetStructFieldSliceFloat, "SET_STRUCT_FIELD_SLICE_FLOAT").cost(costMedium).handler("handleSetStructFieldUnsafeSliceFloat").mutates(),
	sub1(SubOpSetStructFieldSliceUint, "SET_STRUCT_FIELD_SLICE_UINT").cost(costMedium).handler("handleSetStructFieldUnsafeSliceUint").mutates(),
	sub1(SubOpSetStructFieldSliceString, "SET_STRUCT_FIELD_SLICE_STRING").cost(costMedium).handler("handleSetStructFieldUnsafeSliceString").mutates(),
	sub1(SubOpSetStructFieldSliceBool, "SET_STRUCT_FIELD_SLICE_BOOL").cost(costMedium).handler("handleSetStructFieldUnsafeSliceBool").mutates(),
	sub1(SubOpSetStructFieldSliceByte, "SET_STRUCT_FIELD_SLICE_BYTE").cost(costMedium).handler("handleSetStructFieldUnsafeSliceByte").mutates(),
	sub1(SubOpCapSliceIntDirect, "CAP_SLICE_INT_DIRECT").cost(costCheap).handler("handleSubOpCapSliceIntDirect").pure(),
	sub1(SubOpCapSliceFloatDirect, "CAP_SLICE_FLOAT_DIRECT").cost(costCheap).handler("handleSubOpCapSliceFloatDirect").pure(),
	sub1(SubOpCapSliceStringDirect, "CAP_SLICE_STRING_DIRECT").cost(costCheap).handler("handleSubOpCapSliceStringDirect").pure(),
	sub1(SubOpCapSliceBoolDirect, "CAP_SLICE_BOOL_DIRECT").cost(costCheap).handler("handleSubOpCapSliceBoolDirect").pure(),
	sub1(SubOpCapSliceUintDirect, "CAP_SLICE_UINT_DIRECT").cost(costCheap).handler("handleSubOpCapSliceUintDirect").pure(),
	sub1(SubOpCapSliceByteDirect, "CAP_SLICE_BYTE_DIRECT").cost(costCheap).handler("handleSubOpCapSliceByteDirect").pure(),
	sub1(SubOpMakeSliceHeap, "MAKE_SLICE_HEAP").cost(costVeryHeavy).handler("handleSubOpMakeSliceHeap").pure(),
	sub1(SubOpTypeSwitchJump, "TYPE_SWITCH_JUMP").cost(costModerate).handler("handleSubOpTypeSwitchJump").flags(SpecJump).pure(),
	sub1(SubOpRoundFloat32, "ROUND_FLOAT32").cost(costCheap).handler("handleFlatSubOpRoundFloat32").pure(),
	sub1(SubOpRoundComplex64, "ROUND_COMPLEX64").cost(costCheap).handler("handleFlatSubOpRoundComplex64").pure(),
	sub1(SubOpEqInterfaceStrict, "EQ_INTERFACE_STRICT").cost(costCheap).handler("handleSubOpEqInterfaceStrict").pure(),
	sub1(SubOpNeInterfaceStrict, "NE_INTERFACE_STRICT").cost(costCheap).handler("handleSubOpNeInterfaceStrict").pure(),
}
