// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerStringIndex sets uints[A] = uint64(strings[B][ints[C]]).
TEXT ·handlerStringIndex(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R4, R4
	ADD  R4, R6, R7
	MOVD (R7), R8
	MOVD 8(R7), R9
	MOVD (R23)(R5<<3), R10
	CMP  $0, R10
	BLT  si_fallback_arm
	CMP  R9, R10
	BGE  si_fallback_arm
	MOVBU (R8)(R10), R11
	MOVD CTX_UINTS_BASE(R19), R12
	MOVD R11, (R12)(R3<<3)
	DISPATCH_NEXT()

si_fallback_arm:
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_TIER2, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerEqString sets ints[A] = (strings[B] == strings[C]) ? 1 : 0.
TEXT ·handlerEqString(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R4, R4
	LSL  $4, R5, R5
	ADD  R4, R6, R7
	ADD  R5, R6, R8
	MOVD 8(R7), R9
	MOVD 8(R8), R10
	CMP  R10, R9
	BNE  eqs_ne_arm
	MOVD (R7), R7
	MOVD (R8), R8
	CMP  R8, R7
	BEQ  eqs_eq_arm
	CBZ  R9, eqs_eq_arm

eqs_loop:
	MOVBU (R7), R11
	MOVBU (R8), R12
	CMP   R12, R11
	BNE   eqs_ne_arm
	ADD   $1, R7, R7
	ADD   $1, R8, R8
	SUB   $1, R9, R9
	CBNZ  R9, eqs_loop

eqs_eq_arm:
	MOVD $1, R11
	B    eqs_done_arm

eqs_ne_arm:
	MOVD ZR, R11

eqs_done_arm:
	MOVD R11, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerNeString sets ints[A] = (strings[B] != strings[C]) ? 1 : 0.
TEXT ·handlerNeString(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R4, R4
	LSL  $4, R5, R5
	ADD  R4, R6, R7
	ADD  R5, R6, R8
	MOVD 8(R7), R9
	MOVD 8(R8), R10
	CMP  R10, R9
	BNE  nes_ne_arm
	MOVD (R7), R7
	MOVD (R8), R8
	CMP  R8, R7
	BEQ  nes_eq_arm
	CBZ  R9, nes_eq_arm

nes_loop:
	MOVBU (R7), R11
	MOVBU (R8), R12
	CMP   R12, R11
	BNE   nes_ne_arm
	ADD   $1, R7, R7
	ADD   $1, R8, R8
	SUB   $1, R9, R9
	CBNZ  R9, nes_loop

nes_eq_arm:
	MOVD ZR, R11
	B    nes_done_arm

nes_ne_arm:
	MOVD $1, R11

nes_done_arm:
	MOVD R11, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerSliceString sets strings[A] = strings[B][low:high].
TEXT ·handlerSliceString(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R4, R4
	ADD  R4, R6, R7
	MOVD (R7), R8
	MOVD 8(R7), R9
	MOVWU (R22)(R20<<2), R0
	ADD   $1, R20, R20
	MOVD ZR, R10
	TBZ  $0, R5, sl_no_low_arm
	LSR  $8, R0, R11
	AND  $0xFF, R11, R11
	MOVD (R23)(R11<<3), R10

sl_no_low_arm:
	MOVD R9, R11
	TBZ  $1, R5, sl_got_high_arm
	LSR  $16, R0, R12
	AND  $0xFF, R12, R12
	MOVD (R23)(R12<<3), R11

sl_got_high_arm:
	CMP  $0, R10
	BLT  sl_bounds_fail_arm
	CMP  R10, R11
	BLT  sl_bounds_fail_arm
	CMP  R9, R11
	BGT  sl_bounds_fail_arm
	ADD  R10, R8, R8
	SUB  R10, R11, R11
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R3, R3
	ADD  R3, R6, R7
	MOVD R8, (R7)
	MOVD R11, 8(R7)
	DISPATCH_NEXT()

sl_bounds_fail_arm:
	SUB  $2, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_TIER2, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerStringIndexToInt sets ints[A] = int64(strings[B][ints[C]]).
TEXT ·handlerStringIndexToInt(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_STRINGS_BASE(R19), R6
	LSL  $4, R4, R4
	ADD  R4, R6, R7
	MOVD (R7), R8
	MOVD 8(R7), R9
	MOVD (R23)(R5<<3), R10
	CMP  $0, R10
	BLT  sit_fallback_arm
	CMP  R9, R10
	BGE  sit_fallback_arm
	MOVBU (R8)(R10), R11
	MOVD R11, (R23)(R3<<3)
	DISPATCH_NEXT()

sit_fallback_arm:
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_TIER2, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerLenStringLtJumpFalse jumps if ints[A] >= len(strings[B]).
TEXT ·handlerLenStringLtJumpFalse(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	AND  $0xFF, R4, R4
	MOVD CTX_STRINGS_BASE(R19), R5
	LSL  $4, R4, R4
	ADD  R4, R5, R6
	MOVD 8(R6), R7
	MOVD (R23)(R3<<3), R8
	CMP  R7, R8
	BLT  lsj_taken_arm

	MOVWU (R22)(R20<<2), R0
	ADD   $1, R20, R20
	LSR   $8, R0, R3
	AND   $0xFFFF, R3, R3
	LSL   $48, R3, R3
	ASR   $48, R3, R3
	ADD   R3, R20, R20
	MOVD CTX_POLL_BUDGET(R19), R0
	SUB  $1, R0, R0
	MOVD R0, CTX_POLL_BUDGET(R19)
	CMP  $0, R0
	BGT  poll_ok
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_POLL, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET  
poll_ok:
	B     lsj_dispatch_arm

lsj_taken_arm:
	ADD  $1, R20, R20

lsj_dispatch_arm:
	DISPATCH_NEXT()
