// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpLenString sets ints[B] = len(strings[C]) for the tier-1 string-length sub-op.
TEXT ·handlerSubOpLenString(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_STRINGS_BASE(R19), R5
	LSL  $4, R4, R4
	ADD  R4, R5, R6
	MOVD 8(R6), R7
	MOVD R7, (R23)(R3<<3)
	DISPATCH_NEXT()
