// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpStrconvFormatBool sets strings[B] = bools[C] ? "true" : "false" by stamping a pre-allocated header.
TEXT ·handlerSubOpStrconvFormatBool(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_BOOLS_BASE(R15), DI
	MOVBLZX (DI)(CX*1), AX
	LEAQ    ·boolStringFalse(SB), DI
	LEAQ    ·boolStringTrue(SB), SI
	TESTB   AL, AL
	CMOVQNE SI, DI
	MOVQ    0(DI), AX
	MOVQ    8(DI), DX
	MOVQ    CTX_STRINGS_BASE(R15), SI
	SHLQ    $4, BX
	MOVQ    AX, 0(SI)(BX*1)
	MOVQ    DX, 8(SI)(BX*1)
	DISPATCH_NEXT()

// handlerSubOpStrconvItoa sets strings[B] = strconv.Itoa(int(ints[C])) via asmCallStrconvItoa.
TEXT ·handlerSubOpStrconvItoa(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $32
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	CALL    ·asmCallStrconvItoa(SB)
	MOVQ    24(SP), R15
	ADJSP   $-32
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()

// handlerSubOpStrconvFormatInt sets strings[B] = strconv.FormatInt(ints[C], int(ints[ext.A])) via asmCallStrconvFormatInt.
TEXT ·handlerSubOpStrconvFormatInt(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVL    (R12)(R14*4), AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	INCQ    R14
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $40
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	MOVQ    AX, 24(SP)
	CALL    ·asmCallStrconvFormatInt(SB)
	MOVQ    32(SP), R15
	ADJSP   $-40
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()
