// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerGetUpvalueScalar sets bank(C)[A] = upvalues[B].scalarField(C) for direct scalar cells; other shapes fall back to handlerPathBShimGetUpvalue.
TEXT ·handlerGetUpvalueScalar(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    CTX_CURRENT_FRAME(R15), SI
	CMPQ    BX, (CF_UPVALUES_PTR+8)(SI)
	JAE     gu_shim
	MOVQ    CF_UPVALUES_PTR(SI), DI
	MOVQ    (DI)(BX*8), DI
	TESTQ   DI, DI
	JZ      gu_shim
	CMPB    CELL_IS_INDIRECT(DI), $0
	JNE     gu_shim

	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVBLZX CL, CX
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX

	CMPQ    CX, $REGKIND_INT
	JNE     gu_not_int
	MOVQ    CELL_INT_VALUE(DI), CX
	MOVQ    CX, (R8)(AX*8)
	JMP     gu_done
gu_not_int:
	CMPQ    CX, $REGKIND_FLOAT
	JNE     gu_not_float
	MOVQ    CELL_FLOAT_VALUE(DI), CX
	MOVQ    CX, (R9)(AX*8)
	JMP     gu_done
gu_not_float:
	CMPQ    CX, $REGKIND_UINT
	JNE     gu_not_uint
	MOVQ    CELL_UINT_VALUE(DI), CX
	MOVQ    CTX_UINTS_BASE(R15), SI
	MOVQ    CX, (SI)(AX*8)
	JMP     gu_done
gu_not_uint:
	CMPQ    CX, $REGKIND_BOOL
	JNE     gu_shim
	MOVBLZX CELL_BOOL_VALUE(DI), CX
	MOVQ    CTX_BOOLS_BASE(R15), SI
	MOVB    CL, (SI)(AX*1)
gu_done:
	DISPATCH_NEXT()
gu_shim:
	JMP     ·handlerPathBShimGetUpvalue(SB)
