// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// initJumpTable fills the 256-entry dispatch table; tier-1 opcodes get their specific handlers, others get pathBFallback.
TEXT ·initJumpTable(SB), NOSPLIT, $0-8
	MOVQ    table+0(FP), DI

	LEAQ    ·pathBFallback(SB), AX
	MOVQ    $256, CX

initjt_fill:
	MOVQ    AX, (DI)
	ADDQ    $8, DI
	DECQ    CX
	JNZ     initjt_fill

	MOVQ    table+0(FP), DI

	LEAQ    ·handlerLoadIntConst(SB), AX
	MOVQ    AX, 16(DI)

	LEAQ    ·handlerLoadFloatConst(SB), AX
	MOVQ    AX, 24(DI)

	LEAQ    ·handlerAddInt(SB), AX
	MOVQ    AX, 32(DI)

	LEAQ    ·handlerSubInt(SB), AX
	MOVQ    AX, 40(DI)

	LEAQ    ·handlerMulInt(SB), AX
	MOVQ    AX, 48(DI)

	LEAQ    ·handlerDivInt(SB), AX
	MOVQ    AX, 56(DI)

	LEAQ    ·handlerRemInt(SB), AX
	MOVQ    AX, 64(DI)

	LEAQ    ·handlerBitAnd(SB), AX
	MOVQ    AX, 72(DI)

	LEAQ    ·handlerBitOr(SB), AX
	MOVQ    AX, 80(DI)

	LEAQ    ·handlerBitXor(SB), AX
	MOVQ    AX, 88(DI)

	LEAQ    ·handlerBitAndNot(SB), AX
	MOVQ    AX, 96(DI)

	LEAQ    ·handlerShiftLeft(SB), AX
	MOVQ    AX, 104(DI)

	LEAQ    ·handlerShiftRight(SB), AX
	MOVQ    AX, 112(DI)

	LEAQ    ·handlerAddFloat(SB), AX
	MOVQ    AX, 120(DI)

	LEAQ    ·handlerSubFloat(SB), AX
	MOVQ    AX, 128(DI)

	LEAQ    ·handlerMulFloat(SB), AX
	MOVQ    AX, 136(DI)

	LEAQ    ·handlerDivFloat(SB), AX
	MOVQ    AX, 144(DI)

	LEAQ    ·handlerEqInt(SB), AX
	MOVQ    AX, 152(DI)

	LEAQ    ·handlerNeInt(SB), AX
	MOVQ    AX, 160(DI)

	LEAQ    ·handlerLtInt(SB), AX
	MOVQ    AX, 168(DI)

	LEAQ    ·handlerLeInt(SB), AX
	MOVQ    AX, 176(DI)

	LEAQ    ·handlerGtInt(SB), AX
	MOVQ    AX, 184(DI)

	LEAQ    ·handlerGeInt(SB), AX
	MOVQ    AX, 192(DI)

	LEAQ    ·handlerEqFloat(SB), AX
	MOVQ    AX, 200(DI)

	LEAQ    ·handlerNeFloat(SB), AX
	MOVQ    AX, 208(DI)

	LEAQ    ·handlerLtFloat(SB), AX
	MOVQ    AX, 216(DI)

	LEAQ    ·handlerLeFloat(SB), AX
	MOVQ    AX, 224(DI)

	LEAQ    ·handlerGtFloat(SB), AX
	MOVQ    AX, 232(DI)

	LEAQ    ·handlerGeFloat(SB), AX
	MOVQ    AX, 240(DI)

	LEAQ    ·handlerJumpIfTrue(SB), AX
	MOVQ    AX, 248(DI)

	LEAQ    ·handlerJumpIfFalse(SB), AX
	MOVQ    AX, 256(DI)

	LEAQ    ·handlerSubIntConst(SB), AX
	MOVQ    AX, 264(DI)

	LEAQ    ·handlerAddIntConst(SB), AX
	MOVQ    AX, 272(DI)

	LEAQ    ·handlerMulIntConst(SB), AX
	MOVQ    AX, 280(DI)

	LEAQ    ·handlerAddIntJump(SB), AX
	MOVQ    AX, 288(DI)

	LEAQ    ·handlerStringIndex(SB), AX
	MOVQ    AX, 296(DI)

	LEAQ    ·handlerEqString(SB), AX
	MOVQ    AX, 304(DI)

	LEAQ    ·handlerNeString(SB), AX
	MOVQ    AX, 312(DI)

	LEAQ    ·handlerSliceString(SB), AX
	MOVQ    AX, 320(DI)

	LEAQ    ·handlerStringIndexToInt(SB), AX
	MOVQ    AX, 328(DI)

	LEAQ    ·handlerMoveGeneral(SB), AX
	MOVQ    AX, 336(DI)

	LEAQ    ·handlerLoadStringConst(SB), AX
	MOVQ    AX, 344(DI)

	LEAQ    ·handlerLoadUintConst(SB), AX
	MOVQ    AX, 360(DI)

	LEAQ    ·handlerAddUint(SB), AX
	MOVQ    AX, 376(DI)

	LEAQ    ·handlerSubUint(SB), AX
	MOVQ    AX, 384(DI)

	LEAQ    ·handlerMulUint(SB), AX
	MOVQ    AX, 392(DI)

	LEAQ    ·handlerDivUint(SB), AX
	MOVQ    AX, 400(DI)

	LEAQ    ·handlerRemUint(SB), AX
	MOVQ    AX, 408(DI)

	LEAQ    ·handlerBitAndUint(SB), AX
	MOVQ    AX, 416(DI)

	LEAQ    ·handlerBitOrUint(SB), AX
	MOVQ    AX, 424(DI)

	LEAQ    ·handlerBitXorUint(SB), AX
	MOVQ    AX, 432(DI)

	LEAQ    ·handlerBitAndNotUint(SB), AX
	MOVQ    AX, 440(DI)

	LEAQ    ·handlerShiftLeftUint(SB), AX
	MOVQ    AX, 448(DI)

	LEAQ    ·handlerShiftRightUint(SB), AX
	MOVQ    AX, 456(DI)

	LEAQ    ·handlerEqUint(SB), AX
	MOVQ    AX, 464(DI)

	LEAQ    ·handlerNeUint(SB), AX
	MOVQ    AX, 472(DI)

	LEAQ    ·handlerLtUint(SB), AX
	MOVQ    AX, 480(DI)

	LEAQ    ·handlerLeUint(SB), AX
	MOVQ    AX, 488(DI)

	LEAQ    ·handlerGtUint(SB), AX
	MOVQ    AX, 496(DI)

	LEAQ    ·handlerGeUint(SB), AX
	MOVQ    AX, 504(DI)

	LEAQ    ·handlerEqGeneral(SB), AX
	MOVQ    AX, 616(DI)

	LEAQ    ·handlerTruncateNarrow(SB), AX
	MOVQ    AX, 704(DI)

	LEAQ    ·handlerTestNilJumpTrue(SB), AX
	MOVQ    AX, 728(DI)

	LEAQ    ·handlerTestNilJumpFalse(SB), AX
	MOVQ    AX, 736(DI)

	LEAQ    ·handlerGetUpvalueScalar(SB), AX
	MOVQ    AX, 752(DI)

	LEAQ    ·handlerRangeNextSliceByte(SB), AX
	MOVQ    AX, 952(DI)

	LEAQ    ·handlerSliceGetIntDirect(SB), AX
	MOVQ    AX, 1376(DI)

	LEAQ    ·handlerSliceSetIntDirect(SB), AX
	MOVQ    AX, 1384(DI)

	LEAQ    ·handlerGetStructFieldIntT0(SB), AX
	MOVQ    AX, 1400(DI)

	LEAQ    ·handlerSetStructFieldIntT0(SB), AX
	MOVQ    AX, 1408(DI)

	LEAQ    ·handlerGetStructFieldUintT0(SB), AX
	MOVQ    AX, 1416(DI)

	LEAQ    ·handlerSetStructFieldUintT0(SB), AX
	MOVQ    AX, 1424(DI)

	LEAQ    ·handlerGetStructFieldFloatT0(SB), AX
	MOVQ    AX, 1432(DI)

	LEAQ    ·handlerSetStructFieldFloatT0(SB), AX
	MOVQ    AX, 1440(DI)

	LEAQ    ·handlerGetStructFieldBoolT0(SB), AX
	MOVQ    AX, 1448(DI)

	LEAQ    ·handlerSetStructFieldBoolT0(SB), AX
	MOVQ    AX, 1456(DI)

	LEAQ    ·handlerGetStructFieldGeneralT0(SB), AX
	MOVQ    AX, 1464(DI)

	LEAQ    ·handlerSetStructFieldGeneralT0(SB), AX
	MOVQ    AX, 1472(DI)

	LEAQ    ·handlerSliceIndexStructFieldInt(SB), AX
	MOVQ    AX, 1488(DI)

	LEAQ    ·handlerSliceIndexStructFieldFloat(SB), AX
	MOVQ    AX, 1504(DI)

	LEAQ    ·handlerGetStructFieldRawPointerT0(SB), AX
	MOVQ    AX, 1584(DI)

	LEAQ    ·handlerSliceGetIntDirectUnchecked(SB), AX
	MOVQ    AX, 1592(DI)

	LEAQ    ·handlerSliceSetIntDirectUnchecked(SB), AX
	MOVQ    AX, 1600(DI)

	LEAQ    ·handlerDerefSliceGetInt(SB), AX
	MOVQ    AX, 1680(DI)

	LEAQ    ·handlerDerefSliceSetInt(SB), AX
	MOVQ    AX, 1688(DI)

	LEAQ    ·handlerGetStructFieldSliceLen(SB), AX
	MOVQ    AX, 1696(DI)

	LEAQ    ·handlerGetStructFieldSliceIndexScalar(SB), AX
	MOVQ    AX, 1704(DI)

	LEAQ    ·handlerPathBShimLoadGeneralConst(SB), AX
	MOVQ    AX, 352(DI)

	LEAQ    ·handlerPathBShimLoadComplexConst(SB), AX
	MOVQ    AX, 368(DI)

	LEAQ    ·handlerPathBShimAddComplex(SB), AX
	MOVQ    AX, 512(DI)

	LEAQ    ·handlerPathBShimSubComplex(SB), AX
	MOVQ    AX, 520(DI)

	LEAQ    ·handlerPathBShimMulComplex(SB), AX
	MOVQ    AX, 528(DI)

	LEAQ    ·handlerPathBShimDivComplex(SB), AX
	MOVQ    AX, 536(DI)

	LEAQ    ·handlerPathBShimEqComplex(SB), AX
	MOVQ    AX, 544(DI)

	LEAQ    ·handlerPathBShimNeComplex(SB), AX
	MOVQ    AX, 552(DI)

	LEAQ    ·handlerPathBShimBuildComplex(SB), AX
	MOVQ    AX, 560(DI)

	LEAQ    ·handlerPathBShimConcatString(SB), AX
	MOVQ    AX, 568(DI)

	LEAQ    ·handlerPathBShimConcatRuneString(SB), AX
	MOVQ    AX, 576(DI)

	LEAQ    ·handlerPathBShimNeGeneral(SB), AX
	MOVQ    AX, 624(DI)

	LEAQ    ·handlerPathBShimLtGeneral(SB), AX
	MOVQ    AX, 632(DI)

	LEAQ    ·handlerPathBShimLeGeneral(SB), AX
	MOVQ    AX, 640(DI)

	LEAQ    ·handlerPathBShimGtGeneral(SB), AX
	MOVQ    AX, 648(DI)

	LEAQ    ·handlerPathBShimGeGeneral(SB), AX
	MOVQ    AX, 656(DI)

	LEAQ    ·handlerPathBShimPackInterface(SB), AX
	MOVQ    AX, 712(DI)

	LEAQ    ·handlerPathBShimUnpackInterface(SB), AX
	MOVQ    AX, 720(DI)

	LEAQ    ·handlerPathBShimMakeClosure(SB), AX
	MOVQ    AX, 744(DI)

	LEAQ    ·handlerPathBShimSetUpvalue(SB), AX
	MOVQ    AX, 760(DI)

	LEAQ    ·handlerPathBShimMakeSlice(SB), AX
	MOVQ    AX, 784(DI)

	LEAQ    ·handlerPathBShimIndex(SB), AX
	MOVQ    AX, 792(DI)

	LEAQ    ·handlerPathBShimIndexSet(SB), AX
	MOVQ    AX, 800(DI)

	LEAQ    ·handlerPathBShimMapSet(SB), AX
	MOVQ    AX, 816(DI)

	LEAQ    ·handlerPathBShimMapIndexOk(SB), AX
	MOVQ    AX, 824(DI)

	LEAQ    ·handlerPathBShimAppendSpread(SB), AX
	MOVQ    AX, 840(DI)

	LEAQ    ·handlerPathBShimCopy(SB), AX
	MOVQ    AX, 856(DI)

	LEAQ    ·handlerPathBShimSliceGetInt(SB), AX
	MOVQ    AX, 864(DI)

	LEAQ    ·handlerPathBShimSliceSetInt(SB), AX
	MOVQ    AX, 872(DI)

	LEAQ    ·handlerPathBShimSliceGetFloat(SB), AX
	MOVQ    AX, 880(DI)

	LEAQ    ·handlerPathBShimSliceSetFloat(SB), AX
	MOVQ    AX, 888(DI)

	LEAQ    ·handlerPathBShimSliceGetString(SB), AX
	MOVQ    AX, 896(DI)

	LEAQ    ·handlerPathBShimSliceSetString(SB), AX
	MOVQ    AX, 904(DI)

	LEAQ    ·handlerPathBShimSliceGetBool(SB), AX
	MOVQ    AX, 912(DI)

	LEAQ    ·handlerPathBShimSliceSetBool(SB), AX
	MOVQ    AX, 920(DI)

	LEAQ    ·handlerPathBShimSliceGetUint(SB), AX
	MOVQ    AX, 928(DI)

	LEAQ    ·handlerPathBShimSliceSetUint(SB), AX
	MOVQ    AX, 936(DI)

	LEAQ    ·handlerPathBShimMapGetIntInt(SB), AX
	MOVQ    AX, 960(DI)

	LEAQ    ·handlerPathBShimMapSetIntInt(SB), AX
	MOVQ    AX, 968(DI)

	LEAQ    ·handlerPathBShimMapGetStringInt(SB), AX
	MOVQ    AX, 976(DI)

	LEAQ    ·handlerPathBShimMapSetStringInt(SB), AX
	MOVQ    AX, 984(DI)

	LEAQ    ·handlerPathBShimMapGetStringString(SB), AX
	MOVQ    AX, 992(DI)

	LEAQ    ·handlerPathBShimMapSetStringString(SB), AX
	MOVQ    AX, 1000(DI)

	LEAQ    ·handlerPathBShimMapGetIntString(SB), AX
	MOVQ    AX, 1008(DI)

	LEAQ    ·handlerPathBShimMapSetIntString(SB), AX
	MOVQ    AX, 1016(DI)

	LEAQ    ·handlerPathBShimMapIndexOkIntInt(SB), AX
	MOVQ    AX, 1024(DI)

	LEAQ    ·handlerPathBShimMapIndexOkStringInt(SB), AX
	MOVQ    AX, 1032(DI)

	LEAQ    ·handlerPathBShimMapIndexOkStringString(SB), AX
	MOVQ    AX, 1040(DI)

	LEAQ    ·handlerPathBShimMapIndexOkIntString(SB), AX
	MOVQ    AX, 1048(DI)

	LEAQ    ·handlerPathBShimMapGetIntGeneral(SB), AX
	MOVQ    AX, 1056(DI)

	LEAQ    ·handlerPathBShimMapIndexOkIntGeneral(SB), AX
	MOVQ    AX, 1064(DI)

	LEAQ    ·handlerPathBShimMapGetStringGeneral(SB), AX
	MOVQ    AX, 1072(DI)

	LEAQ    ·handlerPathBShimMapIndexOkStringGeneral(SB), AX
	MOVQ    AX, 1080(DI)

	LEAQ    ·handlerPathBShimMapSetStringGeneral(SB), AX
	MOVQ    AX, 1088(DI)

	LEAQ    ·handlerPathBShimMapAddIntInt(SB), AX
	MOVQ    AX, 1096(DI)

	LEAQ    ·handlerPathBShimMapAddStringInt(SB), AX
	MOVQ    AX, 1104(DI)

	LEAQ    ·handlerPathBShimBindMethod(SB), AX
	MOVQ    AX, 1144(DI)

	LEAQ    ·handlerPathBShimAddr(SB), AX
	MOVQ    AX, 1160(DI)

	LEAQ    ·handlerPathBShimDeref(SB), AX
	MOVQ    AX, 1168(DI)

	LEAQ    ·handlerPathBShimAllocIndirect(SB), AX
	MOVQ    AX, 1176(DI)

	LEAQ    ·handlerPathBShimTypeAssert(SB), AX
	MOVQ    AX, 1184(DI)

	LEAQ    ·handlerPathBShimConvert(SB), AX
	MOVQ    AX, 1192(DI)

	LEAQ    ·handlerPathBShimGetGlobal(SB), AX
	MOVQ    AX, 1200(DI)

	LEAQ    ·handlerPathBShimSetGlobal(SB), AX
	MOVQ    AX, 1208(DI)

	LEAQ    ·handlerPathBShimUnsafeString(SB), AX
	MOVQ    AX, 1216(DI)

	LEAQ    ·handlerPathBShimUnsafeSlice(SB), AX
	MOVQ    AX, 1224(DI)

	LEAQ    ·handlerPathBShimUnsafeAdd(SB), AX
	MOVQ    AX, 1232(DI)

	LEAQ    ·handlerPathBShimStrContainsRune(SB), AX
	MOVQ    AX, 1240(DI)

	LEAQ    ·handlerPathBShimStrContains(SB), AX
	MOVQ    AX, 1248(DI)

	LEAQ    ·handlerPathBShimStrHasPrefix(SB), AX
	MOVQ    AX, 1256(DI)

	LEAQ    ·handlerPathBShimStrHasSuffix(SB), AX
	MOVQ    AX, 1264(DI)

	LEAQ    ·handlerPathBShimStrEqualFold(SB), AX
	MOVQ    AX, 1272(DI)

	LEAQ    ·handlerPathBShimStrIndex(SB), AX
	MOVQ    AX, 1280(DI)

	LEAQ    ·handlerPathBShimStrCount(SB), AX
	MOVQ    AX, 1288(DI)

	LEAQ    ·handlerPathBShimStrTrimPrefix(SB), AX
	MOVQ    AX, 1296(DI)

	LEAQ    ·handlerPathBShimStrTrimSuffix(SB), AX
	MOVQ    AX, 1304(DI)

	LEAQ    ·handlerPathBShimStrTrim(SB), AX
	MOVQ    AX, 1312(DI)

	LEAQ    ·handlerPathBShimStrIndexRune(SB), AX
	MOVQ    AX, 1320(DI)

	LEAQ    ·handlerPathBShimStrRepeat(SB), AX
	MOVQ    AX, 1328(DI)

	LEAQ    ·handlerPathBShimStrLastIndex(SB), AX
	MOVQ    AX, 1336(DI)

	LEAQ    ·handlerPathBShimStrJoin(SB), AX
	MOVQ    AX, 1344(DI)

	LEAQ    ·handlerPathBShimStrSplit(SB), AX
	MOVQ    AX, 1352(DI)

	LEAQ    ·handlerPathBShimStrReplaceAll(SB), AX
	MOVQ    AX, 1360(DI)

	LEAQ    ·handlerPathBShimMathPow(SB), AX
	MOVQ    AX, 1368(DI)

	LEAQ    ·handlerPathBShimCopyStructFieldGeneralT0(SB), AX
	MOVQ    AX, 1480(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseIntInt(SB), AX
	MOVQ    AX, 1528(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseStringInt(SB), AX
	MOVQ    AX, 1536(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseStringString(SB), AX
	MOVQ    AX, 1544(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseIntString(SB), AX
	MOVQ    AX, 1552(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseIntGeneral(SB), AX
	MOVQ    AX, 1560(DI)

	LEAQ    ·handlerPathBShimMapIndexOkJumpIfFalseStringGeneral(SB), AX
	MOVQ    AX, 1568(DI)

	LEAQ    ·handlerPathBShimSwapStructFieldsGeneralT0(SB), AX
	MOVQ    AX, 1576(DI)

	LEAQ    ·handlerPathBShimMapSetIntGeneral(SB), AX
	MOVQ    AX, 1656(DI)

	LEAQ    ·handlerPathBShimGetStructFieldIndexGeneral(SB), AX
	MOVQ    AX, 1664(DI)

	LEAQ    ·handlerPathBShimSetStructFieldIndexGeneral(SB), AX
	MOVQ    AX, 1672(DI)

	RET     

// initJumpTableSSE41 patches dispatch entries for ROUNDSD-based handlers (Floor, Ceil, Trunc); called only when the CPU supports SSE4.1.
TEXT ·initJumpTableSSE41(SB), NOSPLIT, $0-8
	MOVQ    table+0(FP), DI




	RET     

// initSubOpJumpTables installs .abi0 addresses of tier-1+ ASM handlers into the sub-op jump tables, bypassing the ABIInternal wrapper that adds a per-dispatch frame.
TEXT ·initSubOpJumpTables(SB), NOSPLIT, $0-0
	LEAQ    ·handlerSubOpMathSin(SB), AX
	MOVQ    AX, ·tier1JumpTable+8(SB)

	LEAQ    ·handlerSubOpMathCos(SB), AX
	MOVQ    AX, ·tier1JumpTable+16(SB)

	LEAQ    ·handlerSubOpMathExp(SB), AX
	MOVQ    AX, ·tier1JumpTable+24(SB)

	LEAQ    ·handlerSubOpMathTan(SB), AX
	MOVQ    AX, ·tier1JumpTable+32(SB)

	LEAQ    ·handlerSubOpMathMod(SB), AX
	MOVQ    AX, ·tier1JumpTable+40(SB)

	LEAQ    ·handlerSubOpStrconvFormatBool(SB), AX
	MOVQ    AX, ·tier1JumpTable+48(SB)

	LEAQ    ·handlerSubOpStrconvFormatInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+56(SB)

	LEAQ    ·handlerSubOpStrconvItoa(SB), AX
	MOVQ    AX, ·tier1JumpTable+64(SB)

	LEAQ    ·handlerSubOpRealComplex(SB), AX
	MOVQ    AX, ·tier1JumpTable+72(SB)

	LEAQ    ·handlerSubOpImagComplex(SB), AX
	MOVQ    AX, ·tier1JumpTable+80(SB)

	LEAQ    ·handlerSubOpBytesToString(SB), AX
	MOVQ    AX, ·tier1JumpTable+88(SB)

	LEAQ    ·handlerSubOpCap(SB), AX
	MOVQ    AX, ·tier1JumpTable+104(SB)

	LEAQ    ·handlerSubOpNegComplex(SB), AX
	MOVQ    AX, ·tier1JumpTable+112(SB)

	LEAQ    ·handlerSubOpMoveComplex(SB), AX
	MOVQ    AX, ·tier1JumpTable+120(SB)

	LEAQ    ·handlerSubOpMakeSliceInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+128(SB)

	LEAQ    ·handlerSubOpLenSliceIntDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+136(SB)

	LEAQ    ·handlerSubOpMakeSliceFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+144(SB)

	LEAQ    ·handlerSubOpSliceGetFloatDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+152(SB)

	LEAQ    ·handlerSubOpSliceSetFloatDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+160(SB)

	LEAQ    ·handlerSubOpLenSliceFloatDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+168(SB)

	LEAQ    ·handlerSubOpMakeSliceString(SB), AX
	MOVQ    AX, ·tier1JumpTable+176(SB)

	LEAQ    ·handlerSubOpSliceGetStringDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+184(SB)

	LEAQ    ·handlerSubOpSliceSetStringDirectExit(SB), AX
	MOVQ    AX, ·tier1JumpTable+192(SB)

	LEAQ    ·handlerSubOpLenSliceStringDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+200(SB)

	LEAQ    ·handlerSubOpMakeSliceBool(SB), AX
	MOVQ    AX, ·tier1JumpTable+208(SB)

	LEAQ    ·handlerSubOpSliceGetBoolDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+216(SB)

	LEAQ    ·handlerSubOpSliceSetBoolDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+224(SB)

	LEAQ    ·handlerSubOpLenSliceBoolDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+232(SB)

	LEAQ    ·handlerSubOpMakeSliceUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+240(SB)

	LEAQ    ·handlerSubOpSliceGetUintDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+248(SB)

	LEAQ    ·handlerSubOpSliceSetUintDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+256(SB)

	LEAQ    ·handlerSubOpLenSliceUintDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+264(SB)

	LEAQ    ·handlerSubOpBoxSliceInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+272(SB)

	LEAQ    ·handlerSubOpMoveInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+280(SB)

	LEAQ    ·handlerSubOpMoveFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+288(SB)

	LEAQ    ·handlerSubOpMoveString(SB), AX
	MOVQ    AX, ·tier1JumpTable+296(SB)

	LEAQ    ·handlerSubOpMoveBool(SB), AX
	MOVQ    AX, ·tier1JumpTable+304(SB)

	LEAQ    ·handlerSubOpMoveUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+312(SB)

	LEAQ    ·handlerSubOpNegInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+368(SB)

	LEAQ    ·handlerSubOpNegFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+376(SB)

	LEAQ    ·handlerSubOpBitNot(SB), AX
	MOVQ    AX, ·tier1JumpTable+384(SB)

	LEAQ    ·handlerSubOpIntToFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+400(SB)

	LEAQ    ·handlerSubOpFloatToInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+408(SB)

	LEAQ    ·handlerSubOpUintToFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+456(SB)

	LEAQ    ·handlerSubOpFloatToUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+464(SB)

	LEAQ    ·handlerSubOpMathSqrt(SB), AX
	MOVQ    AX, ·tier1JumpTable+472(SB)

	LEAQ    ·handlerSubOpMathAbs(SB), AX
	MOVQ    AX, ·tier1JumpTable+480(SB)

	LEAQ    ·handlerSubOpMathFloor(SB), AX
	MOVQ    AX, ·tier1JumpTable+488(SB)

	LEAQ    ·handlerSubOpMathCeil(SB), AX
	MOVQ    AX, ·tier1JumpTable+496(SB)

	LEAQ    ·handlerSubOpMathTrunc(SB), AX
	MOVQ    AX, ·tier1JumpTable+504(SB)

	LEAQ    ·handlerSubOpMathRound(SB), AX
	MOVQ    AX, ·tier1JumpTable+512(SB)

	LEAQ    ·handlerSubOpLenString(SB), AX
	MOVQ    AX, ·tier1JumpTable+520(SB)

	LEAQ    ·handlerJump(SB), AX
	MOVQ    AX, ·tier1JumpTable+592(SB)

	LEAQ    ·handlerLoadIntConstSmall(SB), AX
	MOVQ    AX, ·tier1JumpTable+600(SB)

	LEAQ    ·handlerLoadBool(SB), AX
	MOVQ    AX, ·tier1JumpTable+608(SB)

	LEAQ    ·handlerIncIntJumpLt(SB), AX
	MOVQ    AX, ·tier1JumpTable+616(SB)

	LEAQ    ·handlerLenStringLtJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+624(SB)

	LEAQ    ·handlerSubOpAddUintConst(SB), AX
	MOVQ    AX, ·tier1JumpTable+768(SB)

	LEAQ    ·handlerSubOpSubUintConst(SB), AX
	MOVQ    AX, ·tier1JumpTable+776(SB)

	LEAQ    ·handlerSubOpBitAndUintConst(SB), AX
	MOVQ    AX, ·tier1JumpTable+784(SB)

	LEAQ    ·handlerSubOpLoadUintConstSmall(SB), AX
	MOVQ    AX, ·tier1JumpTable+792(SB)

	LEAQ    ·handlerSubOpIncStructFieldInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+856(SB)

	LEAQ    ·handlerSubOpDecStructFieldInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+864(SB)

	LEAQ    ·handlerSubOpIncStructFieldUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+872(SB)

	LEAQ    ·handlerSubOpDecStructFieldUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+880(SB)

	LEAQ    ·handlerSubOpMakeSliceByte(SB), AX
	MOVQ    AX, ·tier1JumpTable+888(SB)

	LEAQ    ·handlerSubOpSliceGetByteDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+896(SB)

	LEAQ    ·handlerSubOpSliceSetByteDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+904(SB)

	LEAQ    ·handlerSubOpLenSliceByteDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+912(SB)

	LEAQ    ·handlerSubOpSliceByteSlice(SB), AX
	MOVQ    AX, ·tier1JumpTable+920(SB)

	LEAQ    ·handlerLtIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+928(SB)

	LEAQ    ·handlerLeIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+936(SB)

	LEAQ    ·handlerGtIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+944(SB)

	LEAQ    ·handlerGeIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+952(SB)

	LEAQ    ·handlerEqIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+960(SB)

	LEAQ    ·handlerNeIntJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+968(SB)

	LEAQ    ·handlerLeIntConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+976(SB)

	LEAQ    ·handlerLtIntConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+984(SB)

	LEAQ    ·handlerEqIntConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+992(SB)

	LEAQ    ·handlerEqIntConstJumpTrue(SB), AX
	MOVQ    AX, ·tier1JumpTable+1000(SB)

	LEAQ    ·handlerGeIntConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+1008(SB)

	LEAQ    ·handlerGtIntConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+1016(SB)

	LEAQ    ·handlerCallInline(SB), AX
	MOVQ    AX, ·tier1JumpTable+1024(SB)

	LEAQ    ·handlerTailCallInline(SB), AX
	MOVQ    AX, ·tier1JumpTable+1032(SB)

	LEAQ    ·handlerCallMethodInline(SB), AX
	MOVQ    AX, ·tier1JumpTable+1056(SB)

	LEAQ    ·handlerCallInlineScalar(SB), AX
	MOVQ    AX, ·tier1JumpTable+1072(SB)

	LEAQ    ·handlerLoadBoolConst(SB), AX
	MOVQ    AX, ·tier1JumpTable+1104(SB)

	LEAQ    ·handlerSubOpEqUintConstJumpFalse(SB), AX
	MOVQ    AX, ·tier1JumpTable+1200(SB)

	LEAQ    ·handlerSubOpMoveSliceInt(SB), AX
	MOVQ    AX, ·tier1JumpTable+1320(SB)

	LEAQ    ·handlerSubOpMoveSliceFloat(SB), AX
	MOVQ    AX, ·tier1JumpTable+1328(SB)

	LEAQ    ·handlerSubOpMoveSliceString(SB), AX
	MOVQ    AX, ·tier1JumpTable+1336(SB)

	LEAQ    ·handlerSubOpMoveSliceBool(SB), AX
	MOVQ    AX, ·tier1JumpTable+1344(SB)

	LEAQ    ·handlerSubOpMoveSliceUint(SB), AX
	MOVQ    AX, ·tier1JumpTable+1352(SB)

	LEAQ    ·handlerSubOpMoveSliceByte(SB), AX
	MOVQ    AX, ·tier1JumpTable+1360(SB)

	LEAQ    ·handlerSubOpAppendSliceIntDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1368(SB)

	LEAQ    ·handlerSubOpAppendSliceFloatDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1376(SB)

	LEAQ    ·handlerSubOpAppendSliceStringDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1384(SB)

	LEAQ    ·handlerSubOpAppendSliceBoolDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1392(SB)

	LEAQ    ·handlerSubOpAppendSliceUintDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1400(SB)

	LEAQ    ·handlerSubOpAppendSliceByteDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1408(SB)

	LEAQ    ·handlerSubOpSliceSliceIntDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1416(SB)

	LEAQ    ·handlerSubOpSliceSliceFloatDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1424(SB)

	LEAQ    ·handlerSubOpSliceSliceStringDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1432(SB)

	LEAQ    ·handlerSubOpSliceSliceBoolDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1440(SB)

	LEAQ    ·handlerSubOpSliceSliceUintDirect(SB), AX
	MOVQ    AX, ·tier1JumpTable+1448(SB)

	LEAQ    ·handlerSubOpTier2IncInt(SB), AX
	MOVQ    AX, ·tier2JumpTable+8(SB)

	LEAQ    ·handlerSubOpTier2DecInt(SB), AX
	MOVQ    AX, ·tier2JumpTable+16(SB)

	LEAQ    ·handlerSubOpTier2IncUint(SB), AX
	MOVQ    AX, ·tier2JumpTable+24(SB)

	LEAQ    ·handlerSubOpTier2DecUint(SB), AX
	MOVQ    AX, ·tier2JumpTable+32(SB)

	LEAQ    ·handlerReturnInline(SB), AX
	MOVQ    AX, ·tier2JumpTable+80(SB)

	LEAQ    ·handlerSubOpRangeCheckUintJumpFalse(SB), AX
	MOVQ    AX, ·tier2JumpTable+104(SB)

	LEAQ    ·handlerSubOpAllocStructLiteral(SB), AX
	MOVQ    AX, ·tier2JumpTable+112(SB)

	LEAQ    ·handlerReturnVoidInline(SB), AX
	MOVQ    AX, ·tier3JumpTable+8(SB)

	LEAQ    ·handlerPathBShimResetSharedCell(SB), AX
	MOVQ    AX, ·tier1JumpTable+1112(SB)

	LEAQ    ·handlerPathBShimWriteSharedCell(SB), AX
	MOVQ    AX, ·tier1JumpTable+1120(SB)

	LEAQ    ·handlerPathBShimSliceOp(SB), AX
	MOVQ    AX, ·tier1JumpTable+1128(SB)

	LEAQ    ·handlerPathBShimRangeInit(SB), AX
	MOVQ    AX, ·tier1JumpTable+1136(SB)

	LEAQ    ·handlerPathBShimRangeNext(SB), AX
	MOVQ    AX, ·tier1JumpTable+1144(SB)

	LEAQ    ·handlerPathBShimGetGlobalWide(SB), AX
	MOVQ    AX, ·tier1JumpTable+1152(SB)

	LEAQ    ·handlerPathBShimSetGlobalWide(SB), AX
	MOVQ    AX, ·tier1JumpTable+1160(SB)

	LEAQ    ·handlerPathBShimEqInterfaceNil(SB), AX
	MOVQ    AX, ·tier1JumpTable+1168(SB)

	LEAQ    ·handlerPathBShimNeInterfaceNil(SB), AX
	MOVQ    AX, ·tier1JumpTable+1176(SB)

	LEAQ    ·handlerPathBShimSyncClosureUpvalues(SB), AX
	MOVQ    AX, ·tier2JumpTable+120(SB)

	RET     

// dispatchLoop is the ASM dispatch entry point; loads ctx into pinned registers and performs the first dispatch (subsequent dispatches happen via DISPATCH_NEXT at each handler tail).
TEXT ·dispatchLoop(SB), NOSPLIT, $0-8
	MOVQ    ctx+0(FP), R15
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_PC(R15), R14
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	LEAQ    ·flatJumpTable(SB), R10
	DISPATCH_NEXT()

// pathBFallback is the default handler for non-tier-1 opcodes; un-advances pc and returns to Go with EXIT_TIER2.
TEXT ·pathBFallback(SB), NOSPLIT|NOFRAME, $0
	DECQ    R14
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_TIER2, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     

// handlerCallExit exits to Go with EXIT_CALL for dedicated OpCall handling.
TEXT ·handlerCallExit(SB), NOSPLIT|NOFRAME, $0
	DECQ    R14
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_CALL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     

// handlerReturnExit exits to Go with EXIT_RETURN for dedicated OpReturn handling.
TEXT ·handlerReturnExit(SB), NOSPLIT|NOFRAME, $0
	DECQ    R14
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_RETURN, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     

// handlerReturnVoidExit exits to Go with EXIT_RETURN_VOID for dedicated OpReturnVoid handling.
TEXT ·handlerReturnVoidExit(SB), NOSPLIT|NOFRAME, $0
	DECQ    R14
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_RETURN_VOID, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     

// handlerTailCallExit exits to Go with EXIT_TAIL_CALL for dedicated OpTailCall handling.
TEXT ·handlerTailCallExit(SB), NOSPLIT|NOFRAME, $0
	DECQ    R14
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_TAIL_CALL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
