// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpMoveInt copies the value at bank[C] into bank[B] for the tier-1 register-move sub-op.
TEXT ·handlerSubOpMoveInt(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD (R23)(R4<<3), R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMoveFloat copies floats[C] to floats[B] for the tier-1 register-move sub-op.
TEXT ·handlerSubOpMoveFloat(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD (R24)(R4<<3), F0
	FMOVD F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMoveBool copies bank[C] to bank[B] for a context-base-loaded register-move sub-op.
TEXT ·handlerSubOpMoveBool(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_BOOLS_BASE(R19), R6
	MOVBU (R6)(R4), R5
	MOVD CTX_BOOLS_BASE(R19), R6
	MOVB R5, (R6)(R3)
	DISPATCH_NEXT()

// handlerSubOpMoveUint copies bank[C] to bank[B] for a context-base-loaded register-move sub-op.
TEXT ·handlerSubOpMoveUint(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_UINTS_BASE(R19), R6
	MOVD (R6)(R4<<3), R5
	MOVD CTX_UINTS_BASE(R19), R6
	MOVD R5, (R6)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMoveString copies strings[C] to strings[B] for the tier-1 register-move sub-op.
TEXT ·handlerSubOpMoveString(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_STRINGS_BASE(R19), R5
	LSL  $4, R3, R3
	LSL  $4, R4, R4
	ADD  R3, R5, R6
	ADD  R4, R5, R7
	MOVD (R7), R8
	MOVD 8(R7), R9
	MOVD R8, (R6)
	MOVD R9, 8(R6)
	DISPATCH_NEXT()
