// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerTruncateNarrow implements opTruncateNarrow (tier-0 ASM lift). Narrows register A to B bits. registerKind C selects sign-extending int path or zero-masking uint path; never leaves the dispatch loop.
TEXT ·handlerTruncateNarrow(SB), NOSPLIT|NOFRAME, $0
	// Extract A (register index) into AX.
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX

	// Extract B (bit width: 8/16/32) into BX.
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX

	// Extract C (registerKind: 0=int, 5=uint) into CX.
	MOVQ    DX, CX
	SHRQ    $24, CX

	// Branch on registerKind == registerUint (5).
	CMPQ    CX, $5
	JNE     handler_truncate_narrow_int

	// --- Uint path: uints[A] &= (1 << B) - 1 ---
	MOVQ    $1, SI
	MOVB    BL, CL
	SHLQ    CL, SI
	SUBQ    $1, SI
	MOVQ    CTX_UINTS_BASE(R15), DI
	ANDQ    SI, (DI)(AX*8)
	JMP     handler_truncate_narrow_done

handler_truncate_narrow_int:
	// --- Int path: ints[A] = (ints[A] << (64-B)) >> (64-B)  (arithmetic) ---
	MOVQ    (R8)(AX*8), SI
	MOVQ    $64, CX
	SUBQ    BX, CX
	SHLQ    CL, SI
	SARQ    CL, SI
	MOVQ    SI, (R8)(AX*8)

handler_truncate_narrow_done:
	DISPATCH_NEXT()
