// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerTruncateNarrow implements opTruncateNarrow (tier-0 ASM lift). Narrows register A to B bits. registerKind C selects sign-extending int path or zero-masking uint path; never leaves the dispatch loop.
TEXT ·handlerTruncateNarrow(SB), NOSPLIT|NOFRAME, $0
	// Extract A (register index) into R1.
	LSR  $8, R0, R1
	AND  $0xFF, R1, R1

	// Extract B (bit width) into R2.
	LSR  $16, R0, R2
	AND  $0xFF, R2, R2

	// Extract C (registerKind) into R3.
	LSR  $24, R0, R3

	// Branch on registerKind == registerUint (5).
	CMP  $5, R3
	BNE  handler_truncate_narrow_int

	// --- Uint path: uints[A] &= (1 << B) - 1 ---
	MOVD $1, R4
	LSL  R2, R4, R4
	SUB  $1, R4, R4
	MOVD CTX_UINTS_BASE(R19), R5
	MOVD (R5)(R1<<3), R6
	AND  R4, R6, R6
	MOVD R6, (R5)(R1<<3)
	B    handler_truncate_narrow_done

handler_truncate_narrow_int:
	// --- Int path: ints[A] = (ints[A] << (64-B)) >> (64-B)  (arithmetic) ---
	MOVD $64, R4
	SUB  R2, R4, R4
	MOVD (R23)(R1<<3), R6
	LSL  R4, R6, R6
	ASR  R4, R6, R6
	MOVD R6, (R23)(R1<<3)

handler_truncate_narrow_done:
	DISPATCH_NEXT()
