// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerEqInt sets ints[A] = (ints[B] == ints[C]) ? 1 : 0.
TEXT ·handlerEqInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETEQ   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerNeInt sets ints[A] = (ints[B] != ints[C]) ? 1 : 0.
TEXT ·handlerNeInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETNE   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLtInt sets ints[A] = (ints[B] < ints[C]) ? 1 : 0.
TEXT ·handlerLtInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETLT   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLeInt sets ints[A] = (ints[B] <= ints[C]) ? 1 : 0.
TEXT ·handlerLeInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETLE   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGtInt sets ints[A] = (ints[B] > ints[C]) ? 1 : 0.
TEXT ·handlerGtInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETGT   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGeInt sets ints[A] = (ints[B] >= ints[C]) ? 1 : 0.
TEXT ·handlerGeInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	CMPQ    SI, (R8)(CX*8)
	MOVQ    $0, SI
	SETGE   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerEqUint sets ints[A] = (uints[B] == uints[C]) ? 1 : 0.
TEXT ·handlerEqUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETEQ   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerNeUint sets ints[A] = (uints[B] != uints[C]) ? 1 : 0.
TEXT ·handlerNeUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETNE   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLtUint sets ints[A] = (uints[B] < uints[C]) ? 1 : 0.
TEXT ·handlerLtUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETCS   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLeUint sets ints[A] = (uints[B] <= uints[C]) ? 1 : 0.
TEXT ·handlerLeUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETLS   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGtUint sets ints[A] = (uints[B] > uints[C]) ? 1 : 0.
TEXT ·handlerGtUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETHI   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGeUint sets ints[A] = (uints[B] >= uints[C]) ? 1 : 0.
TEXT ·handlerGeUint(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	CMPQ    SI, (DI)(CX*8)
	MOVQ    $0, SI
	SETCC   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerEqFloat sets ints[A] = (floats[B] == floats[C]) ? 1 : 0.
TEXT ·handlerEqFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	UCOMISD (R9)(CX*8), X0
	MOVQ    $0, SI
	SETEQ   SI
	SETPC   CL
	ANDB    CL, SIB
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerNeFloat sets ints[A] = (floats[B] != floats[C]) ? 1 : 0.
TEXT ·handlerNeFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	UCOMISD (R9)(CX*8), X0
	MOVQ    $0, SI
	SETNE   SI
	SETPS   CL
	ORB     CL, SIB
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLtFloat sets ints[A] = (floats[B] < floats[C]) ? 1 : 0.
TEXT ·handlerLtFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(CX*8), X0
	UCOMISD (R9)(BX*8), X0
	MOVQ    $0, SI
	SETHI   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerLeFloat sets ints[A] = (floats[B] <= floats[C]) ? 1 : 0.
TEXT ·handlerLeFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(CX*8), X0
	UCOMISD (R9)(BX*8), X0
	MOVQ    $0, SI
	SETCC   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGtFloat sets ints[A] = (floats[B] > floats[C]) ? 1 : 0.
TEXT ·handlerGtFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	UCOMISD (R9)(CX*8), X0
	MOVQ    $0, SI
	SETHI   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerGeFloat sets ints[A] = (floats[B] >= floats[C]) ? 1 : 0.
TEXT ·handlerGeFloat(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVSD   (R9)(BX*8), X0
	UCOMISD (R9)(CX*8), X0
	MOVQ    $0, SI
	SETCC   SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerJump unconditionally jumps by signed 16-bit offset B|(C<<8).
TEXT ·handlerJump(SB), NOSPLIT|NOFRAME, $0
	SHRQ    $16, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    AX, R14
	DECQ    CTX_POLL_BUDGET(R15)
	JG      poll_ok
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_POLL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
poll_ok:
	DISPATCH_NEXT()

// handlerJumpIfTrue jumps if ints[A] != 0.
TEXT ·handlerJumpIfTrue(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    (R8)(AX*8), BX
	TESTQ   BX, BX
	JZ      skip
	SHRQ    $16, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    AX, R14
	DECQ    CTX_POLL_BUDGET(R15)
	JG      poll_ok
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_POLL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
poll_ok:

skip:
	DISPATCH_NEXT()

// handlerJumpIfFalse jumps if ints[A] == 0.
TEXT ·handlerJumpIfFalse(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    (R8)(AX*8), BX
	TESTQ   BX, BX
	JNZ     skip
	SHRQ    $16, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    AX, R14
	DECQ    CTX_POLL_BUDGET(R15)
	JG      poll_ok
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_POLL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
poll_ok:

skip:
	DISPATCH_NEXT()
