// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpRealComplex sets floats[B] = real(complex[C]).
TEXT ·handlerSubOpRealComplex(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_COMPLEX_BASE(R19), R5
	LSL  $4, R4, R6
	ADD  R6, R5, R5
	FMOVD 0(R5), F0
	FMOVD F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpImagComplex sets floats[B] = imag(complex[C]).
TEXT ·handlerSubOpImagComplex(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	MOVD CTX_COMPLEX_BASE(R19), R5
	LSL  $4, R4, R6
	ADD  R6, R5, R5
	FMOVD 8(R5), F0
	FMOVD F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMoveComplex sets complex[B] = complex[C] (16-byte copy).
TEXT ·handlerSubOpMoveComplex(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSL  $4, R3, R3
	LSR  $24, R0, R4
	LSL  $4, R4, R4
	MOVD CTX_COMPLEX_BASE(R19), R5
	ADD  R4, R5, R8
	MOVD 0(R8), R6
	MOVD 8(R8), R7
	ADD  R3, R5, R8
	MOVD R6, 0(R8)
	MOVD R7, 8(R8)
	DISPATCH_NEXT()

// handlerSubOpNegComplex sets complex[B] = -complex[C] via sign-bit XOR.
TEXT ·handlerSubOpNegComplex(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSL  $4, R3, R3
	LSR  $24, R0, R4
	LSL  $4, R4, R4
	MOVD CTX_COMPLEX_BASE(R19), R5
	ADD  R4, R5, R9
	MOVD 0(R9), R6
	MOVD 8(R9), R7
	MOVD $0x8000000000000000, R8
	EOR  R8, R6, R6
	EOR  R8, R7, R7
	ADD  R3, R5, R9
	MOVD R6, 0(R9)
	MOVD R7, 8(R9)
	DISPATCH_NEXT()
