// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerAddInt32 sets ints[A] = int64(int32(ints[B] + ints[C])).
TEXT ·handlerAddInt32(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD (R23)(R4<<3), R6
	MOVD (R23)(R5<<3), R7
	ADD  R7, R6, R6
	MOVD R6, (R23)(R3<<3)
	MOVD (R23)(R3<<3), R5
	MOVW R5, R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerSubInt32 sets ints[A] = int64(int32(ints[B] - ints[C])).
TEXT ·handlerSubInt32(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD (R23)(R4<<3), R6
	MOVD (R23)(R5<<3), R7
	SUB  R7, R6, R6
	MOVD R6, (R23)(R3<<3)
	MOVD (R23)(R3<<3), R5
	MOVW R5, R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerMulInt32 sets ints[A] = int64(int32(ints[B] * ints[C])).
TEXT ·handlerMulInt32(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD (R23)(R4<<3), R6
	MOVD (R23)(R5<<3), R7
	MUL  R7, R6, R6
	MOVD R6, (R23)(R3<<3)
	MOVD (R23)(R3<<3), R5
	MOVW R5, R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerAddInt32Const sets ints[A] = int64(int32(ints[B] + intConstants[C])).
TEXT ·handlerAddInt32Const(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD (R23)(R4<<3), R6
	MOVD (R26)(R5<<3), R7
	ADD  R7, R6, R6
	MOVD R6, (R23)(R3<<3)
	MOVD (R23)(R3<<3), R5
	MOVW R5, R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerSubInt32Const sets ints[A] = int64(int32(ints[B] - intConstants[C])).
TEXT ·handlerSubInt32Const(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD (R23)(R4<<3), R6
	MOVD (R26)(R5<<3), R7
	SUB  R7, R6, R6
	MOVD R6, (R23)(R3<<3)
	MOVD (R23)(R3<<3), R5
	MOVW R5, R5
	MOVD R5, (R23)(R3<<3)
	DISPATCH_NEXT()

// handlerAddUint32 sets uints[A] = uint64(uint32(uints[B] + uints[C])).
TEXT ·handlerAddUint32(SB), NOSPLIT|NOFRAME, $0
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	LSR  $16, R0, R4
	AND  $0xFF, R4, R4
	LSR  $24, R0, R5
	MOVD CTX_UINTS_BASE(R19), R8
	MOVD (R8)(R4<<3), R6
	MOVD (R8)(R5<<3), R7
	ADD  R7, R6, R6
	MOVD R6, (R8)(R3<<3)
	MOVD CTX_UINTS_BASE(R19), R4
	MOVD (R4)(R3<<3), R5
	MOVWU R5, R5
	MOVD R5, (R4)(R3<<3)
	DISPATCH_NEXT()
