// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpIncStructFieldInt increments the int field on the struct at ints[B] by one via asmCallIncStructFieldInt.
TEXT ·handlerSubOpIncStructFieldInt(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $32
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	CALL    ·asmCallIncStructFieldInt(SB)
	MOVQ    24(SP), R15
	ADJSP   $-32
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()

// handlerSubOpDecStructFieldInt decrements the int field on the struct at ints[B] by one via asmCallDecStructFieldInt.
TEXT ·handlerSubOpDecStructFieldInt(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $32
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	CALL    ·asmCallDecStructFieldInt(SB)
	MOVQ    24(SP), R15
	ADJSP   $-32
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()

// handlerSubOpIncStructFieldUint increments the uint field on the struct at ints[B] by one via asmCallIncStructFieldUint.
TEXT ·handlerSubOpIncStructFieldUint(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $32
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	CALL    ·asmCallIncStructFieldUint(SB)
	MOVQ    24(SP), R15
	ADJSP   $-32
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()

// handlerSubOpDecStructFieldUint single-level shim wrapping asmCallDecStructFieldUint.
TEXT ·handlerSubOpDecStructFieldUint(SB), NOSPLIT|NOFRAME, $0
	NO_LOCAL_POINTERS
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    R14, CTX_SAVED_PC(R15)
	ADJSP   $32
	MOVQ    R15, 0(SP)
	MOVQ    BX, 8(SP)
	MOVQ    CX, 16(SP)
	CALL    ·asmCallDecStructFieldUint(SB)
	MOVQ    24(SP), R15
	ADJSP   $-32
	MOVQ    CTX_SAVED_PC(R15), R14
	MOVQ    CTX_CODE_BASE(R15), R12
	MOVQ    CTX_CODE_LEN(R15), R13
	MOVQ    CTX_INTS_BASE(R15), R8
	MOVQ    CTX_FLOATS_BASE(R15), R9
	MOVQ    CTX_INT_CONSTS_BASE(R15), R11
	MOVQ    CTX_JUMP_TABLE(R15), R10
	DISPATCH_NEXT()
