// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// arm64 macros for the threaded dispatch loop, included by every vm_dispatch_*_arm64.s.
//
// Pinned registers:
//   R19  &DispatchContext
//   R20  pc (instruction index)
//   R21  codeLen
//   R22  codeBase (&Body[0])
//   R23  intsBase (&regs.Ints[0])
//   R24  floatsBase (&regs.Floats[0])
//   R25  flatJumpTable base (1024 slots)
//   R26  intConstsBase (&IntConstants[0])
//
// Scratch registers: R0-R15, F0-F3. R16-R18 (platform), R28 (g), R29 (FP) and R30 (LR)
// are never used.

// DISPATCH_NEXT decodes the next instruction and jumps to its handler. The tier is the
// trailing-zero count of the word (RBITW then CLZW) >> 3, the sub-op is the first
// non-zero byte, and the jump table index is (tier << 8) | sub-op. An all-zero word is
// the tier-3 no-op, so it loops back to dn_check, which also exits with EXIT_END_OF_CODE
// at the end of the body. The dn labels are function-local, so every handler can inline
// the macro.
#define DISPATCH_NEXT() \
dn_check:                              \
	CMP   R21, R20;                    \
	BLT   dn;                          \
	MOVD  R20, CTX_PC(R19);            \
	MOVD  $EXIT_END_OF_CODE, R3;       \
	MOVD  R3, CTX_EXIT_REASON(R19);    \
	MOVD  R20, CTX_EXIT_PC(R19);       \
	JMP   ·dispatchExit(SB);           \
dn:                                    \
	MOVWU (R22)(R20<<2), R0;           \
	ADD   $1, R20, R20;                \
	CBZ   R0, dn_check;                \
	RBITW R0, R1;                      \
	CLZW  R1, R1;                      \
	LSR   $3, R1, R2;                  \
	AND   $0xF8, R1, R1;               \
	LSR   R1, R0, R3;                  \
	AND   $0xFF, R3, R3;               \
	LSL   $8, R2, R2;                  \
	ORR   R3, R2, R2;                  \
	MOVD  (R25)(R2<<3), R1;            \
	JMP   (R1)

// DIV_BY_ZERO_EXIT stores the error and returns to Go through the dispatchExit trampoline,
// which owns the RET so that framed shims embedding the macro avoid the assembler's
// auto-epilogue.
#define DIV_BY_ZERO_EXIT() \
	MOVD R20, CTX_PC(R19);          \
	MOVD $EXIT_DIV_BY_ZERO, R0;     \
	MOVD R0, CTX_EXIT_REASON(R19);  \
	MOVD R20, CTX_EXIT_PC(R19);     \
	JMP  ·dispatchExit(SB)
