// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpLenString sets ints[B] = len(strings[C]) for the tier-1 string-length sub-op.
TEXT ·handlerSubOpLenString(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_STRINGS_BASE(R15), SI
	SHLQ    $4, BX
	MOVQ    8(SI)(BX*1), CX
	MOVQ    CX, (R8)(AX*8)
	DISPATCH_NEXT()
