// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// initJumpTable fills the 256-entry dispatch table; tier-1 opcodes get their specific handlers, others get pathBFallback.
TEXT ·initJumpTable(SB), NOSPLIT, $0-8
	MOVD table+0(FP), R0

	MOVD $·pathBFallback(SB), R1
	MOVD $256, R2

initjt_fill:
	MOVD R1, (R0)
	ADD  $8, R0, R0
	SUB  $1, R2, R2
	CBNZ R2, initjt_fill

	MOVD table+0(FP), R0

	MOVD $·handlerLoadIntConst(SB), R1
	MOVD R1, 16(R0)

	MOVD $·handlerLoadFloatConst(SB), R1
	MOVD R1, 24(R0)

	MOVD $·handlerAddInt(SB), R1
	MOVD R1, 32(R0)

	MOVD $·handlerSubInt(SB), R1
	MOVD R1, 40(R0)

	MOVD $·handlerMulInt(SB), R1
	MOVD R1, 48(R0)

	MOVD $·handlerDivInt(SB), R1
	MOVD R1, 56(R0)

	MOVD $·handlerRemInt(SB), R1
	MOVD R1, 64(R0)

	MOVD $·handlerBitAnd(SB), R1
	MOVD R1, 72(R0)

	MOVD $·handlerBitOr(SB), R1
	MOVD R1, 80(R0)

	MOVD $·handlerBitXor(SB), R1
	MOVD R1, 88(R0)

	MOVD $·handlerBitAndNot(SB), R1
	MOVD R1, 96(R0)

	MOVD $·handlerShiftLeft(SB), R1
	MOVD R1, 104(R0)

	MOVD $·handlerShiftRight(SB), R1
	MOVD R1, 112(R0)

	MOVD $·handlerAddFloat(SB), R1
	MOVD R1, 120(R0)

	MOVD $·handlerSubFloat(SB), R1
	MOVD R1, 128(R0)

	MOVD $·handlerMulFloat(SB), R1
	MOVD R1, 136(R0)

	MOVD $·handlerDivFloat(SB), R1
	MOVD R1, 144(R0)

	MOVD $·handlerEqInt(SB), R1
	MOVD R1, 152(R0)

	MOVD $·handlerNeInt(SB), R1
	MOVD R1, 160(R0)

	MOVD $·handlerLtInt(SB), R1
	MOVD R1, 168(R0)

	MOVD $·handlerLeInt(SB), R1
	MOVD R1, 176(R0)

	MOVD $·handlerGtInt(SB), R1
	MOVD R1, 184(R0)

	MOVD $·handlerGeInt(SB), R1
	MOVD R1, 192(R0)

	MOVD $·handlerEqFloat(SB), R1
	MOVD R1, 200(R0)

	MOVD $·handlerNeFloat(SB), R1
	MOVD R1, 208(R0)

	MOVD $·handlerLtFloat(SB), R1
	MOVD R1, 216(R0)

	MOVD $·handlerLeFloat(SB), R1
	MOVD R1, 224(R0)

	MOVD $·handlerGtFloat(SB), R1
	MOVD R1, 232(R0)

	MOVD $·handlerGeFloat(SB), R1
	MOVD R1, 240(R0)

	MOVD $·handlerJumpIfTrue(SB), R1
	MOVD R1, 248(R0)

	MOVD $·handlerJumpIfFalse(SB), R1
	MOVD R1, 256(R0)

	MOVD $·handlerSubIntConst(SB), R1
	MOVD R1, 264(R0)

	MOVD $·handlerAddIntConst(SB), R1
	MOVD R1, 272(R0)

	MOVD $·handlerMulIntConst(SB), R1
	MOVD R1, 280(R0)

	MOVD $·handlerAddIntJump(SB), R1
	MOVD R1, 288(R0)

	MOVD $·handlerStringIndex(SB), R1
	MOVD R1, 296(R0)

	MOVD $·handlerEqString(SB), R1
	MOVD R1, 304(R0)

	MOVD $·handlerNeString(SB), R1
	MOVD R1, 312(R0)

	MOVD $·handlerSliceString(SB), R1
	MOVD R1, 320(R0)

	MOVD $·handlerStringIndexToInt(SB), R1
	MOVD R1, 328(R0)

	MOVD $·handlerMoveGeneral(SB), R1
	MOVD R1, 336(R0)

	MOVD $·handlerLoadStringConst(SB), R1
	MOVD R1, 344(R0)

	MOVD $·handlerLoadUintConst(SB), R1
	MOVD R1, 360(R0)

	MOVD $·handlerAddUint(SB), R1
	MOVD R1, 376(R0)

	MOVD $·handlerSubUint(SB), R1
	MOVD R1, 384(R0)

	MOVD $·handlerMulUint(SB), R1
	MOVD R1, 392(R0)

	MOVD $·handlerDivUint(SB), R1
	MOVD R1, 400(R0)

	MOVD $·handlerRemUint(SB), R1
	MOVD R1, 408(R0)

	MOVD $·handlerBitAndUint(SB), R1
	MOVD R1, 416(R0)

	MOVD $·handlerBitOrUint(SB), R1
	MOVD R1, 424(R0)

	MOVD $·handlerBitXorUint(SB), R1
	MOVD R1, 432(R0)

	MOVD $·handlerBitAndNotUint(SB), R1
	MOVD R1, 440(R0)

	MOVD $·handlerShiftLeftUint(SB), R1
	MOVD R1, 448(R0)

	MOVD $·handlerShiftRightUint(SB), R1
	MOVD R1, 456(R0)

	MOVD $·handlerEqUint(SB), R1
	MOVD R1, 464(R0)

	MOVD $·handlerNeUint(SB), R1
	MOVD R1, 472(R0)

	MOVD $·handlerLtUint(SB), R1
	MOVD R1, 480(R0)

	MOVD $·handlerLeUint(SB), R1
	MOVD R1, 488(R0)

	MOVD $·handlerGtUint(SB), R1
	MOVD R1, 496(R0)

	MOVD $·handlerGeUint(SB), R1
	MOVD R1, 504(R0)

	MOVD $·handlerEqGeneral(SB), R1
	MOVD R1, 616(R0)

	MOVD $·handlerTruncateNarrow(SB), R1
	MOVD R1, 704(R0)

	MOVD $·handlerTestNilJumpTrue(SB), R1
	MOVD R1, 728(R0)

	MOVD $·handlerTestNilJumpFalse(SB), R1
	MOVD R1, 736(R0)

	MOVD $·handlerGetUpvalueScalar(SB), R1
	MOVD R1, 752(R0)

	MOVD $·handlerRangeNextSliceByte(SB), R1
	MOVD R1, 952(R0)

	MOVD $·handlerSliceGetIntDirect(SB), R1
	MOVD R1, 1376(R0)

	MOVD $·handlerSliceSetIntDirect(SB), R1
	MOVD R1, 1384(R0)

	MOVD $·handlerGetStructFieldIntT0(SB), R1
	MOVD R1, 1400(R0)

	MOVD $·handlerSetStructFieldIntT0(SB), R1
	MOVD R1, 1408(R0)

	MOVD $·handlerGetStructFieldUintT0(SB), R1
	MOVD R1, 1416(R0)

	MOVD $·handlerSetStructFieldUintT0(SB), R1
	MOVD R1, 1424(R0)

	MOVD $·handlerGetStructFieldFloatT0(SB), R1
	MOVD R1, 1432(R0)

	MOVD $·handlerSetStructFieldFloatT0(SB), R1
	MOVD R1, 1440(R0)

	MOVD $·handlerGetStructFieldBoolT0(SB), R1
	MOVD R1, 1448(R0)

	MOVD $·handlerSetStructFieldBoolT0(SB), R1
	MOVD R1, 1456(R0)

	MOVD $·handlerGetStructFieldGeneralT0(SB), R1
	MOVD R1, 1464(R0)

	MOVD $·handlerSetStructFieldGeneralT0(SB), R1
	MOVD R1, 1472(R0)

	MOVD $·handlerSliceIndexStructFieldInt(SB), R1
	MOVD R1, 1488(R0)

	MOVD $·handlerSliceIndexStructFieldFloat(SB), R1
	MOVD R1, 1504(R0)

	MOVD $·handlerGetStructFieldRawPointerT0(SB), R1
	MOVD R1, 1584(R0)

	MOVD $·handlerSliceGetIntDirectUnchecked(SB), R1
	MOVD R1, 1592(R0)

	MOVD $·handlerSliceSetIntDirectUnchecked(SB), R1
	MOVD R1, 1600(R0)

	MOVD $·handlerDerefSliceGetInt(SB), R1
	MOVD R1, 1680(R0)

	MOVD $·handlerDerefSliceSetInt(SB), R1
	MOVD R1, 1688(R0)

	MOVD $·handlerGetStructFieldSliceLen(SB), R1
	MOVD R1, 1696(R0)

	MOVD $·handlerGetStructFieldSliceIndexScalar(SB), R1
	MOVD R1, 1704(R0)

	MOVD $·handlerPathBShimLoadGeneralConst(SB), R1
	MOVD R1, 352(R0)

	MOVD $·handlerPathBShimLoadComplexConst(SB), R1
	MOVD R1, 368(R0)

	MOVD $·handlerPathBShimAddComplex(SB), R1
	MOVD R1, 512(R0)

	MOVD $·handlerPathBShimSubComplex(SB), R1
	MOVD R1, 520(R0)

	MOVD $·handlerPathBShimMulComplex(SB), R1
	MOVD R1, 528(R0)

	MOVD $·handlerPathBShimDivComplex(SB), R1
	MOVD R1, 536(R0)

	MOVD $·handlerPathBShimEqComplex(SB), R1
	MOVD R1, 544(R0)

	MOVD $·handlerPathBShimNeComplex(SB), R1
	MOVD R1, 552(R0)

	MOVD $·handlerPathBShimBuildComplex(SB), R1
	MOVD R1, 560(R0)

	MOVD $·handlerPathBShimConcatString(SB), R1
	MOVD R1, 568(R0)

	MOVD $·handlerPathBShimConcatRuneString(SB), R1
	MOVD R1, 576(R0)

	MOVD $·handlerPathBShimNeGeneral(SB), R1
	MOVD R1, 624(R0)

	MOVD $·handlerPathBShimLtGeneral(SB), R1
	MOVD R1, 632(R0)

	MOVD $·handlerPathBShimLeGeneral(SB), R1
	MOVD R1, 640(R0)

	MOVD $·handlerPathBShimGtGeneral(SB), R1
	MOVD R1, 648(R0)

	MOVD $·handlerPathBShimGeGeneral(SB), R1
	MOVD R1, 656(R0)

	MOVD $·handlerPathBShimPackInterface(SB), R1
	MOVD R1, 712(R0)

	MOVD $·handlerPathBShimUnpackInterface(SB), R1
	MOVD R1, 720(R0)

	MOVD $·handlerPathBShimMakeClosure(SB), R1
	MOVD R1, 744(R0)

	MOVD $·handlerPathBShimSetUpvalue(SB), R1
	MOVD R1, 760(R0)

	MOVD $·handlerPathBShimMakeSlice(SB), R1
	MOVD R1, 784(R0)

	MOVD $·handlerPathBShimIndex(SB), R1
	MOVD R1, 792(R0)

	MOVD $·handlerPathBShimIndexSet(SB), R1
	MOVD R1, 800(R0)

	MOVD $·handlerPathBShimMapSet(SB), R1
	MOVD R1, 816(R0)

	MOVD $·handlerPathBShimMapIndexOk(SB), R1
	MOVD R1, 824(R0)

	MOVD $·handlerPathBShimAppendSpread(SB), R1
	MOVD R1, 840(R0)

	MOVD $·handlerPathBShimCopy(SB), R1
	MOVD R1, 856(R0)

	MOVD $·handlerPathBShimSliceGetInt(SB), R1
	MOVD R1, 864(R0)

	MOVD $·handlerPathBShimSliceSetInt(SB), R1
	MOVD R1, 872(R0)

	MOVD $·handlerPathBShimSliceGetFloat(SB), R1
	MOVD R1, 880(R0)

	MOVD $·handlerPathBShimSliceSetFloat(SB), R1
	MOVD R1, 888(R0)

	MOVD $·handlerPathBShimSliceGetString(SB), R1
	MOVD R1, 896(R0)

	MOVD $·handlerPathBShimSliceSetString(SB), R1
	MOVD R1, 904(R0)

	MOVD $·handlerPathBShimSliceGetBool(SB), R1
	MOVD R1, 912(R0)

	MOVD $·handlerPathBShimSliceSetBool(SB), R1
	MOVD R1, 920(R0)

	MOVD $·handlerPathBShimSliceGetUint(SB), R1
	MOVD R1, 928(R0)

	MOVD $·handlerPathBShimSliceSetUint(SB), R1
	MOVD R1, 936(R0)

	MOVD $·handlerPathBShimMapGetIntInt(SB), R1
	MOVD R1, 960(R0)

	MOVD $·handlerPathBShimMapSetIntInt(SB), R1
	MOVD R1, 968(R0)

	MOVD $·handlerPathBShimMapGetStringInt(SB), R1
	MOVD R1, 976(R0)

	MOVD $·handlerPathBShimMapSetStringInt(SB), R1
	MOVD R1, 984(R0)

	MOVD $·handlerPathBShimMapGetStringString(SB), R1
	MOVD R1, 992(R0)

	MOVD $·handlerPathBShimMapSetStringString(SB), R1
	MOVD R1, 1000(R0)

	MOVD $·handlerPathBShimMapGetIntString(SB), R1
	MOVD R1, 1008(R0)

	MOVD $·handlerPathBShimMapSetIntString(SB), R1
	MOVD R1, 1016(R0)

	MOVD $·handlerPathBShimMapIndexOkIntInt(SB), R1
	MOVD R1, 1024(R0)

	MOVD $·handlerPathBShimMapIndexOkStringInt(SB), R1
	MOVD R1, 1032(R0)

	MOVD $·handlerPathBShimMapIndexOkStringString(SB), R1
	MOVD R1, 1040(R0)

	MOVD $·handlerPathBShimMapIndexOkIntString(SB), R1
	MOVD R1, 1048(R0)

	MOVD $·handlerPathBShimMapGetIntGeneral(SB), R1
	MOVD R1, 1056(R0)

	MOVD $·handlerPathBShimMapIndexOkIntGeneral(SB), R1
	MOVD R1, 1064(R0)

	MOVD $·handlerPathBShimMapGetStringGeneral(SB), R1
	MOVD R1, 1072(R0)

	MOVD $·handlerPathBShimMapIndexOkStringGeneral(SB), R1
	MOVD R1, 1080(R0)

	MOVD $·handlerPathBShimMapSetStringGeneral(SB), R1
	MOVD R1, 1088(R0)

	MOVD $·handlerPathBShimMapAddIntInt(SB), R1
	MOVD R1, 1096(R0)

	MOVD $·handlerPathBShimMapAddStringInt(SB), R1
	MOVD R1, 1104(R0)

	MOVD $·handlerPathBShimBindMethod(SB), R1
	MOVD R1, 1144(R0)

	MOVD $·handlerPathBShimAddr(SB), R1
	MOVD R1, 1160(R0)

	MOVD $·handlerPathBShimDeref(SB), R1
	MOVD R1, 1168(R0)

	MOVD $·handlerPathBShimAllocIndirect(SB), R1
	MOVD R1, 1176(R0)

	MOVD $·handlerPathBShimTypeAssert(SB), R1
	MOVD R1, 1184(R0)

	MOVD $·handlerPathBShimConvert(SB), R1
	MOVD R1, 1192(R0)

	MOVD $·handlerPathBShimGetGlobal(SB), R1
	MOVD R1, 1200(R0)

	MOVD $·handlerPathBShimSetGlobal(SB), R1
	MOVD R1, 1208(R0)

	MOVD $·handlerPathBShimUnsafeString(SB), R1
	MOVD R1, 1216(R0)

	MOVD $·handlerPathBShimUnsafeSlice(SB), R1
	MOVD R1, 1224(R0)

	MOVD $·handlerPathBShimUnsafeAdd(SB), R1
	MOVD R1, 1232(R0)

	MOVD $·handlerPathBShimStrContainsRune(SB), R1
	MOVD R1, 1240(R0)

	MOVD $·handlerPathBShimStrContains(SB), R1
	MOVD R1, 1248(R0)

	MOVD $·handlerPathBShimStrHasPrefix(SB), R1
	MOVD R1, 1256(R0)

	MOVD $·handlerPathBShimStrHasSuffix(SB), R1
	MOVD R1, 1264(R0)

	MOVD $·handlerPathBShimStrEqualFold(SB), R1
	MOVD R1, 1272(R0)

	MOVD $·handlerPathBShimStrIndex(SB), R1
	MOVD R1, 1280(R0)

	MOVD $·handlerPathBShimStrCount(SB), R1
	MOVD R1, 1288(R0)

	MOVD $·handlerPathBShimStrTrimPrefix(SB), R1
	MOVD R1, 1296(R0)

	MOVD $·handlerPathBShimStrTrimSuffix(SB), R1
	MOVD R1, 1304(R0)

	MOVD $·handlerPathBShimStrTrim(SB), R1
	MOVD R1, 1312(R0)

	MOVD $·handlerPathBShimStrIndexRune(SB), R1
	MOVD R1, 1320(R0)

	MOVD $·handlerPathBShimStrRepeat(SB), R1
	MOVD R1, 1328(R0)

	MOVD $·handlerPathBShimStrLastIndex(SB), R1
	MOVD R1, 1336(R0)

	MOVD $·handlerPathBShimStrJoin(SB), R1
	MOVD R1, 1344(R0)

	MOVD $·handlerPathBShimStrSplit(SB), R1
	MOVD R1, 1352(R0)

	MOVD $·handlerPathBShimStrReplaceAll(SB), R1
	MOVD R1, 1360(R0)

	MOVD $·handlerPathBShimMathPow(SB), R1
	MOVD R1, 1368(R0)

	MOVD $·handlerPathBShimCopyStructFieldGeneralT0(SB), R1
	MOVD R1, 1480(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseIntInt(SB), R1
	MOVD R1, 1528(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseStringInt(SB), R1
	MOVD R1, 1536(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseStringString(SB), R1
	MOVD R1, 1544(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseIntString(SB), R1
	MOVD R1, 1552(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseIntGeneral(SB), R1
	MOVD R1, 1560(R0)

	MOVD $·handlerPathBShimMapIndexOkJumpIfFalseStringGeneral(SB), R1
	MOVD R1, 1568(R0)

	MOVD $·handlerPathBShimSwapStructFieldsGeneralT0(SB), R1
	MOVD R1, 1576(R0)

	MOVD $·handlerPathBShimMapSetIntGeneral(SB), R1
	MOVD R1, 1656(R0)

	MOVD $·handlerPathBShimGetStructFieldIndexGeneral(SB), R1
	MOVD R1, 1664(R0)

	MOVD $·handlerPathBShimSetStructFieldIndexGeneral(SB), R1
	MOVD R1, 1672(R0)

	RET

// initSubOpJumpTables installs .abi0 addresses of tier-1+ ASM handlers into the sub-op jump tables, bypassing the ABIInternal wrapper that adds a per-dispatch frame.
TEXT ·initSubOpJumpTables(SB), NOSPLIT, $0-0
	MOVD $·handlerSubOpMathSin(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 8(R2)

	MOVD $·handlerSubOpMathCos(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 16(R2)

	MOVD $·handlerSubOpMathExp(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 24(R2)

	MOVD $·handlerSubOpMathTan(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 32(R2)

	MOVD $·handlerSubOpMathMod(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 40(R2)

	MOVD $·handlerSubOpStrconvFormatBool(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 48(R2)

	MOVD $·handlerSubOpStrconvFormatInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 56(R2)

	MOVD $·handlerSubOpStrconvItoa(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 64(R2)

	MOVD $·handlerSubOpRealComplex(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 72(R2)

	MOVD $·handlerSubOpImagComplex(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 80(R2)

	MOVD $·handlerSubOpBytesToString(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 88(R2)

	MOVD $·handlerSubOpCap(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 104(R2)

	MOVD $·handlerSubOpNegComplex(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 112(R2)

	MOVD $·handlerSubOpMoveComplex(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 120(R2)

	MOVD $·handlerSubOpMakeSliceInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 128(R2)

	MOVD $·handlerSubOpLenSliceIntDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 136(R2)

	MOVD $·handlerSubOpMakeSliceFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 144(R2)

	MOVD $·handlerSubOpSliceGetFloatDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 152(R2)

	MOVD $·handlerSubOpSliceSetFloatDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 160(R2)

	MOVD $·handlerSubOpLenSliceFloatDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 168(R2)

	MOVD $·handlerSubOpMakeSliceString(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 176(R2)

	MOVD $·handlerSubOpSliceGetStringDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 184(R2)

	MOVD $·handlerSubOpSliceSetStringDirectExit(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 192(R2)

	MOVD $·handlerSubOpLenSliceStringDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 200(R2)

	MOVD $·handlerSubOpMakeSliceBool(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 208(R2)

	MOVD $·handlerSubOpSliceGetBoolDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 216(R2)

	MOVD $·handlerSubOpSliceSetBoolDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 224(R2)

	MOVD $·handlerSubOpLenSliceBoolDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 232(R2)

	MOVD $·handlerSubOpMakeSliceUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 240(R2)

	MOVD $·handlerSubOpSliceGetUintDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 248(R2)

	MOVD $·handlerSubOpSliceSetUintDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 256(R2)

	MOVD $·handlerSubOpLenSliceUintDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 264(R2)

	MOVD $·handlerSubOpBoxSliceInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 272(R2)

	MOVD $·handlerSubOpMoveInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 280(R2)

	MOVD $·handlerSubOpMoveFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 288(R2)

	MOVD $·handlerSubOpMoveString(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 296(R2)

	MOVD $·handlerSubOpMoveBool(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 304(R2)

	MOVD $·handlerSubOpMoveUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 312(R2)

	MOVD $·handlerSubOpNegInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 368(R2)

	MOVD $·handlerSubOpNegFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 376(R2)

	MOVD $·handlerSubOpBitNot(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 384(R2)

	MOVD $·handlerSubOpIntToFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 400(R2)

	MOVD $·handlerSubOpFloatToInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 408(R2)

	MOVD $·handlerSubOpUintToFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 456(R2)

	MOVD $·handlerSubOpFloatToUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 464(R2)

	MOVD $·handlerSubOpMathSqrt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 472(R2)

	MOVD $·handlerSubOpMathAbs(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 480(R2)

	MOVD $·handlerSubOpMathFloor(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 488(R2)

	MOVD $·handlerSubOpMathCeil(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 496(R2)

	MOVD $·handlerSubOpMathTrunc(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 504(R2)

	MOVD $·handlerSubOpMathRound(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 512(R2)

	MOVD $·handlerSubOpLenString(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 520(R2)

	MOVD $·handlerJump(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 592(R2)

	MOVD $·handlerLoadIntConstSmall(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 600(R2)

	MOVD $·handlerLoadBool(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 608(R2)

	MOVD $·handlerIncIntJumpLt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 616(R2)

	MOVD $·handlerLenStringLtJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 624(R2)

	MOVD $·handlerSubOpAddUintConst(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 768(R2)

	MOVD $·handlerSubOpSubUintConst(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 776(R2)

	MOVD $·handlerSubOpBitAndUintConst(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 784(R2)

	MOVD $·handlerSubOpLoadUintConstSmall(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 792(R2)

	MOVD $·handlerSubOpIncStructFieldInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 856(R2)

	MOVD $·handlerSubOpDecStructFieldInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 864(R2)

	MOVD $·handlerSubOpIncStructFieldUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 872(R2)

	MOVD $·handlerSubOpDecStructFieldUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 880(R2)

	MOVD $·handlerSubOpMakeSliceByte(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 888(R2)

	MOVD $·handlerSubOpSliceGetByteDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 896(R2)

	MOVD $·handlerSubOpSliceSetByteDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 904(R2)

	MOVD $·handlerSubOpLenSliceByteDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 912(R2)

	MOVD $·handlerSubOpSliceByteSlice(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 920(R2)

	MOVD $·handlerLtIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 928(R2)

	MOVD $·handlerLeIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 936(R2)

	MOVD $·handlerGtIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 944(R2)

	MOVD $·handlerGeIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 952(R2)

	MOVD $·handlerEqIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 960(R2)

	MOVD $·handlerNeIntJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 968(R2)

	MOVD $·handlerLeIntConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 976(R2)

	MOVD $·handlerLtIntConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 984(R2)

	MOVD $·handlerEqIntConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 992(R2)

	MOVD $·handlerEqIntConstJumpTrue(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1000(R2)

	MOVD $·handlerGeIntConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1008(R2)

	MOVD $·handlerGtIntConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1016(R2)

	MOVD $·handlerCallInline(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1024(R2)

	MOVD $·handlerTailCallInline(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1032(R2)

	MOVD $·handlerCallMethodInline(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1056(R2)

	MOVD $·handlerCallInlineScalar(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1072(R2)

	MOVD $·handlerLoadBoolConst(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1104(R2)

	MOVD $·handlerSubOpEqUintConstJumpFalse(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1200(R2)

	MOVD $·handlerSubOpMoveSliceInt(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1320(R2)

	MOVD $·handlerSubOpMoveSliceFloat(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1328(R2)

	MOVD $·handlerSubOpMoveSliceString(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1336(R2)

	MOVD $·handlerSubOpMoveSliceBool(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1344(R2)

	MOVD $·handlerSubOpMoveSliceUint(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1352(R2)

	MOVD $·handlerSubOpMoveSliceByte(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1360(R2)

	MOVD $·handlerSubOpAppendSliceIntDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1368(R2)

	MOVD $·handlerSubOpAppendSliceFloatDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1376(R2)

	MOVD $·handlerSubOpAppendSliceStringDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1384(R2)

	MOVD $·handlerSubOpAppendSliceBoolDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1392(R2)

	MOVD $·handlerSubOpAppendSliceUintDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1400(R2)

	MOVD $·handlerSubOpAppendSliceByteDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1408(R2)

	MOVD $·handlerSubOpSliceSliceIntDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1416(R2)

	MOVD $·handlerSubOpSliceSliceFloatDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1424(R2)

	MOVD $·handlerSubOpSliceSliceStringDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1432(R2)

	MOVD $·handlerSubOpSliceSliceBoolDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1440(R2)

	MOVD $·handlerSubOpSliceSliceUintDirect(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1448(R2)

	MOVD $·handlerSubOpTier2IncInt(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 8(R2)

	MOVD $·handlerSubOpTier2DecInt(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 16(R2)

	MOVD $·handlerSubOpTier2IncUint(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 24(R2)

	MOVD $·handlerSubOpTier2DecUint(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 32(R2)

	MOVD $·handlerReturnInline(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 80(R2)

	MOVD $·handlerSubOpRangeCheckUintJumpFalse(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 104(R2)

	MOVD $·handlerSubOpAllocStructLiteral(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 112(R2)

	MOVD $·handlerReturnVoidInline(SB), R1
	MOVD $·tier3JumpTable(SB), R2
	MOVD R1, 8(R2)

	MOVD $·handlerPathBShimResetSharedCell(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1112(R2)

	MOVD $·handlerPathBShimWriteSharedCell(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1120(R2)

	MOVD $·handlerPathBShimSliceOp(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1128(R2)

	MOVD $·handlerPathBShimRangeInit(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1136(R2)

	MOVD $·handlerPathBShimRangeNext(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1144(R2)

	MOVD $·handlerPathBShimGetGlobalWide(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1152(R2)

	MOVD $·handlerPathBShimSetGlobalWide(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1160(R2)

	MOVD $·handlerPathBShimEqInterfaceNil(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1168(R2)

	MOVD $·handlerPathBShimNeInterfaceNil(SB), R1
	MOVD $·tier1JumpTable(SB), R2
	MOVD R1, 1176(R2)

	MOVD $·handlerPathBShimSyncClosureUpvalues(SB), R1
	MOVD $·tier2JumpTable(SB), R2
	MOVD R1, 120(R2)

	RET

// dispatchLoop is the ASM dispatch entry point; loads ctx into pinned registers and performs the first dispatch (subsequent dispatches happen via DISPATCH_NEXT at each handler tail).
TEXT ·dispatchLoop(SB), NOSPLIT, $0-8
	MOVD ctx+0(FP), R19
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_PC(R19), R20
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD $·flatJumpTable(SB), R25
	DISPATCH_NEXT()

// pathBFallback is the default handler for non-tier-1 opcodes; un-advances pc and returns to Go with EXIT_TIER2.
TEXT ·pathBFallback(SB), NOSPLIT|NOFRAME, $0
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_TIER2, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerCallExit exits to Go with EXIT_CALL for dedicated OpCall handling.
TEXT ·handlerCallExit(SB), NOSPLIT|NOFRAME, $0
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_CALL, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerReturnExit exits to Go with EXIT_RETURN for dedicated OpReturn handling.
TEXT ·handlerReturnExit(SB), NOSPLIT|NOFRAME, $0
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_RETURN, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerReturnVoidExit exits to Go with EXIT_RETURN_VOID for dedicated OpReturnVoid handling.
TEXT ·handlerReturnVoidExit(SB), NOSPLIT|NOFRAME, $0
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_RETURN_VOID, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// handlerTailCallExit exits to Go with EXIT_TAIL_CALL for dedicated OpTailCall handling.
TEXT ·handlerTailCallExit(SB), NOSPLIT|NOFRAME, $0
	SUB  $1, R20, R20
	MOVD R20, CTX_PC(R19)
	MOVD $EXIT_TAIL_CALL, R0
	MOVD R0, CTX_EXIT_REASON(R19)
	MOVD R20, CTX_EXIT_PC(R19)
	RET

// dispatchExit is the arm64 JMP target for FRAMEd shims and DISPATCH_NEXT/DIV_BY_ZERO_EXIT paths; its single RET pops the caller-restored R30 without the auto-epilogue that would double-tear-down a FRAMEd shim.
TEXT ·dispatchExit(SB), NOSPLIT|NOFRAME, $0
	RET
