// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerPathBShimMoveGeneral calls ·asmCallHandleMoveGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMoveGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMoveGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimLoadGeneralConst calls ·asmCallHandleLoadGeneralConst(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimLoadGeneralConst(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleLoadGeneralConst(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimLoadComplexConst calls ·asmCallHandleLoadComplexConst(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimLoadComplexConst(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleLoadComplexConst(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimAddComplex calls ·asmCallHandleAddComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimAddComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleAddComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSubComplex calls ·asmCallHandleSubComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSubComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSubComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMulComplex calls ·asmCallHandleMulComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMulComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMulComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimDivComplex calls ·asmCallHandleDivComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimDivComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleDivComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimEqComplex calls ·asmCallHandleEqComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimEqComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleEqComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimNeComplex calls ·asmCallHandleNeComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimNeComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleNeComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimBuildComplex calls ·asmCallHandleBuildComplex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimBuildComplex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleBuildComplex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimConcatString calls ·asmCallHandleConcatString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimConcatString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleConcatString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimConcatRuneString calls ·asmCallHandleConcatRuneString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimConcatRuneString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleConcatRuneString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimEqGeneral calls ·asmCallHandleEqGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimEqGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleEqGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimNeGeneral calls ·asmCallHandleNeGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimNeGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleNeGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimLtGeneral calls ·asmCallHandleLtGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimLtGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleLtGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimLeGeneral calls ·asmCallHandleLeGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimLeGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleLeGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGtGeneral calls ·asmCallHandleGtGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGtGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGtGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGeGeneral calls ·asmCallHandleGeGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGeGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGeGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimPackInterface calls ·asmCallHandlePackInterface(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimPackInterface(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandlePackInterface(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimUnpackInterface calls ·asmCallHandleUnpackInterface(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimUnpackInterface(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleUnpackInterface(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimTestNilJumpTrue calls ·asmCallHandleTestNilJumpTrue(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimTestNilJumpTrue(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleTestNilJumpTrue(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimTestNilJumpFalse calls ·asmCallHandleTestNilJumpFalse(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimTestNilJumpFalse(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleTestNilJumpFalse(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMakeClosure calls ·asmCallHandleMakeClosure(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMakeClosure(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMakeClosure(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetUpvalue calls ·asmCallHandleGetUpvalue(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetUpvalue(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetUpvalue(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetUpvalue calls ·asmCallHandleSetUpvalue(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetUpvalue(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetUpvalue(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMakeSlice calls ·asmCallHandleMakeSlice(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMakeSlice(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMakeSlice(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimIndex calls ·asmCallHandleIndex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimIndex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleIndex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimIndexSet calls ·asmCallHandleIndexSet(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimIndexSet(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleIndexSet(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSet calls ·asmCallHandleMapSet(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSet(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSet(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOk calls ·asmCallHandleMapIndexOk(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOk(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOk(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimAppendSpread calls ·asmCallHandleAppendSpread(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimAppendSpread(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleAppendSpread(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimCopy calls ·asmCallHandleCopy(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimCopy(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleCopy(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceGetInt calls ·asmCallHandleSliceGetInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceGetInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceGetInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceSetInt calls ·asmCallHandleSliceSetInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceSetInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceSetInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceGetFloat calls ·asmCallHandleSliceGetFloat(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceGetFloat(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceGetFloat(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceSetFloat calls ·asmCallHandleSliceSetFloat(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceSetFloat(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceSetFloat(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceGetString calls ·asmCallHandleSliceGetString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceGetString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceGetString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceSetString calls ·asmCallHandleSliceSetString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceSetString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceSetString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceGetBool calls ·asmCallHandleSliceGetBool(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceGetBool(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceGetBool(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceSetBool calls ·asmCallHandleSliceSetBool(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceSetBool(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceSetBool(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceGetUint calls ·asmCallHandleSliceGetUint(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceGetUint(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceGetUint(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceSetUint calls ·asmCallHandleSliceSetUint(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceSetUint(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceSetUint(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetIntInt calls ·asmCallHandleMapGetIntInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetIntInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetIntInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetIntInt calls ·asmCallHandleMapSetIntInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetIntInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetIntInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetStringInt calls ·asmCallHandleMapGetStringInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetStringInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetStringInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetStringInt calls ·asmCallHandleMapSetStringInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetStringInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetStringInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetStringString calls ·asmCallHandleMapGetStringString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetStringString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetStringString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetStringString calls ·asmCallHandleMapSetStringString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetStringString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetStringString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetIntString calls ·asmCallHandleMapGetIntString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetIntString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetIntString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetIntString calls ·asmCallHandleMapSetIntString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetIntString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetIntString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkIntInt calls ·asmCallHandleMapIndexOkIntInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkIntInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkIntInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkStringInt calls ·asmCallHandleMapIndexOkStringInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkStringInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkStringInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkStringString calls ·asmCallHandleMapIndexOkStringString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkStringString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkStringString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkIntString calls ·asmCallHandleMapIndexOkIntString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkIntString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkIntString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetIntGeneral calls ·asmCallHandleMapGetIntGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetIntGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetIntGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkIntGeneral calls ·asmCallHandleMapIndexOkIntGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkIntGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkIntGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapGetStringGeneral calls ·asmCallHandleMapGetStringGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapGetStringGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapGetStringGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkStringGeneral calls ·asmCallHandleMapIndexOkStringGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkStringGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkStringGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetStringGeneral calls ·asmCallHandleMapSetStringGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetStringGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetStringGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapAddIntInt calls ·asmCallHandleMapAddIntInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapAddIntInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapAddIntInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapAddStringInt calls ·asmCallHandleMapAddStringInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapAddStringInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapAddStringInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimBindMethod calls ·asmCallHandleBindMethod(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimBindMethod(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleBindMethod(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimAddr calls ·asmCallHandleAddr(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimAddr(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleAddr(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimDeref calls ·asmCallHandleDeref(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimDeref(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleDeref(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimAllocIndirect calls ·asmCallHandleAllocIndirect(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimAllocIndirect(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleAllocIndirect(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimTypeAssert calls ·asmCallHandleTypeAssert(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimTypeAssert(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleTypeAssert(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimConvert calls ·asmCallHandleConvert(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimConvert(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleConvert(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetGlobal calls ·asmCallHandleGetGlobal(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetGlobal(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetGlobal(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetGlobal calls ·asmCallHandleSetGlobal(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetGlobal(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetGlobal(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimUnsafeString calls ·asmCallHandleUnsafeString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimUnsafeString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleUnsafeString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimUnsafeSlice calls ·asmCallHandleUnsafeSlice(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimUnsafeSlice(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleUnsafeSlice(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimUnsafeAdd calls ·asmCallHandleUnsafeAdd(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimUnsafeAdd(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleUnsafeAdd(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrContainsRune calls ·asmCallHandleStrContainsRune(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrContainsRune(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrContainsRune(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrContains calls ·asmCallHandleStrContains(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrContains(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrContains(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrHasPrefix calls ·asmCallHandleStrHasPrefix(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrHasPrefix(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrHasPrefix(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrHasSuffix calls ·asmCallHandleStrHasSuffix(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrHasSuffix(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrHasSuffix(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrEqualFold calls ·asmCallHandleStrEqualFold(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrEqualFold(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrEqualFold(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrIndex calls ·asmCallHandleStrIndex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrIndex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrIndex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrCount calls ·asmCallHandleStrCount(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrCount(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrCount(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrTrimPrefix calls ·asmCallHandleStrTrimPrefix(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrTrimPrefix(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrTrimPrefix(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrTrimSuffix calls ·asmCallHandleStrTrimSuffix(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrTrimSuffix(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrTrimSuffix(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrTrim calls ·asmCallHandleStrTrim(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrTrim(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrTrim(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrIndexRune calls ·asmCallHandleStrIndexRune(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrIndexRune(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrIndexRune(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrRepeat calls ·asmCallHandleStrRepeat(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrRepeat(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrRepeat(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrLastIndex calls ·asmCallHandleStrLastIndex(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrLastIndex(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrLastIndex(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrJoin calls ·asmCallHandleStrJoin(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrJoin(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrJoin(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrSplit calls ·asmCallHandleStrSplit(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrSplit(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrSplit(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimStrReplaceAll calls ·asmCallHandleStrReplaceAll(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimStrReplaceAll(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleStrReplaceAll(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMathPow calls ·asmCallHandleMathPow(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMathPow(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMathPow(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldIntT0 calls ·asmCallHandleGetStructFieldIntT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldIntT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldIntT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldIntT0 calls ·asmCallHandleSetStructFieldIntT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldIntT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldIntT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldUintT0 calls ·asmCallHandleGetStructFieldUintT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldUintT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldUintT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldUintT0 calls ·asmCallHandleSetStructFieldUintT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldUintT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldUintT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldFloatT0 calls ·asmCallHandleGetStructFieldFloatT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldFloatT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldFloatT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldFloatT0 calls ·asmCallHandleSetStructFieldFloatT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldFloatT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldFloatT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldBoolT0 calls ·asmCallHandleGetStructFieldBoolT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldBoolT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldBoolT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldBoolT0 calls ·asmCallHandleSetStructFieldBoolT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldBoolT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldBoolT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldGeneralT0 calls ·asmCallHandleGetStructFieldGeneralT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldGeneralT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldGeneralT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldGeneralT0 calls ·asmCallHandleSetStructFieldGeneralT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldGeneralT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldGeneralT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimCopyStructFieldGeneralT0 calls ·asmCallHandleCopyStructFieldGeneralT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimCopyStructFieldGeneralT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleCopyStructFieldGeneralT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceIndexStructFieldInt calls ·asmCallHandleSliceIndexStructFieldInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceIndexStructFieldInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceIndexStructFieldInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceIndexStructFieldFloat calls ·asmCallHandleSliceIndexStructFieldFloat(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceIndexStructFieldFloat(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceIndexStructFieldFloat(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseIntInt calls ·asmCallHandleMapIndexOkJumpIfFalseIntInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseIntInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseIntInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseStringInt calls ·asmCallHandleMapIndexOkJumpIfFalseStringInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseStringInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseStringInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseStringString calls ·asmCallHandleMapIndexOkJumpIfFalseStringString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseStringString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseStringString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseIntString calls ·asmCallHandleMapIndexOkJumpIfFalseIntString(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseIntString(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseIntString(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseIntGeneral calls ·asmCallHandleMapIndexOkJumpIfFalseIntGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseIntGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseIntGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapIndexOkJumpIfFalseStringGeneral calls ·asmCallHandleMapIndexOkJumpIfFalseStringGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapIndexOkJumpIfFalseStringGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapIndexOkJumpIfFalseStringGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSwapStructFieldsGeneralT0 calls ·asmCallHandleSwapStructFieldsGeneralT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSwapStructFieldsGeneralT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSwapStructFieldsGeneralT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldRawPointerT0 calls ·asmCallHandleGetStructFieldRawPointerT0(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldRawPointerT0(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldRawPointerT0(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimMapSetIntGeneral calls ·asmCallHandleMapSetIntGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimMapSetIntGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleMapSetIntGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldIndexGeneral calls ·asmCallHandleGetStructFieldIndexGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldIndexGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldIndexGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetStructFieldIndexGeneral calls ·asmCallHandleSetStructFieldIndexGeneral(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetStructFieldIndexGeneral(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetStructFieldIndexGeneral(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimDerefSliceGetInt calls ·asmCallHandleDerefSliceGetInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimDerefSliceGetInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleDerefSliceGetInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimDerefSliceSetInt calls ·asmCallHandleDerefSliceSetInt(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimDerefSliceSetInt(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleDerefSliceSetInt(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldSliceLen calls ·asmCallHandleGetStructFieldSliceLen(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldSliceLen(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldSliceLen(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit_narrow
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit_narrow:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetStructFieldSliceIndexScalar calls ·asmCallHandleGetStructFieldSliceIndexScalar(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetStructFieldSliceIndexScalar(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetStructFieldSliceIndexScalar(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimResetSharedCell calls ·asmCallHandleResetSharedCell(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimResetSharedCell(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleResetSharedCell(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimWriteSharedCell calls ·asmCallHandleWriteSharedCell(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimWriteSharedCell(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleWriteSharedCell(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSliceOp calls ·asmCallHandleSliceOp(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSliceOp(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSliceOp(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimRangeInit calls ·asmCallHandleRangeInit(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimRangeInit(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleRangeInit(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimRangeNext calls ·asmCallHandleRangeNext(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimRangeNext(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleRangeNext(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimGetGlobalWide calls ·asmCallHandleGetGlobalWide(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimGetGlobalWide(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleGetGlobalWide(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSetGlobalWide calls ·asmCallHandleSetGlobalWide(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSetGlobalWide(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSetGlobalWide(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimEqInterfaceNil calls ·asmCallHandleEqInterfaceNil(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimEqInterfaceNil(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleEqInterfaceNil(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimNeInterfaceNil calls ·asmCallHandleNeInterfaceNil(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimNeInterfaceNil(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleNeInterfaceNil(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)

// handlerPathBShimSyncClosureUpvalues calls ·asmCallHandleSyncClosureUpvalues(SB) then tail-JMPs DISPATCH_NEXT on opContinue or dispatchExit on cold paths.
TEXT ·handlerPathBShimSyncClosureUpvalues(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	MOVD R20, CTX_PC(R19)
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVW R0, 16(RSP)
	BL   ·asmCallHandleSyncClosureUpvalues(SB)
	MOVD 24(RSP), R19
	MOVBU CTX_HANDLER_RESULT(R19), R0
	CMP  $0, R0
	BNE  tier2_shim_exit
	MOVD CTX_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()
tier2_shim_exit:
	MOVD 0(RSP), R30
	ADD  $48, RSP
	JMP  ·dispatchExit(SB)
