// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSliceIndexStructFieldFloat sets floats[A] = slice(general[B])[ints[C]].field(layout[ext]) for float64 leaves; other shapes fall back to handlerPathBShimSliceIndexStructFieldFloat.
TEXT ·handlerSliceIndexStructFieldFloat(SB), NOSPLIT|NOFRAME, $0
	MOVL    (R12)(R14*4), BX
	SHRQ    $8, BX
	MOVWLZX BX, BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	CMPQ    BX, FN_STRUCT_LAYOUT_TABLE_LEN(AX)
	JAE     sif_shim
	MOVQ    FN_STRUCT_LAYOUT_TABLE(AX), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVBLZX OFF_LAYOUT_KIND(SI), CX
	CMPQ    CX, $14
	JNE     sif_shim
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (BX)(BX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      sif_shim
	MOVQ    16(DI), BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $23
	JNE     sif_shim
	MOVQ    8(DI), DI
	MOVQ    48(CX), CX
	MOVWLZX OFF_LAYOUT_TYPE_INDEX(SI), BX
	CMPQ    BX, FN_TYPE_TABLE_LEN(AX)
	JAE     sif_shim
	MOVQ    FN_TYPE_TABLE(AX), AX
	SHLQ    $4, BX
	ADDQ    BX, AX
	CMPQ    CX, 8(AX)
	JNE     sif_shim
	MOVQ    0(CX), AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    (R8)(BX*8), BX
	CMPQ    BX, 8(DI)
	JAE     sif_shim
	IMULQ   BX, AX
	MOVQ    (DI), DI
	TESTQ   DI, DI
	JZ      sif_shim
	ADDQ    AX, DI
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVQ    (DI), CX
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CX, (R9)(AX*8)
	INCQ    R14
	DISPATCH_NEXT()
sif_shim:
	JMP     ·handlerPathBShimSliceIndexStructFieldFloat(SB)

// handlerSliceIndexStructFieldInt sets ints[A] = slice(general[B])[ints[C]].field(layout[ext]) for full-width int leaves; other shapes fall back to handlerPathBShimSliceIndexStructFieldInt.
TEXT ·handlerSliceIndexStructFieldInt(SB), NOSPLIT|NOFRAME, $0
	MOVL    (R12)(R14*4), BX
	SHRQ    $8, BX
	MOVWLZX BX, BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	CMPQ    BX, FN_STRUCT_LAYOUT_TABLE_LEN(AX)
	JAE     sif_shim
	MOVQ    FN_STRUCT_LAYOUT_TABLE(AX), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVBLZX OFF_LAYOUT_KIND(SI), CX
	CMPQ    CX, $2
	JE      sif_kind_ok
	CMPQ    CX, $6
	JNE     sif_shim
sif_kind_ok:
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (BX)(BX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      sif_shim
	MOVQ    16(DI), BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $23
	JNE     sif_shim
	MOVQ    8(DI), DI
	MOVQ    48(CX), CX
	MOVWLZX OFF_LAYOUT_TYPE_INDEX(SI), BX
	CMPQ    BX, FN_TYPE_TABLE_LEN(AX)
	JAE     sif_shim
	MOVQ    FN_TYPE_TABLE(AX), AX
	SHLQ    $4, BX
	ADDQ    BX, AX
	CMPQ    CX, 8(AX)
	JNE     sif_shim
	MOVQ    0(CX), AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    (R8)(BX*8), BX
	CMPQ    BX, 8(DI)
	JAE     sif_shim
	IMULQ   BX, AX
	MOVQ    (DI), DI
	TESTQ   DI, DI
	JZ      sif_shim
	ADDQ    AX, DI
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVQ    (DI), CX
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CX, (R8)(AX*8)
	INCQ    R14
	DISPATCH_NEXT()
sif_shim:
	JMP     ·handlerPathBShimSliceIndexStructFieldInt(SB)

// handlerDerefSliceGetInt sets ints[A] = (*general[B])[ints[C]] with a live bounds check; unsupported shapes and range panics fall back to handlerPathBShimDerefSliceGetInt.
TEXT ·handlerDerefSliceGetInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      ds_shim
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JNE     ds_shim
	MOVQ    8(DI), SI
	TESTQ   $0x80, CX
	JZ      ds_direct
	MOVQ    (SI), SI
ds_direct:
	TESTQ   SI, SI
	JZ      ds_shim
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVBLZX BL, BX
	MOVQ    (R8)(BX*8), BX
	CMPQ    BX, 8(SI)
	JAE     ds_shim
	MOVQ    (SI), SI
	MOVQ    (SI)(BX*8), CX
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CX, (R8)(AX*8)
	DISPATCH_NEXT()
ds_shim:
	JMP     ·handlerPathBShimDerefSliceGetInt(SB)

// handlerDerefSliceSetInt sets (*general[A])[ints[B]] = ints[C] with a live bounds check; unsupported shapes and range panics fall back to handlerPathBShimDerefSliceSetInt.
TEXT ·handlerDerefSliceSetInt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      ds_shim
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JNE     ds_shim
	MOVQ    8(DI), SI
	TESTQ   $0x80, CX
	JZ      ds_direct
	MOVQ    (SI), SI
ds_direct:
	TESTQ   SI, SI
	JZ      ds_shim
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    (R8)(BX*8), BX
	CMPQ    BX, 8(SI)
	JAE     ds_shim
	MOVQ    (SI), SI
	MOVQ    DX, AX
	SHRQ    $24, AX
	MOVQ    (R8)(AX*8), CX
	MOVQ    CX, (SI)(BX*8)
	DISPATCH_NEXT()
ds_shim:
	JMP     ·handlerPathBShimDerefSliceSetInt(SB)

// handlerGetStructFieldGeneralT0 reads a plain pointer-kind struct field into general[A] under the write-barrier guard; other field kinds and receiver shapes fall back to handlerPathBShimGetStructFieldGeneralT0.
TEXT ·handlerGetStructFieldGeneralT0(SB), NOSPLIT|NOFRAME, $0
	CMPB    runtime·writeBarrier(SB), $0
	JNE     sf_shim
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	CMPQ    BX, FN_STRUCT_LAYOUT_TABLE_LEN(AX)
	JAE     sf_shim
	MOVQ    FN_STRUCT_LAYOUT_TABLE(AX), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	CMPB    OFF_LAYOUT_FLAGS(SI), $0
	JNE     sf_shim
	MOVBLZX OFF_LAYOUT_KIND(SI), CX
	CMPQ    CX, $22
	JE      sf_kind_ok
	CMPQ    CX, $20
	JNE     sf_shim
sf_kind_ok:
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      sf_shim
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JE      sf_ptr_recv
	CMPQ    BX, $25
	JNE     sf_shim
	TESTQ   $0x100, CX
	JZ      sf_shim
	MOVQ    8(DI), DI
	JMP     sf_have_base
sf_ptr_recv:
	MOVQ    8(DI), DI
	TESTQ   $0x80, CX
	JZ      sf_have_base
	MOVQ    (DI), DI
sf_have_base:
	TESTQ   DI, DI
	JZ      sf_shim
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVBLZX OFF_LAYOUT_KIND(SI), CX
	CMPQ    CX, $20
	JNE     gp_ptr_field
	MOVQ    (DI), SI
	MOVQ    8(DI), BX
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	TESTQ   SI, SI
	JZ      gp_store_zero
	MOVBLZX 23(SI), CX
	ANDQ    $0x1F, CX
	CMPQ    CX, $18
	JE      gp_iface_store
	CMPQ    CX, $19
	JE      gp_iface_store
	CMPQ    CX, $21
	JE      gp_iface_store
	CMPQ    CX, $22
	JE      gp_iface_store
	CMPQ    CX, $26
	JNE     sf_shim
gp_iface_store:
	MOVQ    SI, 0(DI)
	MOVQ    BX, 8(DI)
	MOVQ    CX, 16(DI)
	JMP     gp_done
gp_store_zero:
	XORQ    CX, CX
	MOVQ    CX, 0(DI)
	MOVQ    CX, 8(DI)
	MOVQ    CX, 16(DI)
gp_done:
	DISPATCH_NEXT()
gp_ptr_field:
	MOVQ    (DI), BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	MOVWLZX OFF_LAYOUT_FIELD_TYPE_INDEX(SI), CX
	CMPQ    CX, FN_TYPE_TABLE_LEN(AX)
	JAE     sf_shim
	MOVQ    FN_TYPE_TABLE(AX), AX
	SHLQ    $4, CX
	ADDQ    CX, AX
	MOVQ    8(AX), SI
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    SI, 0(DI)
	MOVQ    BX, 8(DI)
	MOVQ    $22, 16(DI)
	JMP     gp_done
sf_shim:
	JMP     ·handlerPathBShimGetStructFieldGeneralT0(SB)

// handlerSetStructFieldGeneralT0 stores general[B] into a plain pointer-kind or cycle-broken any field of receiver general[A] under the write-barrier guard; other field kinds, value kinds and receiver shapes fall back to handlerPathBShimSetStructFieldGeneralT0.
TEXT ·handlerSetStructFieldGeneralT0(SB), NOSPLIT|NOFRAME, $0
	CMPB    runtime·writeBarrier(SB), $0
	JNE     sf_shim
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	CMPQ    BX, FN_STRUCT_LAYOUT_TABLE_LEN(AX)
	JAE     sf_shim
	MOVQ    FN_STRUCT_LAYOUT_TABLE(AX), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVBLZX OFF_LAYOUT_FLAGS(SI), CX
	TESTQ   CX, CX
	JNZ     ss_flags
	CMPB    OFF_LAYOUT_KIND(SI), $22
	JNE     sf_shim
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      sf_shim
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JE      ssp_ptr_recv
	CMPQ    BX, $25
	JNE     sf_shim
	TESTQ   $0x100, CX
	JZ      sf_shim
	MOVQ    8(DI), DI
	JMP     ssp_have_base
ssp_ptr_recv:
	MOVQ    8(DI), DI
	TESTQ   $0x80, CX
	JZ      ssp_have_base
	MOVQ    (DI), DI
ssp_have_base:
	TESTQ   DI, DI
	JZ      sf_shim
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), BX
	LEAQ    (AX)(AX*2), CX
	LEAQ    (BX)(CX*8), BX
	MOVQ    0(BX), CX
	TESTQ   CX, CX
	JZ      ss_ptr_nil
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	MOVWLZX OFF_LAYOUT_FIELD_TYPE_INDEX(SI), SI
	CMPQ    SI, FN_TYPE_TABLE_LEN(AX)
	JAE     sf_shim
	MOVQ    FN_TYPE_TABLE(AX), AX
	SHLQ    $4, SI
	ADDQ    SI, AX
	MOVQ    8(AX), AX
	CMPQ    CX, AX
	JNE     sf_shim
	MOVQ    16(BX), CX
	MOVQ    CX, AX
	ANDQ    $0x1F, AX
	CMPQ    AX, $22
	JNE     sf_shim
	MOVQ    8(BX), AX
	TESTQ   $0x80, CX
	JZ      ss_ptr_store
	MOVQ    (AX), AX
ss_ptr_store:
	MOVQ    AX, (DI)
	JMP     ss_done
ss_ptr_nil:
	XORQ    AX, AX
	JMP     ss_ptr_store
ss_flags:
	CMPQ    CX, $LAYOUT_FLAG_CYCLE_BROKEN
	JNE     sf_shim
	CMPB    OFF_LAYOUT_KIND(SI), $20
	JNE     sf_shim
	MOVQ    DX, BX
	SHRQ    $8, BX
	MOVBLZX BL, BX
	MOVQ    CTX_GENERALS_BASE(R15), CX
	LEAQ    (BX)(BX*2), BX
	LEAQ    (CX)(BX*8), BX
	MOVQ    16(BX), CX
	ANDQ    $0x1F, CX
	CMPQ    CX, $22
	JNE     sf_shim
	MOVQ    0(BX), CX
	TESTQ   CX, CX
	JZ      sf_shim
	MOVQ    ABI_TYPE_PTR_ELEM(CX), CX
	MOVWLZX OFF_LAYOUT_TYPE_INDEX(SI), BX
	CMPQ    BX, FN_TYPE_TABLE_LEN(AX)
	JAE     sf_shim
	MOVQ    FN_TYPE_TABLE(AX), AX
	SHLQ    $4, BX
	ADDQ    BX, AX
	MOVQ    8(AX), AX
	CMPQ    AX, CX
	JNE     sf_shim
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      sf_shim
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JE      ssi_ptr_recv
	CMPQ    BX, $25
	JNE     sf_shim
	TESTQ   $0x100, CX
	JZ      sf_shim
	MOVQ    8(DI), DI
	JMP     ssi_have_base
ssi_ptr_recv:
	MOVQ    8(DI), DI
	TESTQ   $0x80, CX
	JZ      ssi_have_base
	MOVQ    (DI), DI
ssi_have_base:
	TESTQ   DI, DI
	JZ      sf_shim
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), BX
	LEAQ    (AX)(AX*2), CX
	LEAQ    (BX)(CX*8), BX
	MOVQ    0(BX), AX
	TESTQ   AX, AX
	JZ      ss_iface_nil
	MOVQ    16(BX), CX
	MOVQ    CX, SI
	ANDQ    $0x1F, SI
	CMPQ    SI, $18
	JE      ss_iface_data
	CMPQ    SI, $19
	JE      ss_iface_data
	CMPQ    SI, $21
	JE      ss_iface_data
	CMPQ    SI, $22
	JE      ss_iface_data
	CMPQ    SI, $26
	JNE     sf_shim
ss_iface_data:
	MOVQ    8(BX), BX
	TESTQ   $0x80, CX
	JZ      ss_iface_store
	MOVQ    (BX), BX
ss_iface_store:
	MOVQ    AX, (DI)
	MOVQ    BX, 8(DI)
	JMP     ss_done
ss_iface_nil:
	XORQ    BX, BX
	JMP     ss_iface_store
ss_done:
	DISPATCH_NEXT()
sf_shim:
	JMP     ·handlerPathBShimSetStructFieldGeneralT0(SB)

// handlerGetStructFieldRawPointerT0 re-wraps the cycle-broken eface field at layout[C] through receiver[B] into a direct pointer value in general[A] under the write-barrier guard.
TEXT ·handlerGetStructFieldRawPointerT0(SB), NOSPLIT|NOFRAME, $0
	CMPB    runtime·writeBarrier(SB), $0
	JNE     rp_shim
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_FRAME_POINTER(R15), AX
	IMULQ   $CALLFRAME_SIZE, AX
	ADDQ    CTX_CSTACK_BASE(R15), AX
	MOVQ    CF_FUNCTION(AX), AX
	CMPQ    BX, FN_STRUCT_LAYOUT_TABLE_LEN(AX)
	JAE     rp_shim
	MOVQ    FN_STRUCT_LAYOUT_TABLE(AX), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      rp_zero
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $22
	JE      rp_ptr_recv
	CMPQ    BX, $25
	JNE     rp_shim
	TESTQ   $0x100, CX
	JZ      rp_shim
	MOVQ    8(DI), DI
	JMP     rp_have_base
rp_ptr_recv:
	MOVQ    8(DI), DI
	TESTQ   $0x80, CX
	JZ      rp_have_base
	MOVQ    (DI), DI
rp_have_base:
	TESTQ   DI, DI
	JZ      rp_zero
	MOVLQZX OFF_LAYOUT_OFFSET(SI), CX
	ADDQ    CX, DI
	MOVQ    (DI), CX
	MOVQ    8(DI), SI
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), BX
	LEAQ    (DI)(BX*8), DI
	TESTQ   CX, CX
	JZ      rp_store_zero
	MOVQ    CX, 0(DI)
	MOVQ    SI, 8(DI)
	MOVQ    $22, 16(DI)
	JMP     rp_done
rp_zero:
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), BX
	LEAQ    (DI)(BX*8), DI
rp_store_zero:
	XORQ    CX, CX
	MOVQ    CX, 0(DI)
	MOVQ    CX, 8(DI)
	MOVQ    CX, 16(DI)
rp_done:
	DISPATCH_NEXT()
rp_shim:
	JMP     ·handlerPathBShimGetStructFieldRawPointerT0(SB)

// handlerEqGeneral sets ints[A] = (general[B] == general[C]) for invalid pairs, differing type words, and pointer-identity kinds; other shapes fall back to handlerPathBShimEqGeneral.
TEXT ·handlerEqGeneral(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (BX)(BX*2), AX
	LEAQ    (DI)(AX*8), SI
	LEAQ    (CX)(CX*2), AX
	LEAQ    (DI)(AX*8), DI
	MOVQ    0(SI), AX
	MOVQ    0(DI), CX
	TESTQ   AX, AX
	JZ      eqg_a_invalid
	TESTQ   CX, CX
	JZ      eqg_shim
	MOVQ    16(SI), BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $20
	JE      eqg_shim
	MOVQ    16(DI), CX
	ANDQ    $0x1F, CX
	CMPQ    CX, $20
	JE      eqg_shim
	CMPQ    AX, 0(DI)
	JNE     eqg_store_zero
	CMPQ    BX, $18
	JE      eqg_ptr_cmp
	CMPQ    BX, $22
	JE      eqg_ptr_cmp
	CMPQ    BX, $26
	JNE     eqg_shim
eqg_ptr_cmp:
	MOVQ    16(SI), CX
	MOVQ    8(SI), AX
	TESTQ   $0x80, CX
	JZ      eqg_a_direct
	MOVQ    (AX), AX
eqg_a_direct:
	MOVQ    16(DI), CX
	MOVQ    8(DI), BX
	TESTQ   $0x80, CX
	JZ      eqg_b_direct
	MOVQ    (BX), BX
eqg_b_direct:
	XORQ    CX, CX
	CMPQ    AX, BX
	JNE     eqg_store
	MOVQ    $1, CX
	JMP     eqg_store
eqg_a_invalid:
	TESTQ   CX, CX
	JNE     eqg_shim
	MOVQ    $1, CX
	JMP     eqg_store
eqg_store_zero:
	XORQ    CX, CX
eqg_store:
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CX, (R8)(AX*8)
	DISPATCH_NEXT()
eqg_shim:
	JMP     ·handlerPathBShimEqGeneral(SB)

// handlerMoveGeneral copies general[B] to general[A] for alias mode under the write-barrier guard; other modes and marking phases fall back to handlerPathBShimMoveGeneral.
TEXT ·handlerMoveGeneral(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, CX
	SHRQ    $24, CX
	CMPQ    CX, $1
	JNE     mg_shim
	CMPB    runtime·writeBarrier(SB), $0
	JNE     mg_shim
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (BX)(BX*2), CX
	LEAQ    (DI)(CX*8), SI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(SI), CX
	MOVQ    CX, 0(DI)
	MOVQ    8(SI), CX
	MOVQ    CX, 8(DI)
	MOVQ    16(SI), CX
	MOVQ    CX, 16(DI)
	DISPATCH_NEXT()
mg_shim:
	JMP     ·handlerPathBShimMoveGeneral(SB)

// handlerTestNilJumpTrue jumps by signed offset B|C<<8 when general[A] is invalid or a nil value of a nilable kind.
TEXT ·handlerTestNilJumpTrue(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      tnj_take
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $18
	JB      tnj_skip
	CMPQ    BX, $23
	JA      tnj_skip
	TESTQ   $0x200, CX
	JNZ     tnj_skip
	MOVQ    8(DI), SI
	CMPQ    BX, $20
	JE      tnj_deref
	CMPQ    BX, $23
	JE      tnj_deref
	TESTQ   $0x80, CX
	JZ      tnj_word
tnj_deref:
	MOVQ    (SI), SI
tnj_word:
	TESTQ   SI, SI
	JZ      tnj_take
	JMP     tnj_skip
tnj_take:
	SHRQ    $16, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    AX, R14
	DECQ    CTX_POLL_BUDGET(R15)
	JG      tnj_skip
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_POLL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
tnj_skip:
	DISPATCH_NEXT()

// handlerTestNilJumpFalse jumps by signed offset B|C<<8 when general[A] is valid and non-nil.
TEXT ·handlerTestNilJumpFalse(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    CTX_GENERALS_BASE(R15), DI
	LEAQ    (AX)(AX*2), CX
	LEAQ    (DI)(CX*8), DI
	MOVQ    0(DI), CX
	TESTQ   CX, CX
	JZ      tnj_skip
	MOVQ    16(DI), CX
	MOVQ    CX, BX
	ANDQ    $0x1F, BX
	CMPQ    BX, $18
	JB      tnj_take
	CMPQ    BX, $23
	JA      tnj_take
	TESTQ   $0x200, CX
	JNZ     tnj_take
	MOVQ    8(DI), SI
	CMPQ    BX, $20
	JE      tnj_deref
	CMPQ    BX, $23
	JE      tnj_deref
	TESTQ   $0x80, CX
	JZ      tnj_word
tnj_deref:
	MOVQ    (SI), SI
tnj_word:
	TESTQ   SI, SI
	JZ      tnj_skip
	JMP     tnj_take
tnj_take:
	SHRQ    $16, DX
	MOVWLZX DX, AX
	MOVWQSX AX, AX
	ADDQ    AX, R14
	DECQ    CTX_POLL_BUDGET(R15)
	JG      tnj_skip
	MOVQ    R14, CTX_PC(R15)
	MOVQ    $EXIT_POLL, CTX_EXIT_REASON(R15)
	MOVQ    R14, CTX_EXIT_PC(R15)
	RET     
tnj_skip:
	DISPATCH_NEXT()
