// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerGetStructFieldIntT0 sets ints[A] = receiver[B].field(layout[C]) for full-width scalar fields; other shapes fall back to handlerPathBShimGetStructFieldIntT0.
TEXT ·handlerGetStructFieldIntT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $2, R6
	BEQ  sf_kind_ok
	CMP  $6, R6
	BNE  sf_shim
sf_kind_ok:
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVD (R6), R9
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD R9, (R23)(R3<<3)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldIntT0(SB)

// handlerSetStructFieldIntT0 sets receiver[A].field(layout[C]) = ints[B] for full-width scalar fields; other shapes fall back to handlerPathBShimSetStructFieldIntT0.
TEXT ·handlerSetStructFieldIntT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $2, R6
	BEQ  sf_kind_ok
	CMP  $6, R6
	BNE  sf_shim
sf_kind_ok:
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD (R23)(R3<<3), R9
	MOVD R9, (R6)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimSetStructFieldIntT0(SB)

// handlerGetStructFieldUintT0 sets uints[A] = receiver[B].field(layout[C]) for full-width scalar fields; other shapes fall back to handlerPathBShimGetStructFieldUintT0.
TEXT ·handlerGetStructFieldUintT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $7, R6
	BEQ  sf_kind_ok
	CMP  $11, R6
	BNE  sf_shim
sf_kind_ok:
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVD (R6), R9
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD CTX_UINTS_BASE(R19), R5
	MOVD R9, (R5)(R3<<3)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldUintT0(SB)

// handlerSetStructFieldUintT0 sets receiver[A].field(layout[C]) = uints[B] for full-width scalar fields; other shapes fall back to handlerPathBShimSetStructFieldUintT0.
TEXT ·handlerSetStructFieldUintT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $7, R6
	BEQ  sf_kind_ok
	CMP  $11, R6
	BNE  sf_shim
sf_kind_ok:
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD CTX_UINTS_BASE(R19), R5
	MOVD (R5)(R3<<3), R9
	MOVD R9, (R6)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimSetStructFieldUintT0(SB)

// handlerGetStructFieldFloatT0 sets floats[A] = receiver[B].field(layout[C]) for full-width scalar fields; other shapes fall back to handlerPathBShimGetStructFieldFloatT0.
TEXT ·handlerGetStructFieldFloatT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $14, R6
	BNE  sf_shim
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVD (R6), R9
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD R9, (R24)(R3<<3)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldFloatT0(SB)

// handlerSetStructFieldFloatT0 sets receiver[A].field(layout[C]) = floats[B] for full-width scalar fields; other shapes fall back to handlerPathBShimSetStructFieldFloatT0.
TEXT ·handlerSetStructFieldFloatT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $14, R6
	BNE  sf_shim
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD (R24)(R3<<3), R9
	MOVD R9, (R6)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimSetStructFieldFloatT0(SB)

// handlerGetStructFieldBoolT0 sets bools[A] = receiver[B].field(layout[C]) for full-width scalar fields; other shapes fall back to handlerPathBShimGetStructFieldBoolT0.
TEXT ·handlerGetStructFieldBoolT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $1, R6
	BNE  sf_shim
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVBU (R6), R9
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD CTX_BOOLS_BASE(R19), R5
	MOVB R9, (R5)(R3)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldBoolT0(SB)

// handlerSetStructFieldBoolT0 sets receiver[A].field(layout[C]) = bools[B] for full-width scalar fields; other shapes fall back to handlerPathBShimSetStructFieldBoolT0.
TEXT ·handlerSetStructFieldBoolT0(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $1, R6
	BNE  sf_shim
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD CTX_BOOLS_BASE(R19), R5
	MOVBU (R5)(R3), R9
	MOVB R9, (R6)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimSetStructFieldBoolT0(SB)

// handlerGetStructFieldSliceIndexScalar sets bank(ext2.C)[A] = receiver[B].field(layout[C])[ints[ext1.C]].subfield(ext2.wide); other shapes fall back to handlerPathBShimGetStructFieldSliceIndexScalar.
TEXT ·handlerGetStructFieldSliceIndexScalar(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $23, R6
	BNE  sf_shim
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVWU (R22)(R20<<2), R3
	ADD  $1, R20, R4
	MOVWU (R22)(R4<<2), R5

	LSR  $24, R3, R7
	MOVD (R23)(R7<<3), R7
	MOVD 8(R6), R4
	CMP  R4, R7
	BHS  sf_shim

	LSR  $8, R3, R4
	AND  $0xFFFF, R4, R4
	MUL  R4, R7, R7
	MOVD (R6), R4
	ADD  R4, R7, R7
	LSR  $8, R5, R4
	AND  $0xFFFF, R4, R4
	ADD  R4, R7, R7

	LSR  $24, R5, R5
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3

	CMP  $REGKIND_INT, R5
	BNE  sfsi_not_int
	MOVD (R7), R9
	MOVD R9, (R23)(R3<<3)
	B    sfsi_done
sfsi_not_int:
	CMP  $REGKIND_FLOAT, R5
	BNE  sfsi_not_float
	MOVD (R7), R9
	MOVD R9, (R24)(R3<<3)
	B    sfsi_done
sfsi_not_float:
	CMP  $REGKIND_UINT, R5
	BNE  sfsi_not_uint
	MOVD (R7), R9
	MOVD CTX_UINTS_BASE(R19), R4
	MOVD R9, (R4)(R3<<3)
	B    sfsi_done
sfsi_not_uint:
	CMP  $REGKIND_BOOL, R5
	BNE  sf_shim
	MOVBU (R7), R9
	MOVD CTX_BOOLS_BASE(R19), R4
	MOVB R9, (R4)(R3)
sfsi_done:
	ADD  $2, R20, R20
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldSliceIndexScalar(SB)

// handlerGetStructFieldSliceLen sets ints[A] = len(receiver[B].field(layout[C])) for slice-kind fields; other shapes fall back to handlerPathBShimGetStructFieldSliceLen.
TEXT ·handlerGetStructFieldSliceLen(SB), NOSPLIT|NOFRAME, $0
	LSR  $24, R0, R3
	MOVD CTX_FRAME_POINTER(R19), R4
	MOVD $CALLFRAME_SIZE, R5
	MUL  R5, R4, R4
	MOVD CTX_CSTACK_BASE(R19), R5
	ADD  R4, R5, R5
	MOVD CF_FUNCTION(R5), R5
	MOVD FN_STRUCT_LAYOUT_TABLE_LEN(R5), R4
	CMP  R4, R3
	BHS  sf_shim
	MOVD FN_STRUCT_LAYOUT_TABLE(R5), R5
	LSL  $4, R3, R3
	ADD  R3, R5, R5
	MOVBU OFF_LAYOUT_FLAGS(R5), R6
	CBNZ R6, sf_shim
	MOVBU OFF_LAYOUT_KIND(R5), R6
	CMP  $23, R6
	BNE  sf_shim
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	MOVD $24, R4
	MUL  R4, R3, R4
	MOVD CTX_GENERALS_BASE(R19), R6
	ADD  R4, R6, R6
	MOVD 0(R6), R7
	CBZ  R7, sf_shim
	MOVD 16(R6), R7
	AND  $0x1F, R7, R8
	CMP  $22, R8
	BEQ  sf_ptr_recv
	CMP  $25, R8
	BNE  sf_shim
	TBZ  $8, R7, sf_shim
	MOVD 8(R6), R6
	B    sf_have_base
sf_ptr_recv:
	MOVD 8(R6), R6
	TBZ  $7, R7, sf_have_base
	MOVD (R6), R6
sf_have_base:
	CBZ  R6, sf_shim
	MOVWU OFF_LAYOUT_OFFSET(R5), R7
	ADD  R7, R6, R6
	MOVD 8(R6), R9
	LSR  $8, R0, R3
	AND  $0xFF, R3, R3
	MOVD R9, (R23)(R3<<3)
	DISPATCH_NEXT()
sf_shim:
	B    ·handlerPathBShimGetStructFieldSliceLen(SB)
