// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpMathSqrt sets floats[B] = math.Sqrt(floats[C]).
TEXT ·handlerSubOpMathSqrt(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	SQRTSD  (R9)(BX*8), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMathAbs sets floats[B] = math.Abs(floats[C]).
TEXT ·handlerSubOpMathAbs(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    (R9)(BX*8), SI
	BTRQ    $63, SI
	MOVQ    SI, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMathFloor sets floats[B] = math.Floor(floats[C]).
TEXT ·handlerSubOpMathFloor(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVSD   (R9)(BX*8), X0
	ROUNDSD $1, X0, X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMathCeil sets floats[B] = math.Ceil(floats[C]).
TEXT ·handlerSubOpMathCeil(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVSD   (R9)(BX*8), X0
	ROUNDSD $2, X0, X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMathTrunc sets floats[B] = math.Trunc(floats[C]).
TEXT ·handlerSubOpMathTrunc(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVSD   (R9)(BX*8), X0
	ROUNDSD $3, X0, X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMathRound sets floats[B] = math.Round(floats[C]).
TEXT ·handlerSubOpMathRound(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVSD   (R9)(BX*8), X0
	MOVQ    $0x3FE0000000000000, SI
	MOVQ    $0x8000000000000000, CX
	MOVQ    X0, DI
	ANDQ    CX, DI
	ORQ     DI, SI
	MOVQ    SI, X1
	ADDSD   X1, X0
	ROUNDSD $3, X0, X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()
