// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpStrconvFormatBool sets strings[B] = bools[C] ? "true" : "false" by stamping a pre-allocated header.
TEXT ·handlerSubOpStrconvFormatBool(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R1
	AND  $0xFF, R1, R1
	LSR  $24, R0, R2
	MOVD CTX_BOOLS_BASE(R19), R3
	MOVBU (R3)(R2), R4
	MOVD $·boolStringFalse(SB), R5
	MOVD $·boolStringTrue(SB), R6
	CMP  $0, R4
	CSEL EQ, R5, R6, R5
	MOVD 0(R5), R6
	MOVD 8(R5), R7
	MOVD CTX_STRINGS_BASE(R19), R3
	LSL  $4, R1, R1
	ADD  R1, R3, R3
	MOVD R6, 0(R3)
	MOVD R7, 8(R3)
	DISPATCH_NEXT()

// handlerSubOpStrconvItoa sets strings[B] = strconv.Itoa(int(ints[C])) via asmCallStrconvItoa.
TEXT ·handlerSubOpStrconvItoa(SB), NOSPLIT, $32-0
	NO_LOCAL_POINTERS
	LSR  $16, R0, R1
	AND  $0xFF, R1, R1
	LSR  $24, R0, R2
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVD R1, 16(RSP)
	MOVD R2, 24(RSP)
	BL   ·asmCallStrconvItoa(SB)
	MOVD 32(RSP), R19
	MOVD CTX_SAVED_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $48, RSP
	DISPATCH_NEXT()

// handlerSubOpStrconvFormatInt sets strings[B] = strconv.FormatInt(ints[C], int(ints[ext.A])) via asmCallStrconvFormatInt.
TEXT ·handlerSubOpStrconvFormatInt(SB), NOSPLIT, $48-0
	NO_LOCAL_POINTERS
	LSR  $16, R0, R1
	AND  $0xFF, R1, R1
	LSR  $24, R0, R2
	MOVWU (R22)(R20<<2), R3
	LSR  $8, R3, R3
	AND  $0xFF, R3, R3
	ADD  $1, R20, R20
	MOVD R20, CTX_SAVED_PC(R19)
	MOVD R19, 8(RSP)
	MOVD R1, 16(RSP)
	MOVD R2, 24(RSP)
	MOVD R3, 32(RSP)
	BL   ·asmCallStrconvFormatInt(SB)
	MOVD 40(RSP), R19
	MOVD CTX_SAVED_PC(R19), R20
	MOVD CTX_CODE_BASE(R19), R22
	MOVD CTX_CODE_LEN(R19), R21
	MOVD CTX_INTS_BASE(R19), R23
	MOVD CTX_FLOATS_BASE(R19), R24
	MOVD CTX_INT_CONSTS_BASE(R19), R26
	MOVD CTX_JUMP_TABLE(R19), R25
	MOVD 0(RSP), R30
	ADD  $64, RSP
	DISPATCH_NEXT()
