// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerAddInt32 sets ints[A] = int64(int32(ints[B] + ints[C])).
TEXT ·handlerAddInt32(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	ADDQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	MOVLQSX (R8)(AX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerSubInt32 sets ints[A] = int64(int32(ints[B] - ints[C])).
TEXT ·handlerSubInt32(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	SUBQ    (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	MOVLQSX (R8)(AX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerMulInt32 sets ints[A] = int64(int32(ints[B] * ints[C])).
TEXT ·handlerMulInt32(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	IMULQ   (R8)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	MOVLQSX (R8)(AX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerAddInt32Const sets ints[A] = int64(int32(ints[B] + intConstants[C])).
TEXT ·handlerAddInt32Const(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	ADDQ    (R11)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	MOVLQSX (R8)(AX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerSubInt32Const sets ints[A] = int64(int32(ints[B] - intConstants[C])).
TEXT ·handlerSubInt32Const(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    (R8)(BX*8), SI
	SUBQ    (R11)(CX*8), SI
	MOVQ    SI, (R8)(AX*8)
	MOVLQSX (R8)(AX*8), SI
	MOVQ    SI, (R8)(AX*8)
	DISPATCH_NEXT()

// handlerAddUint32 sets uints[A] = uint64(uint32(uints[B] + uints[C])).
TEXT ·handlerAddUint32(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $8, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $16, BX
	MOVBLZX BL, BX
	MOVQ    DX, CX
	SHRQ    $24, CX
	MOVQ    CTX_UINTS_BASE(R15), DI
	MOVQ    (DI)(BX*8), SI
	ADDQ    (DI)(CX*8), SI
	MOVQ    SI, (DI)(AX*8)
	MOVQ    CTX_UINTS_BASE(R15), BX
	MOVL    (BX)(AX*8), SI
	MOVQ    SI, (BX)(AX*8)
	DISPATCH_NEXT()
