// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && amd64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_amd64.h"

// handlerSubOpRealComplex sets floats[B] = real(complex[C]).
TEXT ·handlerSubOpRealComplex(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_COMPLEX_BASE(R15), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVSD   0(SI), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpImagComplex sets floats[B] = imag(complex[C]).
TEXT ·handlerSubOpImagComplex(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	MOVQ    CTX_COMPLEX_BASE(R15), SI
	SHLQ    $4, BX
	ADDQ    BX, SI
	MOVSD   8(SI), X0
	MOVSD   X0, (R9)(AX*8)
	DISPATCH_NEXT()

// handlerSubOpMoveComplex sets complex[B] = complex[C] (16-byte copy).
TEXT ·handlerSubOpMoveComplex(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	SHLQ    $4, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	SHLQ    $4, BX
	MOVQ    CTX_COMPLEX_BASE(R15), SI
	MOVQ    0(SI)(BX*1), CX
	MOVQ    8(SI)(BX*1), DX
	MOVQ    CX, 0(SI)(AX*1)
	MOVQ    DX, 8(SI)(AX*1)
	DISPATCH_NEXT()

// handlerSubOpNegComplex sets complex[B] = -complex[C] via sign-bit XOR.
TEXT ·handlerSubOpNegComplex(SB), NOSPLIT|NOFRAME, $0
	MOVQ    DX, AX
	SHRQ    $16, AX
	MOVBLZX AL, AX
	SHLQ    $4, AX
	MOVQ    DX, BX
	SHRQ    $24, BX
	SHLQ    $4, BX
	MOVQ    CTX_COMPLEX_BASE(R15), SI
	MOVQ    0(SI)(BX*1), CX
	MOVQ    8(SI)(BX*1), DX
	MOVQ    $0x8000000000000000, DI
	XORQ    DI, CX
	XORQ    DI, DX
	MOVQ    CX, 0(SI)(AX*1)
	MOVQ    DX, 8(SI)(AX*1)
	DISPATCH_NEXT()
