// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && arm64

#include "textflag.h"
#include "funcdata.h"
#include "asm_dispatch_offsets.h"
#include "asm_dispatch_arm64.h"

// handlerSubOpMathSqrt sets floats[B] = math.Sqrt(floats[C]).
TEXT ·handlerSubOpMathSqrt(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD (R24)(R4<<3), F0
	FSQRTD F0, F0
	FMOVD F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMathAbs sets floats[B] = math.Abs(floats[C]).
TEXT ·handlerSubOpMathAbs(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD (R24)(R4<<3), F0
	FABSD F0, F0
	FMOVD F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMathFloor sets floats[B] = math.Floor(floats[C]).
TEXT ·handlerSubOpMathFloor(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD   (R24)(R4<<3), F0
	FRINTMD F0, F0
	FMOVD   F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMathCeil sets floats[B] = math.Ceil(floats[C]).
TEXT ·handlerSubOpMathCeil(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD   (R24)(R4<<3), F0
	FRINTPD F0, F0
	FMOVD   F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMathTrunc sets floats[B] = math.Trunc(floats[C]).
TEXT ·handlerSubOpMathTrunc(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD   (R24)(R4<<3), F0
	FRINTZD F0, F0
	FMOVD   F0, (R24)(R3<<3)
	DISPATCH_NEXT()

// handlerSubOpMathRound sets floats[B] = math.Round(floats[C]).
TEXT ·handlerSubOpMathRound(SB), NOSPLIT|NOFRAME, $0
	LSR  $16, R0, R3
	AND  $0xFF, R3, R3
	LSR  $24, R0, R4
	FMOVD   (R24)(R4<<3), F0
	FRINTAD F0, F0
	FMOVD   F0, (R24)(R3<<3)
	DISPATCH_NEXT()
