// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build ignore

// gen_kind_families renders register-bank handler families.
//
// Covers the typed-slice handlers, native fast-path dispatchers, Pattern C flat wrappers
// and tier-1 typed append adapters.
//
// Each family is a table of variants plus one template lifted verbatim from the
// hand-written handler it replaced. A variant whose body diverged stays hand-written next
// to the generated file.
//
// Usage:
//
//	go run gen_kind_families.go            # rewrite files
//	go run gen_kind_families.go -validate  # check files
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"strings"
	"text/template"
)

const (
	// sliceOutputPath is the typed-slice handler family file.
	sliceOutputPath = "vm_handler_slice_typed_generated.go"

	// fastPathOutputPath is the native fast-path dispatcher family file.
	fastPathOutputPath = "native_fastpath_dispatch_generated.go"

	// flatWrapperOutputPath is the Pattern C flat wrapper family file.
	flatWrapperOutputPath = "vm_handler_flat_wrappers_generated.go"

	// appendAdapterOutputPath is the tier-1 typed append adapter family file.
	appendAdapterOutputPath = "vm_handler_append_adapters_generated.go"

	// outputFileMode is the permission of every written file: source, readable like the rest
	// of the package.
	outputFileMode = 0o644

	// readString is the string argument reader expression.
	readString = "readStringArg(registers, site.Arguments[%d])"

	// readInt is the int argument reader expression.
	readInt = "readIntArg(registers, site.Arguments[%d])"

	// readFloat is the float argument reader expression.
	readFloat = "readFloatArg(registers, site.Arguments[%d])"

	// readBool is the bool argument reader expression.
	readBool = "readBoolArg(registers, site.Arguments[%d])"

	// readAny is the any-typed argument reader expression.
	readAny = "readNativeAnyArg(vm, cached, site, registers, %d)"
)

// generatedFileHeader opens every emitted file: the Apache 2.0 licence and the
// anti-fascism stand the rest of the codebase carries, then the Go-standard generated
// marker that golangci-lint and gopls look for.
const generatedFileHeader = `// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

// Code generated by go run gen_kind_families.go. DO NOT EDIT.

`

// sliceTemplate renders every member of one sliceKind. The bodies are the hand-written
// handlers with the kind tokens replaced; keep them token-identical when editing.
const sliceTemplate = `{{if .Make}}func handleSubOpMakeSlice{{.Kind}}(vm *VM, frame *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	extensionWord := readExtensionWord(frame)
	frame.ProgramCounter++
	length := registers.Ints[instruction.C]
	capacity := registers.Ints[extensionWord.A]
	if result, refused := refuseMakeSlice(vm, int(length), int(capacity), unsafe.Sizeof(*new({{.Elem}}))); refused {
		return result
	}
	if vm.Limits.MaxAllocSize > 0 && int(capacity) > vm.Limits.MaxAllocSize {
		vm.evalError = fmt.Errorf(errMakeSliceLimitFmt,
			fault.ErrAllocationLimit, capacity, vm.Limits.MaxAllocSize)
		return opPanicError
	}
	backing := vm.Arena.{{.Alloc}}(int(capacity))
	clear(backing)
	registers.{{.SliceBank}}[instruction.B] = backing[:length:capacity]
	return opContinue
}

{{end}}{{if .GetName}}func {{.GetName}}(vm *VM, frame *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	extensionWord := readExtensionWord(frame)
	frame.ProgramCounter++
	slice := registers.{{.SliceBank}}[instruction.C]
	index := registers.Ints[extensionWord.A]
	if uint64(index) >= uint64(len(slice)) {
		return raiseIndexOutOfRange(vm, int(index), len(slice))
	}
	registers.{{.ScalarBank}}[instruction.B] = {{.ReadExpr}}
	return opContinue
}

func {{.SetName}}(vm *VM, frame *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	extensionWord := readExtensionWord(frame)
	frame.ProgramCounter++
	slice := registers.{{.SliceBank}}[instruction.B]
	index := registers.Ints[instruction.C]
	if uint64(index) >= uint64(len(slice)) {
		return raiseIndexOutOfRange(vm, int(index), len(slice))
	}
	slice[index] = {{.StoreExpr}}
	return opContinue
}

{{end}}{{if .LenCap}}func handleSubOpLenSlice{{.Kind}}Direct(_ *VM, _ *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	registers.Ints[instruction.B] = int64(len(registers.{{.SliceBank}}[instruction.C]))
	return opContinue
}

func handleSubOpCapSlice{{.Kind}}Direct(_ *VM, _ *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	registers.Ints[instruction.B] = int64(cap(registers.{{.SliceBank}}[instruction.C]))
	return opContinue
}

{{end}}{{if .SliceSliceName}}func {{.SliceSliceName}}(vm *VM, frame *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	ext1 := readExtensionWord(frame)
	frame.ProgramCounter++
	flags := ext1.A
	source := registers.{{.SliceBank}}[instruction.C]
	low := int64(0)
	high := int64(len(source))
	capacity := int64(cap(source))
	if flags&isa.SliceLowBoundFlag != 0 {
		low = registers.Ints[ext1.B]
	}
	if flags&isa.SliceHighBoundFlag != 0 {
		high = registers.Ints[ext1.C]
	}
	if flags&isa.SliceMaxBitFlag != 0 {
		ext2 := readExtensionWord(frame)
		frame.ProgramCounter++
		capacity = registers.Ints[ext2.A]
	}
	if low < 0 || high < low || capacity < high || capacity > int64(cap(source)) {
		vm.evalError = fmt.Errorf(sliceBoundsOutOfRangeFormat,
			low, high, capacity, cap(source))
		return opPanicError
	}
	registers.{{.SliceBank}}[instruction.B] = source[low:high:capacity]
	return opContinue
}

{{end}}{{if .AppendElem}}func handleSubOpAppendSlice{{.Kind}}Direct(vm *VM, frame *CallFrame, registers *Registers, instr isa.Instruction) OpResult {
	extensionWord := readExtensionWord(frame)
	frame.ProgramCounter++
	source := registers.{{.SliceBank}}[instr.C]
	element := {{.AppendElem}}
	if vm.Limits.MaxAllocSize > 0 && len(source)+1 > vm.Limits.MaxAllocSize {
		vm.evalError = fmt.Errorf(appendLimitExceededFormat,
			fault.ErrAllocationLimit, len(source)+1, vm.Limits.MaxAllocSize)
		return opPanicError
	}
	registers.{{.SliceBank}}[instr.B] = append(source, element)
	return opContinue
}

{{end}}{{if .RangeNext}}func handleRangeNextSlice{{.Kind}}(_ *VM, frame *CallFrame, registers *Registers, instruction isa.Instruction) OpResult {
	slice := registers.{{.SliceBank}}[instruction.B]
	index := registers.Ints[instruction.A] + 1
	registers.Ints[instruction.A] = index
	if index >= int64(len(slice)) {
		extensionWord := readExtensionWord(frame)
		frame.ProgramCounter++
		jumpOffset := int32(extensionWord.A) | int32(extensionWord.B)<<jumpOffsetByteB | int32(extensionWord.C)<<jumpOffsetByteC
		frame.ProgramCounter += int(jumpOffset)
		return opContinue
	}
	registers.{{.ScalarBank}}[instruction.C] = {{.ReadExpr}}
	frame.ProgramCounter++
	return opContinue
}

{{end}}`

// fastTemplate renders one dispatcher. Call is the fully rendered f(...) expression.
const fastTemplate = `func fpDispatch{{.Name}}(vm *VM, cached any, {{.SiteParam}} *program.CallSite, {{.RegistersParam}} *Registers) {
	f, ok := cached.({{.Sig}})
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	{{if .RetBank}}registers.{{.RetBank}}[site.Returns[0].Register] = {{end}}{{.Call}}
}

`

// flatTemplate renders one Pattern C wrapper.
const flatTemplate = `func handleFlatSubOp{{.Name}}(vm *VM, frame *CallFrame, registers *Registers, instr isa.Instruction) OpResult {
	return {{.Inner}}(vm, frame, registers, {{if .Unary}}isa.Instruction{A: instr.C}{{else}}isa.Instruction{A: instr.B, B: instr.C}{{end}})
}

`

// appendAdapterTemplate renders one adapter.
const appendAdapterTemplate = `func handleSubOpAppend{{.Kind}}(vm *VM, frame *CallFrame, registers *Registers, instr isa.Instruction) OpResult {
	extensionWord := readExtensionWord(frame)
	frame.ProgramCounter++
	return handleAppend{{.Kind}}(vm, frame, registers, isa.Instruction{A: instr.B, B: instr.C, C: extensionWord.A})
}

`

// fastDispatches is the family table: every dispatcher whose body is one type assertion
// and one call. Dispatchers with error returns, variadic formatting, nil-guarded any
// results or fixed-size byte arrays stay hand-written in native_fastpath.go.
var fastDispatches = []fastDispatch{
	{Name: "StringString", Sig: "func(string) string", Args: []fastArg{stringArg}, RetBank: "Strings", RetConv: ""},
	{Name: "StringInt", Sig: "func(string) int", Args: []fastArg{stringArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "StringBool", Sig: "func(string) bool", Args: []fastArg{stringArg}, RetBank: "Bools", RetConv: ""},
	{Name: "StringRuneBool", Sig: "func(string, int32) bool", Args: []fastArg{stringArg, runeArg}, RetBank: "Bools", RetConv: ""},
	{Name: "StringRuneInt", Sig: "func(string, int32) int", Args: []fastArg{stringArg, runeArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "String2Bool", Sig: "func(string, string) bool", Args: []fastArg{stringArg, stringArg}, RetBank: "Bools", RetConv: ""},
	{Name: "String2String", Sig: "func(string, string) string", Args: []fastArg{stringArg, stringArg}, RetBank: "Strings", RetConv: ""},
	{Name: "String2Int", Sig: "func(string, string) int", Args: []fastArg{stringArg, stringArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "String3String", Sig: "func(string, string, string) string", Args: []fastArg{stringArg, stringArg, stringArg}, RetBank: "Strings", RetConv: ""},
	{Name: "IntString", Sig: "func(int) string", Args: []fastArg{intArg}, RetBank: "Strings", RetConv: ""},
	{Name: "IntInt", Sig: "func(int) int", Args: []fastArg{intArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "IntBool", Sig: "func(int) bool", Args: []fastArg{intArg}, RetBank: "Bools", RetConv: ""},
	{Name: "Int2Int", Sig: "func(int, int) int", Args: []fastArg{intArg, intArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "Int2Bool", Sig: "func(int, int) bool", Args: []fastArg{intArg, intArg}, RetBank: "Bools", RetConv: ""},
	{Name: "Int2String", Sig: "func(int, int) string", Args: []fastArg{intArg, intArg}, RetBank: "Strings", RetConv: ""},
	{Name: "Int64IntString", Sig: "func(int64, int) string", Args: []fastArg{int64Arg, intArg}, RetBank: "Strings", RetConv: ""},
	{Name: "Float64Float64", Sig: "func(float64) float64", Args: []fastArg{floatArg}, RetBank: "Floats", RetConv: ""},
	{Name: "Float642Float64", Sig: "func(float64, float64) float64", Args: []fastArg{floatArg, floatArg}, RetBank: "Floats", RetConv: ""},
	{Name: "AnyBool", Sig: "func(any) bool", Args: []fastArg{anyArg}, RetBank: "Bools", RetConv: ""},
	{Name: "AnyString", Sig: "func(any) string", Args: []fastArg{anyArg}, RetBank: "Strings", RetConv: ""},
	{Name: "AnyInt", Sig: "func(any) int", Args: []fastArg{anyArg}, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "AnyInt64", Sig: "func(any) int64", Args: []fastArg{anyArg}, RetBank: "Ints", RetConv: ""},
	{Name: "AnyFloat64", Sig: "func(any) float64", Args: []fastArg{anyArg}, RetBank: "Floats", RetConv: ""},
	{Name: "RetString", Sig: "func() string", Args: nil, RetBank: "Strings", RetConv: ""},
	{Name: "RetBool", Sig: "func() bool", Args: nil, RetBank: "Bools", RetConv: ""},
	{Name: "RetInt", Sig: "func() int", Args: nil, RetBank: "Ints", RetConv: "int64(%s)"},
	{Name: "RetInt64", Sig: "func() int64", Args: nil, RetBank: "Ints", RetConv: ""},
	{Name: "RetFloat64", Sig: "func() float64", Args: nil, RetBank: "Floats", RetConv: ""},
	{Name: "Void", Sig: "func()", Args: nil, RetBank: "", RetConv: ""},
	{Name: "VoidString", Sig: "func(string)", Args: []fastArg{stringArg}, RetBank: "", RetConv: ""},
	{Name: "VoidInt", Sig: "func(int)", Args: []fastArg{intArg}, RetBank: "", RetConv: ""},
	{Name: "VoidInt64", Sig: "func(int64)", Args: []fastArg{int64Arg}, RetBank: "", RetConv: ""},
	{Name: "VoidBool", Sig: "func(bool)", Args: []fastArg{boolArg}, RetBank: "", RetConv: ""},
	{Name: "VoidString2", Sig: "func(string, string)", Args: []fastArg{stringArg, stringArg}, RetBank: "", RetConv: ""},
}

// sliceKind describes one typed-slice element kind: the banks it lives in and which
// members of the family it has, with the per-kind expressions the templates splice in.
type sliceKind struct {
	// Kind is the capitalised kind token in handler names ("Float").
	Kind string

	// Elem is the Go element type ("float64").
	Elem string

	// SliceBank is the Registers field holding slices of Elem ("slicesFloat").
	SliceBank string

	// ScalarBank is the Registers field holding single Elem values ("Floats").
	ScalarBank string

	// Alloc is the RegisterArena method that allocates a backing array
	// ("AllocFloatBacking").
	Alloc string

	// Make emits handleSubOpMakeSlice<Kind>.
	Make bool

	// GetName names the tier-1 element get handler. Empty skips it.
	GetName string

	// SetName names the tier-1 element set handler. Empty skips it.
	SetName string

	// ReadExpr converts slice[index] into the scalar bank's type for get and range-next.
	ReadExpr string

	// StoreExpr is the value the set handler stores into slice[index].
	StoreExpr string

	// LenCap emits handleSubOpLenSlice<Kind>Direct and handleSubOpCapSlice<Kind>Direct.
	LenCap bool

	// SliceSliceName names the three-index slicing handler; empty skips it.
	SliceSliceName string

	// AppendElem is the element expression of handleSubOpAppendSlice<Kind>Direct; empty
	// skips it.
	AppendElem string

	// RangeNext emits handleRangeNextSlice<Kind>.
	RangeNext bool
}

// sliceKinds is the family table. The byte kind's make handler is hand-written because it
// clears only the requested length rather than the whole backing array.
var sliceKinds = []sliceKind{
	{Kind: "Int", Elem: "int64", SliceBank: "SlicesInt", ScalarBank: "Ints", Alloc: "AllocIntBacking",
		Make: true, ReadExpr: "slice[index]", LenCap: true, SliceSliceName: "handleSubOpSliceSliceIntDirect",
		AppendElem: "registers.Ints[extensionWord.A]", RangeNext: true},
	{Kind: "Float", Elem: "float64", SliceBank: "slicesFloat", ScalarBank: "Floats", Alloc: "AllocFloatBacking",
		Make: true, GetName: "handleSubOpSliceGetFloatDirect", SetName: "handleSubOpSliceSetFloatDirect",
		ReadExpr: "slice[index]", StoreExpr: "registers.Floats[extensionWord.A]", LenCap: true,
		SliceSliceName: "handleSubOpSliceSliceFloatDirect", AppendElem: "registers.Floats[extensionWord.A]"},
	{Kind: "String", Elem: "string", SliceBank: "slicesString", ScalarBank: "Strings", Alloc: "AllocStringBacking",
		Make: true, GetName: "handleSubOpSliceGetStringDirect", SetName: "handleSubOpSliceSetStringDirect",
		ReadExpr: "slice[index]", StoreExpr: "MaterialiseStringForTypedSliceStore(vm.Arena, slice, registers.Strings[extensionWord.A])",
		LenCap: true, SliceSliceName: "handleSubOpSliceSliceStringDirect",
		AppendElem: "MaterialiseStringForGoAppend(vm.Arena, source, registers.Strings[extensionWord.A])"},
	{Kind: "Bool", Elem: "bool", SliceBank: "slicesBool", ScalarBank: "Bools", Alloc: "AllocBoolBacking",
		Make: true, GetName: "handleSubOpSliceGetBoolDirect", SetName: "handleSubOpSliceSetBoolDirect",
		ReadExpr: "slice[index]", StoreExpr: "registers.Bools[extensionWord.A]", LenCap: true,
		SliceSliceName: "handleSubOpSliceSliceBoolDirect", AppendElem: "registers.Bools[extensionWord.A]"},
	{Kind: "Uint", Elem: "uint64", SliceBank: "slicesUint", ScalarBank: "Uints", Alloc: "AllocUintBacking",
		Make: true, GetName: "handleSubOpSliceGetUintDirect", SetName: "handleSubOpSliceSetUintDirect",
		ReadExpr: "slice[index]", StoreExpr: "registers.Uints[extensionWord.A]", LenCap: true,
		SliceSliceName: "handleSubOpSliceSliceUintDirect", AppendElem: "registers.Uints[extensionWord.A]"},
	{Kind: "Byte", Elem: "byte", SliceBank: "slicesByte", ScalarBank: "Uints", Alloc: "AllocByteBacking",
		GetName: "handleSliceGetByteDirect", SetName: "handleSliceSetByteDirect",
		ReadExpr: "uint64(slice[index])", StoreExpr: "safeconv.Uint64ToUint8(registers.Uints[extensionWord.A])",
		LenCap: true, SliceSliceName: "handleSubOpSliceByteSlice",
		AppendElem: "safeconv.Uint64ToByteTruncate(registers.Uints[extensionWord.A])", RangeNext: true},
}

// fastArg is one argument of a native fast-path dispatcher.
type fastArg struct {
	// Read is the register-reading expression with %d for the argument index.
	Read string

	// Conv wraps Read with %s when the Go parameter type differs from the bank type.
	Conv string
}

var (
	// stringArg is the fast-path shape for a string parameter.
	stringArg = fastArg{Read: readString, Conv: ""}

	// intArg is the fast-path shape for an int parameter.
	intArg = fastArg{Read: readInt, Conv: "int(%s)"}

	// int64Arg is the fast-path shape for an int64 parameter.
	int64Arg = fastArg{Read: readInt, Conv: ""}

	// runeArg is the fast-path shape for a rune parameter.
	runeArg = fastArg{Read: readInt, Conv: "safeconv.Int64ToInt32(%s)"}

	// floatArg is the fast-path shape for a float64 parameter.
	floatArg = fastArg{Read: readFloat, Conv: ""}

	// boolArg is the fast-path shape for a bool parameter.
	boolArg = fastArg{Read: readBool, Conv: ""}

	// anyArg is the fast-path shape for an any parameter.
	anyArg = fastArg{Read: readAny, Conv: ""}
)

// fastDispatch describes one dispatcher: the asserted function type, how each argument is
// read, and where the result goes.
type fastDispatch struct {
	// Name is the dispatcher suffix after fpDispatch ("StringInt").
	Name string

	// Sig is the asserted Go function type ("func(string) int").
	Sig string

	// Args are the arguments in call order.
	Args []fastArg

	// RetBank is the Registers field receiving the result; empty for void functions.
	RetBank string

	// RetConv wraps the call with %s when the bank type differs from the return type.
	RetConv string
}

// fastView is the template input for one dispatcher: the row plus the rendered call and
// the parameter names, which become blanks when the body never reads them.
type fastView struct {
	fastDispatch

	// Call is the rendered f(args) expression.
	Call string

	// SiteParam is the site parameter name, or "_" when unused.
	SiteParam string

	// RegistersParam is the registers parameter name, or "_".
	RegistersParam string
}

// flatWrapper describes one Pattern C wrapper: the sub-op name suffix, the tier-0 handler
// it dispatches to, and whether the sub-op carries one operand (in C) or two (in B and
// C).
type flatWrapper struct {
	// Name is the suffix after handleFlatSubOp ("MoveInt").
	Name string

	// Inner is the handler that receives the reshaped instruction ("handleMoveInt").
	Inner string

	// Unary maps instr.C to A; otherwise instr.B and instr.C map to A and B.
	Unary bool
}

// flatWrappers is the family table, one row per Pattern C sub-op with a flat wrapper.
var flatWrappers = []flatWrapper{
	{Name: "MoveInt", Inner: "handleMoveInt", Unary: false},
	{Name: "MoveFloat", Inner: "handleMoveFloat", Unary: false},
	{Name: "MoveString", Inner: "handleMoveString", Unary: false},
	{Name: "MoveBool", Inner: "handleMoveBool", Unary: false},
	{Name: "MoveUint", Inner: "handleMoveUint", Unary: false},
	{Name: "MoveSliceInt", Inner: "handleMoveSliceInt", Unary: false},
	{Name: "MoveSliceFloat", Inner: "handleMoveSliceFloat", Unary: false},
	{Name: "MoveSliceString", Inner: "handleMoveSliceString", Unary: false},
	{Name: "MoveSliceBool", Inner: "handleMoveSliceBool", Unary: false},
	{Name: "MoveSliceUint", Inner: "handleMoveSliceUint", Unary: false},
	{Name: "MoveSliceByte", Inner: "handleMoveSliceByte", Unary: false},
	{Name: "MoveIntToGeneral", Inner: "handleMoveIntToGeneral", Unary: false},
	{Name: "MoveGeneralToInt", Inner: "handleMoveGeneralToInt", Unary: false},
	{Name: "MoveFloatToGeneral", Inner: "handleMoveFloatToGeneral", Unary: false},
	{Name: "MoveGeneralToFloat", Inner: "handleMoveGeneralToFloat", Unary: false},
	{Name: "MoveStringToGeneral", Inner: "handleMoveStringToGeneral", Unary: false},
	{Name: "MoveGeneralToString", Inner: "handleMoveGeneralToString", Unary: false},
	{Name: "NegInt", Inner: "handleNegInt", Unary: false},
	{Name: "NegFloat", Inner: "handleNegFloat", Unary: false},
	{Name: "BitNot", Inner: "handleBitNot", Unary: false},
	{Name: "BitNotUint", Inner: "handleBitNotUint", Unary: false},
	{Name: "IntToFloat", Inner: "handleIntToFloat", Unary: false},
	{Name: "FloatToInt", Inner: "handleFloatToInt", Unary: false},
	{Name: "Not", Inner: "handleNot", Unary: false},
	{Name: "BoolToInt", Inner: "handleBoolToInt", Unary: false},
	{Name: "IntToBool", Inner: "handleIntToBool", Unary: false},
	{Name: "IntToUint", Inner: "handleIntToUint", Unary: false},
	{Name: "UintToInt", Inner: "handleUintToInt", Unary: false},
	{Name: "UintToFloat", Inner: "handleUintToFloat", Unary: false},
	{Name: "FloatToUint", Inner: "handleFloatToUint", Unary: false},
	{Name: "MathSqrt", Inner: "handleMathSqrt", Unary: false},
	{Name: "MathAbs", Inner: "handleMathAbs", Unary: false},
	{Name: "MathFloor", Inner: "handleMathFloor", Unary: false},
	{Name: "MathCeil", Inner: "handleMathCeil", Unary: false},
	{Name: "MathTrunc", Inner: "handleMathTrunc", Unary: false},
	{Name: "MathRound", Inner: "handleMathRound", Unary: false},
	{Name: "LenString", Inner: "handleLenString", Unary: false},
	{Name: "RuneToString", Inner: "handleRuneToString", Unary: false},
	{Name: "StrToUpper", Inner: "handleStrToUpper", Unary: false},
	{Name: "StrToLower", Inner: "handleStrToLower", Unary: false},
	{Name: "StrTrimSpace", Inner: "handleStrTrimSpace", Unary: false},
	{Name: "Len", Inner: "handleLen", Unary: false},
	{Name: "StringToBytes", Inner: "handleStringToBytes", Unary: false},
	{Name: "UnsafeStringData", Inner: "handleUnsafeStringData", Unary: false},
	{Name: "UnsafeSliceData", Inner: "handleUnsafeSliceData", Unary: false},
	{Name: "RoundFloat32", Inner: "handleRoundFloat32", Unary: false},
	{Name: "RoundComplex64", Inner: "handleRoundComplex64", Unary: false},
	{Name: "AddUintConst", Inner: "handleAddUintConst", Unary: false},
	{Name: "SubUintConst", Inner: "handleSubUintConst", Unary: false},
	{Name: "BitAndUintConst", Inner: "handleBitAndUintConst", Unary: false},
	{Name: "IncIntJumpLt", Inner: "handleIncIntJumpLt", Unary: false},
	{Name: "LenStringLtJumpFalse", Inner: "handleLenStringLtJumpFalse", Unary: false},
	{Name: "LoadZero", Inner: "handleLoadZero", Unary: false},
	{Name: "Tier2MakeMap", Inner: "handleMakeMap", Unary: true},
	{Name: "MakeChannel", Inner: "handleMakeChannel", Unary: false},
	{Name: "MapDelete", Inner: "handleMapDelete", Unary: false},
	{Name: "ChannelReceive", Inner: "handleChannelReceive", Unary: false},
	{Name: "GetMethod", Inner: "handleGetMethod", Unary: false},
	{Name: "Spill", Inner: "handleSpill", Unary: false},
	{Name: "Reload", Inner: "handleReload", Unary: false},
	{Name: "Tier2IncInt", Inner: "handleIncInt", Unary: true},
	{Name: "Tier2DecInt", Inner: "handleDecInt", Unary: true},
	{Name: "Tier2IncUint", Inner: "handleIncUint", Unary: true},
	{Name: "Tier2DecUint", Inner: "handleDecUint", Unary: true},
	{Name: "Tier2Panic", Inner: "handlePanic", Unary: true},
	{Name: "Tier2Recover", Inner: "handleRecover", Unary: true},
	{Name: "Tier2SetZero", Inner: "handleSetZero", Unary: true},
	{Name: "Tier2ChannelClose", Inner: "handleChannelClose", Unary: true},
	{Name: "Tier2LoadNil", Inner: "handleLoadNil", Unary: true},
	{Name: "Tier2Return", Inner: "handleReturn", Unary: true},
}

// appendAdapter describes one tier-1 typed append adapter: the kind token names both the
// adapter (handleSubOpAppend<Kind>) and the tier-0 handler it reshapes the operands for
// (handleAppend<Kind>).
type appendAdapter struct {
	// Kind is the capitalised kind token ("Int").
	Kind string

	// Bank names the register bank in the doc comment ("int").
	Bank string
}

// appendAdapters is the family table. The uint adapter is hand-written: it carries its
// own in-place and growth fallbacks rather than delegating.
var appendAdapters = []appendAdapter{
	{Kind: "Int", Bank: "int"},
	{Kind: "String", Bank: "string"},
	{Kind: "Float", Bank: "float"},
	{Kind: "Bool", Bank: "bool"},
}

// outputFile is one rendered file and where it lives.
type outputFile struct {
	// path is the output file path.
	path string

	// content is the gofmt-formatted file bytes.
	content []byte
}

// renderCall renders f(args) for one row, one argument per line when there are several,
// wrapped by RetConv when set.
//
// Takes row (fastDispatch) which is the dispatcher.
//
// Returns string which is the call expression.
func renderCall(row fastDispatch) string {
	args := make([]string, 0, len(row.Args))
	for index, argument := range row.Args {
		expr := fmt.Sprintf(argument.Read, index)
		if argument.Conv != "" {
			expr = fmt.Sprintf(argument.Conv, expr)
		}
		args = append(args, expr)
	}
	var call string
	switch len(args) {
	case 0:
		call = "f()"
	case 1:
		call = "f(" + args[0] + ")"
	default:
		call = "f(\n\t\t" + strings.Join(args, ",\n\t\t") + ",\n\t)"
	}
	if row.RetConv != "" {
		call = fmt.Sprintf(row.RetConv, call)
	}
	return call
}

// renderFlatFamily renders every wrapper through flatTemplate.
//
// Returns string which is the rendered declarations.
// Returns error when the template fails.
func renderFlatFamily() (string, error) {
	tmpl, err := template.New("flat").Parse(flatTemplate)
	if err != nil {
		return "", fmt.Errorf("flat wrapper template: %w", err)
	}
	var out strings.Builder
	for _, row := range flatWrappers {
		if err := tmpl.Execute(&out, row); err != nil {
			return "", fmt.Errorf("flat wrapper template for %s: %w", row.Name, err)
		}
	}
	return out.String(), nil
}

// renderAppendAdapterFamily renders every adapter.
//
// Returns string which is the rendered declarations.
// Returns error when the template fails.
func renderAppendAdapterFamily() (string, error) {
	tmpl, err := template.New("append").Parse(appendAdapterTemplate)
	if err != nil {
		return "", fmt.Errorf("append adapter template: %w", err)
	}
	var out strings.Builder
	for _, row := range appendAdapters {
		if err := tmpl.Execute(&out, row); err != nil {
			return "", fmt.Errorf("append adapter template for %s: %w", row.Kind, err)
		}
	}
	return out.String(), nil
}

// main parses flags and runs the generator.
func main() {
	validate := flag.Bool("validate", false,
		"compare the committed files against the generated ones instead of writing them")
	flag.Parse()

	if err := run(*validate); err != nil {
		fmt.Fprintf(os.Stderr, "gen_kind_families: %v\n", err)
		os.Exit(1)
	}
}

// run renders both files in memory and then either validates or writes them.
//
// Takes validate (bool) which selects comparison against the committed files over
// writing.
//
// Returns error which is the first failure, or the validation verdict.
func run(validate bool) error {
	files, err := emitAll()
	if err != nil {
		return err
	}
	if validate {
		return validateFiles(files)
	}
	return writeFiles(files)
}

// emitAll renders the typed-slice and fast-path files.
//
// Returns []outputFile which are the formatted files.
// Returns error when a template fails or the output does not parse.
func emitAll() ([]outputFile, error) {
	sliceBody, err := renderSliceFamily()
	if err != nil {
		return nil, err
	}
	fastBody, err := renderFastFamily()
	if err != nil {
		return nil, err
	}
	flatBody, err := renderFlatFamily()
	if err != nil {
		return nil, err
	}
	appendBody, err := renderAppendAdapterFamily()
	if err != nil {
		return nil, err
	}
	specs := []struct {
		path    string
		imports [][]string
		body    string
	}{
		{path: sliceOutputPath, imports: [][]string{{"fmt", "unsafe"}, {"pipit.sh/pipit/internal/fault", "pipit.sh/pipit/internal/isa", "pipit.sh/pipit/internal/safeconv"}}, body: sliceBody},
		{path: fastPathOutputPath, imports: [][]string{{"pipit.sh/pipit/internal/engine/program", "pipit.sh/pipit/internal/safeconv"}}, body: fastBody},
		{path: flatWrapperOutputPath, imports: [][]string{{"pipit.sh/pipit/internal/isa"}}, body: flatBody},
		{path: appendAdapterOutputPath, imports: [][]string{{"pipit.sh/pipit/internal/isa"}}, body: appendBody},
	}
	files := make([]outputFile, 0, len(specs))
	for _, spec := range specs {
		formatted, err := format.Source([]byte(fileText(spec.imports, spec.body)))
		if err != nil {
			return nil, fmt.Errorf("%s: generated source does not parse: %w", spec.path, err)
		}
		files = append(files, outputFile{path: spec.path, content: formatted})
	}
	return files, nil
}

// renderSliceFamily renders every kind through sliceTemplate.
//
// Returns string which is the rendered declarations.
// Returns error when the template fails.
func renderSliceFamily() (string, error) {
	tmpl, err := template.New("slice").Parse(sliceTemplate)
	if err != nil {
		return "", fmt.Errorf("slice template: %w", err)
	}
	var out strings.Builder
	for _, kind := range sliceKinds {
		if err := tmpl.Execute(&out, kind); err != nil {
			return "", fmt.Errorf("slice template for %s: %w", kind.Kind, err)
		}
	}
	return out.String(), nil
}

// renderFastFamily renders every dispatcher through fastTemplate.
//
// Returns string which is the rendered declarations.
// Returns error when the template fails.
func renderFastFamily() (string, error) {
	tmpl, err := template.New("fast").Parse(fastTemplate)
	if err != nil {
		return "", fmt.Errorf("fast-path template: %w", err)
	}
	var out strings.Builder
	for _, row := range fastDispatches {
		view := fastView{fastDispatch: row, Call: renderCall(row), SiteParam: "site", RegistersParam: "registers"}
		if len(row.Args) == 0 && row.RetBank == "" {
			view.SiteParam, view.RegistersParam = "_", "_"
		}
		if err := tmpl.Execute(&out, view); err != nil {
			return "", fmt.Errorf("fast-path template for %s: %w", row.Name, err)
		}
	}
	return out.String(), nil
}

// fileText assembles one generated file: header, package clause, import groups and body.
//
// Takes importGroups ([][]string) which are the import paths, one blank-separated group
// per element.
// Takes body (string) which is the declarations.
//
// Returns string which is the unformatted file text.
func fileText(importGroups [][]string, body string) string {
	var out strings.Builder
	out.WriteString(generatedFileHeader)
	out.WriteString("package engine\n\n")
	out.WriteString("import (\n")
	for index, group := range importGroups {
		if index > 0 {
			out.WriteString("\n")
		}
		for _, path := range group {
			out.WriteString("\t\"" + path + "\"\n")
		}
	}
	out.WriteString(")\n\n")
	out.WriteString(body)
	return out.String()
}

// validateFiles compares each generated file against the committed one.
//
// Takes files ([]outputFile) which are the freshly generated files.
//
// Returns error naming how many files differ, or nil when every file matches. A file that
// cannot be read counts as differing.
func validateFiles(files []outputFile) error {
	stale := 0
	for _, file := range files {
		committed, err := os.ReadFile(file.path)
		switch {
		case err != nil:
			fmt.Fprintf(os.Stderr, "%s: cannot read the committed file: %v\n", file.path, err)
			stale++
		case !bytes.Equal(committed, file.content):
			fmt.Fprintf(os.Stderr, "%s is stale: first difference at line %d (committed %d bytes, generated %d bytes)\n",
				file.path, firstDifferingLine(committed, file.content), len(committed), len(file.content))
			stale++
		default:
			fmt.Fprintf(os.Stderr, "// %s matches the family tables\n", file.path)
		}
	}
	if stale > 0 {
		return fmt.Errorf("%d of %d generated files no longer match the family tables; "+
			"regenerate with: make generate-kind-families", stale, len(files))
	}
	return nil
}

// firstDifferingLine returns the 1-based line at which two byte slices first differ, or
// the line after the shorter one ends when one is a prefix of the other.
//
// Takes committed ([]byte) which is the file on disk.
// Takes generated ([]byte) which is the freshly generated file.
//
// Returns int which is the line number.
func firstDifferingLine(committed, generated []byte) int {
	line := 1
	for index := range min(len(committed), len(generated)) {
		if committed[index] != generated[index] {
			return line
		}
		if committed[index] == '\n' {
			line++
		}
	}
	return line
}

// writeFiles writes every generated file to disk.
//
// Takes files ([]outputFile) which are the files to write.
//
// Returns error when a write fails.
func writeFiles(files []outputFile) error {
	for _, file := range files {
		if err := os.WriteFile(file.path, file.content, outputFileMode); err != nil {
			return fmt.Errorf("write %s: %w", file.path, err)
		}
		fmt.Fprintf(os.Stderr, "// wrote %s (%d bytes)\n", file.path, len(file.content))
	}
	return nil
}
