// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

// Code generated by go run gen_kind_families.go. DO NOT EDIT.

package engine

import (
	"pipit.sh/pipit/internal/engine/program"
	"pipit.sh/pipit/internal/safeconv"
)

func fpDispatchStringString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(readStringArg(registers, site.Arguments[0]))
}

func fpDispatchStringInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(readStringArg(registers, site.Arguments[0])))
}

func fpDispatchStringBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(readStringArg(registers, site.Arguments[0]))
}

func fpDispatchStringRuneBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, int32) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(
		readStringArg(registers, site.Arguments[0]),
		safeconv.Int64ToInt32(readIntArg(registers, site.Arguments[1])),
	)
}

func fpDispatchStringRuneInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, int32) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(
		readStringArg(registers, site.Arguments[0]),
		safeconv.Int64ToInt32(readIntArg(registers, site.Arguments[1])),
	))
}

func fpDispatchString2Bool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, string) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(
		readStringArg(registers, site.Arguments[0]),
		readStringArg(registers, site.Arguments[1]),
	)
}

func fpDispatchString2String(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, string) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(
		readStringArg(registers, site.Arguments[0]),
		readStringArg(registers, site.Arguments[1]),
	)
}

func fpDispatchString2Int(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, string) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(
		readStringArg(registers, site.Arguments[0]),
		readStringArg(registers, site.Arguments[1]),
	))
}

func fpDispatchString3String(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, string, string) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(
		readStringArg(registers, site.Arguments[0]),
		readStringArg(registers, site.Arguments[1]),
		readStringArg(registers, site.Arguments[2]),
	)
}

func fpDispatchIntString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(int(readIntArg(registers, site.Arguments[0])))
}

func fpDispatchIntInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(int(readIntArg(registers, site.Arguments[0]))))
}

func fpDispatchIntBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(int(readIntArg(registers, site.Arguments[0])))
}

func fpDispatchInt2Int(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int, int) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(
		int(readIntArg(registers, site.Arguments[0])),
		int(readIntArg(registers, site.Arguments[1])),
	))
}

func fpDispatchInt2Bool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int, int) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(
		int(readIntArg(registers, site.Arguments[0])),
		int(readIntArg(registers, site.Arguments[1])),
	)
}

func fpDispatchInt2String(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int, int) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(
		int(readIntArg(registers, site.Arguments[0])),
		int(readIntArg(registers, site.Arguments[1])),
	)
}

func fpDispatchInt64IntString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int64, int) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(
		readIntArg(registers, site.Arguments[0]),
		int(readIntArg(registers, site.Arguments[1])),
	)
}

func fpDispatchFloat64Float64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(float64) float64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Floats[site.Returns[0].Register] = f(readFloatArg(registers, site.Arguments[0]))
}

func fpDispatchFloat642Float64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(float64, float64) float64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Floats[site.Returns[0].Register] = f(
		readFloatArg(registers, site.Arguments[0]),
		readFloatArg(registers, site.Arguments[1]),
	)
}

func fpDispatchAnyBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(any) bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f(readNativeAnyArg(vm, cached, site, registers, 0))
}

func fpDispatchAnyString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(any) string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f(readNativeAnyArg(vm, cached, site, registers, 0))
}

func fpDispatchAnyInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(any) int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f(readNativeAnyArg(vm, cached, site, registers, 0)))
}

func fpDispatchAnyInt64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(any) int64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = f(readNativeAnyArg(vm, cached, site, registers, 0))
}

func fpDispatchAnyFloat64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(any) float64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Floats[site.Returns[0].Register] = f(readNativeAnyArg(vm, cached, site, registers, 0))
}

func fpDispatchRetString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func() string)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Strings[site.Returns[0].Register] = f()
}

func fpDispatchRetBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func() bool)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Bools[site.Returns[0].Register] = f()
}

func fpDispatchRetInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func() int)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = int64(f())
}

func fpDispatchRetInt64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func() int64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Ints[site.Returns[0].Register] = f()
}

func fpDispatchRetFloat64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func() float64)
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	registers.Floats[site.Returns[0].Register] = f()
}

func fpDispatchVoid(vm *VM, cached any, _ *program.CallSite, _ *Registers) {
	f, ok := cached.(func())
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f()
}

func fpDispatchVoidString(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string))
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f(readStringArg(registers, site.Arguments[0]))
}

func fpDispatchVoidInt(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int))
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f(int(readIntArg(registers, site.Arguments[0])))
}

func fpDispatchVoidInt64(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(int64))
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f(readIntArg(registers, site.Arguments[0]))
}

func fpDispatchVoidBool(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(bool))
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f(readBoolArg(registers, site.Arguments[0]))
}

func fpDispatchVoidString2(vm *VM, cached any, site *program.CallSite, registers *Registers) {
	f, ok := cached.(func(string, string))
	if !ok {
		_ = RecordFastPathTypeMismatch(vm, -1, fastPathDispatcherTag, reflectTypeName(cached))
		return
	}

	f(
		readStringArg(registers, site.Arguments[0]),
		readStringArg(registers, site.Arguments[1]),
	)
}
