// Code generated by cmd/asmgen; DO NOT EDIT.

// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build !safe && !(js && wasm) && (amd64 || arm64)

package engine

var (
	asmJumpTable [opcodeTableSize]uintptr
)

//go:noescape
func dispatchLoop(ctx *dispatchContext)

//go:noescape
func initJumpTable(table *[opcodeTableSize]uintptr)

//go:noescape
func initSubOpJumpTables()

//go:noescape
func pathBFallback()

//go:noescape
func handlerLoadIntConst()

//go:noescape
func handlerLoadBool()

//go:noescape
func handlerAddInt()

//go:noescape
func handlerAddUint()

//go:noescape
func handlerSubUint()

//go:noescape
func handlerMulUint()

//go:noescape
func handlerBitAndUint()

//go:noescape
func handlerBitOrUint()

//go:noescape
func handlerBitXorUint()

//go:noescape
func handlerBitAndNotUint()

//go:noescape
func handlerShiftLeftUint()

//go:noescape
func handlerShiftRightUint()

//go:noescape
func handlerEqUint()

//go:noescape
func handlerNeUint()

//go:noescape
func handlerLtUint()

//go:noescape
func handlerLeUint()

//go:noescape
func handlerGtUint()

//go:noescape
func handlerGeUint()

//go:noescape
func handlerSubInt()

//go:noescape
func handlerMulInt()

//go:noescape
func handlerDivInt()

//go:noescape
func handlerRemInt()

//go:noescape
func handlerBitAnd()

//go:noescape
func handlerBitOr()

//go:noescape
func handlerBitXor()

//go:noescape
func handlerBitAndNot()

//go:noescape
func handlerShiftLeft()

//go:noescape
func handlerShiftRight()

//go:noescape
func handlerAddFloat()

//go:noescape
func handlerSubFloat()

//go:noescape
func handlerMulFloat()

//go:noescape
func handlerDivFloat()

//go:noescape
func handlerEqInt()

//go:noescape
func handlerNeInt()

//go:noescape
func handlerLtInt()

//go:noescape
func handlerLeInt()

//go:noescape
func handlerGtInt()

//go:noescape
func handlerGeInt()

//go:noescape
func handlerJump()

//go:noescape
func handlerJumpIfTrue()

//go:noescape
func handlerJumpIfFalse()

//go:noescape
func handlerCallExit()

//go:noescape
func handlerReturnExit()

//go:noescape
func handlerReturnVoidExit()

//go:noescape
func handlerTailCallExit()

//go:noescape
func handlerTailCallInlineSubroutine()

//go:noescape
func handlerCallInline()

//go:noescape
func handlerCallInlineSetupGeneralBank()

//go:noescape
func handlerCallInlineClearGeneralBank()

//go:noescape
func handlerReturnInline()

//go:noescape
func handlerReturnVoidInline()

//go:noescape
func handlerSubIntConst()

//go:noescape
func handlerAddIntConst()

//go:noescape
func handlerLeIntConstJumpFalse()

//go:noescape
func handlerLtIntConstJumpFalse()

//go:noescape
func handlerEqIntConstJumpFalse()

//go:noescape
func handlerEqIntConstJumpTrue()

//go:noescape
func handlerGeIntConstJumpFalse()

//go:noescape
func handlerGtIntConstJumpFalse()

//go:noescape
func handlerLtIntJumpFalse()

//go:noescape
func handlerLeIntJumpFalse()

//go:noescape
func handlerGtIntJumpFalse()

//go:noescape
func handlerGeIntJumpFalse()

//go:noescape
func handlerEqIntJumpFalse()

//go:noescape
func handlerNeIntJumpFalse()

//go:noescape
func handlerMulIntConst()

//go:noescape
func handlerAddIntJump()

//go:noescape
func handlerIncIntJumpLt()

//go:noescape
func handlerLoadIntConstSmall()

//go:noescape
func handlerLoadFloatConst()

//go:noescape
func handlerLoadStringConst()

//go:noescape
func handlerLoadBoolConst()

//go:noescape
func handlerEqFloat()

//go:noescape
func handlerNeFloat()

//go:noescape
func handlerLtFloat()

//go:noescape
func handlerLeFloat()

//go:noescape
func handlerGtFloat()

//go:noescape
func handlerGeFloat()

//go:noescape
func handlerStringIndex()

//go:noescape
func handlerEqString()

//go:noescape
func handlerNeString()

//go:noescape
func handlerSliceString()

//go:noescape
func handlerStringIndexToInt()

//go:noescape
func handlerLenStringLtJumpFalse()

//go:noescape
func handlerSubOpEqUintConstJumpFalse()

//go:noescape
func handlerSubOpLenSliceIntDirect()

//go:noescape
func handlerSubOpLenSliceFloatDirect()

//go:noescape
func handlerSubOpLenSliceStringDirect()

//go:noescape
func handlerSubOpLenSliceBoolDirect()

//go:noescape
func handlerSubOpLenSliceUintDirect()

//go:noescape
func handlerSubOpSliceGetFloatDirect()

//go:noescape
func handlerSubOpSliceSetFloatDirect()

//go:noescape
func handlerSubOpSliceGetUintDirect()

//go:noescape
func handlerSubOpSliceSetUintDirect()

//go:noescape
func handlerSubOpSliceGetBoolDirect()

//go:noescape
func handlerSubOpSliceSetBoolDirect()

//go:noescape
func handlerSubOpSliceGetStringDirect()

//go:noescape
func handlerSubOpRealComplex()

//go:noescape
func handlerSubOpImagComplex()

//go:noescape
func handlerSubOpMoveComplex()

//go:noescape
func handlerSubOpNegComplex()

//go:noescape
func handlerSubOpMoveInt()

//go:noescape
func handlerSubOpMoveFloat()

//go:noescape
func handlerSubOpMoveBool()

//go:noescape
func handlerSubOpMoveUint()

//go:noescape
func handlerSubOpMoveString()

//go:noescape
func handlerSubOpMoveSliceInt()

//go:noescape
func handlerSubOpMoveSliceFloat()

//go:noescape
func handlerSubOpMoveSliceString()

//go:noescape
func handlerSubOpMoveSliceBool()

//go:noescape
func handlerSubOpMoveSliceUint()

//go:noescape
func handlerSubOpMoveSliceByte()

//go:noescape
func handlerSubOpSliceSliceIntDirect()

//go:noescape
func handlerSubOpSliceSliceFloatDirect()

//go:noescape
func handlerSubOpSliceSliceStringDirect()

//go:noescape
func handlerSubOpSliceSliceBoolDirect()

//go:noescape
func handlerSubOpSliceSliceUintDirect()

//go:noescape
func handlerSubOpTier2IncInt()

//go:noescape
func handlerSubOpTier2DecInt()

//go:noescape
func handlerSubOpNegInt()

//go:noescape
func handlerSubOpNegFloat()

//go:noescape
func handlerSubOpBitNot()

//go:noescape
func handlerSubOpIntToFloat()

//go:noescape
func handlerSubOpFloatToInt()

//go:noescape
func handlerSubOpUintToFloat()

//go:noescape
func handlerSubOpFloatToUint()

//go:noescape
func handlerSubOpMathSqrt()

//go:noescape
func handlerSubOpMathAbs()

//go:noescape
func handlerSubOpMathFloor()

//go:noescape
func handlerSubOpMathCeil()

//go:noescape
func handlerSubOpMathTrunc()

//go:noescape
func handlerSubOpMathRound()

//go:noescape
func handlerSubOpLenString()

//go:noescape
func handlerSubOpMathSin()

//go:noescape
func handlerSubOpMathCos()

//go:noescape
func handlerSubOpMathExp()

//go:noescape
func handlerSubOpMathTan()

//go:noescape
func handlerSubOpMathMod()

//go:noescape
func handlerSubOpStrconvFormatBool()

//go:noescape
func handlerSubOpStrconvItoa()

//go:noescape
func handlerSubOpStrconvFormatInt()

//go:noescape
func handlerSubOpCap()

//go:noescape
func handlerSubOpBytesToString()

//go:noescape
func handlerSubOpBoxSliceInt()

//go:noescape
func handlerSubOpMakeSliceInt()

//go:noescape
func handlerSubOpMakeSliceFloat()

//go:noescape
func handlerSubOpMakeSliceString()

//go:noescape
func handlerSubOpMakeSliceBool()

//go:noescape
func handlerSubOpMakeSliceUint()

//go:noescape
func handlerSubOpMakeSliceByte()

//go:noescape
func handlerSubOpLenSliceByteDirect()

//go:noescape
func handlerSubOpSliceGetByteDirect()

//go:noescape
func handlerSubOpSliceSetByteDirect()

//go:noescape
func handlerSubOpSliceByteSlice()

//go:noescape
func handlerRangeNextSliceByte()

//go:noescape
func handlerSubOpIncStructFieldInt()

//go:noescape
func handlerSubOpDecStructFieldInt()

//go:noescape
func handlerSubOpIncStructFieldUint()

//go:noescape
func handlerSubOpDecStructFieldUint()

//go:noescape
func handlerSubOpRangeCheckUintJumpFalse()

//go:noescape
func handlerSubOpTier2IncUint()

//go:noescape
func handlerSubOpTier2DecUint()

func installDispatchTables() {
	installTier1Dispatcher()
	installTier2Dispatcher()
	installTier3Dispatcher()
	initSubOpJumpTables()
	installPerOpDirectExits()
	installFlatJumpTableASM()
	initOpNeedsGoFallback()
}
