// Code generated by 'pipit extract'. DO NOT EDIT.

package net

import (
	jsonrpc "net/rpc/jsonrpc"
	"reflect"
)

func init() {
	Symbols["net/rpc/jsonrpc"] = map[string]reflect.Value{"Dial": reflect.ValueOf(jsonrpc.Dial), "NewClient": reflect.ValueOf(jsonrpc.NewClient), "NewClientCodec": reflect.ValueOf(jsonrpc.NewClientCodec), "NewServerCodec": reflect.ValueOf(jsonrpc.NewServerCodec), "ServeConn": reflect.ValueOf(jsonrpc.ServeConn)}
}
