// Code generated by 'pipit extract'. DO NOT EDIT.

package net

import (
	fcgi "net/http/fcgi"
	"reflect"
)

func init() {
	Symbols["net/http/fcgi"] = map[string]reflect.Value{"ErrConnClosed": reflect.ValueOf(&fcgi.ErrConnClosed).Elem(), "ErrRequestAborted": reflect.ValueOf(&fcgi.ErrRequestAborted).Elem(), "ProcessEnv": reflect.ValueOf(fcgi.ProcessEnv), "Serve": reflect.ValueOf(fcgi.Serve)}
}
