// Code generated by 'pipit extract'. DO NOT EDIT.

package net

import (
	url "net/url"
	"reflect"
)

func init() {
	Symbols["net/url"] = map[string]reflect.Value{"Error": reflect.ValueOf((*url.Error)(nil)), "EscapeError": reflect.ValueOf((*url.EscapeError)(nil)), "InvalidHostError": reflect.ValueOf((*url.InvalidHostError)(nil)), "JoinPath": reflect.ValueOf(url.JoinPath), "Parse": reflect.ValueOf(url.Parse), "ParseQuery": reflect.ValueOf(url.ParseQuery), "ParseRequestURI": reflect.ValueOf(url.ParseRequestURI), "PathEscape": reflect.ValueOf(url.PathEscape), "PathUnescape": reflect.ValueOf(url.PathUnescape), "QueryEscape": reflect.ValueOf(url.QueryEscape), "QueryUnescape": reflect.ValueOf(url.QueryUnescape), "URL": reflect.ValueOf((*url.URL)(nil)), "User": reflect.ValueOf(url.User), "UserPassword": reflect.ValueOf(url.UserPassword), "Userinfo": reflect.ValueOf((*url.Userinfo)(nil)), "Values": reflect.ValueOf((*url.Values)(nil))}
}
