// Code generated by 'pipit extract'. DO NOT EDIT.

package net

import (
	httputil "net/http/httputil"
	"reflect"
)

func init() {
	Symbols["net/http/httputil"] = map[string]reflect.Value{"BufferPool": reflect.ValueOf((*httputil.BufferPool)(nil)), "ClientConn": reflect.ValueOf((*httputil.ClientConn)(nil)), "DumpRequest": reflect.ValueOf(httputil.DumpRequest), "DumpRequestOut": reflect.ValueOf(httputil.DumpRequestOut), "DumpResponse": reflect.ValueOf(httputil.DumpResponse), "ErrClosed": reflect.ValueOf(&httputil.ErrClosed).Elem(), "ErrLineTooLong": reflect.ValueOf(&httputil.ErrLineTooLong).Elem(), "ErrPersistEOF": reflect.ValueOf(&httputil.ErrPersistEOF).Elem(), "ErrPipeline": reflect.ValueOf(&httputil.ErrPipeline).Elem(), "NewChunkedReader": reflect.ValueOf(httputil.NewChunkedReader), "NewChunkedWriter": reflect.ValueOf(httputil.NewChunkedWriter), "NewClientConn": reflect.ValueOf(httputil.NewClientConn), "NewProxyClientConn": reflect.ValueOf(httputil.NewProxyClientConn), "NewServerConn": reflect.ValueOf(httputil.NewServerConn), "NewSingleHostReverseProxy": reflect.ValueOf(httputil.NewSingleHostReverseProxy), "ProxyRequest": reflect.ValueOf((*httputil.ProxyRequest)(nil)), "ReverseProxy": reflect.ValueOf((*httputil.ReverseProxy)(nil)), "ServerConn": reflect.ValueOf((*httputil.ServerConn)(nil))}
}
