// Code generated by 'pipit extract'. DO NOT EDIT.

package net

import (
	quotedprintable "mime/quotedprintable"
	"reflect"
)

func init() {
	Symbols["mime/quotedprintable"] = map[string]reflect.Value{"NewReader": reflect.ValueOf(quotedprintable.NewReader), "NewWriter": reflect.ValueOf(quotedprintable.NewWriter), "Reader": reflect.ValueOf((*quotedprintable.Reader)(nil)), "Writer": reflect.ValueOf((*quotedprintable.Writer)(nil))}
}
