// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CallSite struct {
	_tab flatbuffers.Table
}

func GetRootAsCallSite(buf []byte, offset flatbuffers.UOffsetT) *CallSite {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CallSite{}
	x.Init(buf, n+offset)
	return x
}

func FinishCallSiteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCallSite(buf []byte, offset flatbuffers.UOffsetT) *CallSite {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CallSite{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCallSiteBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CallSite) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CallSite) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CallSite) FunctionIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallSite) MutateFunctionIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(4, n)
}

func (rcv *CallSite) ClosureRegister() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallSite) MutateClosureRegister(n byte) bool {
	return rcv._tab.MutateByteSlot(6, n)
}

func (rcv *CallSite) NativeRegister() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallSite) MutateNativeRegister(n byte) bool {
	return rcv._tab.MutateByteSlot(8, n)
}

func (rcv *CallSite) IsClosure() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallSite) MutateIsClosure(n bool) bool {
	return rcv._tab.MutateBoolSlot(10, n)
}

func (rcv *CallSite) IsNative() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallSite) MutateIsNative(n bool) bool {
	return rcv._tab.MutateBoolSlot(12, n)
}

func (rcv *CallSite) IsMethod() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallSite) MutateIsMethod(n bool) bool {
	return rcv._tab.MutateBoolSlot(14, n)
}

func (rcv *CallSite) MethodReceiverRegister() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CallSite) MutateMethodReceiverRegister(n byte) bool {
	return rcv._tab.MutateByteSlot(16, n)
}

func (rcv *CallSite) Arguments(obj *VarLocation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CallSite) ArgumentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CallSite) Returns(obj *VarLocation, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *CallSite) ReturnsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *CallSite) IsEllipsisSpread() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallSite) MutateIsEllipsisSpread(n bool) bool {
	return rcv._tab.MutateBoolSlot(22, n)
}

func (rcv *CallSite) BlocksHostGoroutine() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CallSite) MutateBlocksHostGoroutine(n bool) bool {
	return rcv._tab.MutateBoolSlot(24, n)
}

func CallSiteStart(builder *flatbuffers.Builder) {
	builder.StartObject(11)
}
func CallSiteAddFunctionIndex(builder *flatbuffers.Builder, functionIndex uint16) {
	builder.PrependUint16Slot(0, functionIndex, 0)
}
func CallSiteAddClosureRegister(builder *flatbuffers.Builder, closureRegister byte) {
	builder.PrependByteSlot(1, closureRegister, 0)
}
func CallSiteAddNativeRegister(builder *flatbuffers.Builder, nativeRegister byte) {
	builder.PrependByteSlot(2, nativeRegister, 0)
}
func CallSiteAddIsClosure(builder *flatbuffers.Builder, isClosure bool) {
	builder.PrependBoolSlot(3, isClosure, false)
}
func CallSiteAddIsNative(builder *flatbuffers.Builder, isNative bool) {
	builder.PrependBoolSlot(4, isNative, false)
}
func CallSiteAddIsMethod(builder *flatbuffers.Builder, isMethod bool) {
	builder.PrependBoolSlot(5, isMethod, false)
}
func CallSiteAddMethodReceiverRegister(builder *flatbuffers.Builder, methodReceiverRegister byte) {
	builder.PrependByteSlot(6, methodReceiverRegister, 0)
}
func CallSiteAddArguments(builder *flatbuffers.Builder, arguments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(7, flatbuffers.UOffsetT(arguments), 0)
}
func CallSiteStartArgumentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CallSiteAddReturns(builder *flatbuffers.Builder, returns flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(8, flatbuffers.UOffsetT(returns), 0)
}
func CallSiteStartReturnsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func CallSiteAddIsEllipsisSpread(builder *flatbuffers.Builder, isEllipsisSpread bool) {
	builder.PrependBoolSlot(9, isEllipsisSpread, false)
}
func CallSiteAddBlocksHostGoroutine(builder *flatbuffers.Builder, blocksHostGoroutine bool) {
	builder.PrependBoolSlot(10, blocksHostGoroutine, false)
}
func CallSiteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
