// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ComplexValue struct {
	_tab flatbuffers.Struct
}

func (rcv *ComplexValue) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ComplexValue) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ComplexValue) Real() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ComplexValue) MutateReal(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ComplexValue) Imaginary() float64 {
	return rcv._tab.GetFloat64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ComplexValue) MutateImaginary(n float64) bool {
	return rcv._tab.MutateFloat64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateComplexValue(builder *flatbuffers.Builder, real float64, imaginary float64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependFloat64(imaginary)
	builder.PrependFloat64(real)
	return builder.Offset()
}
