// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import (
	"bytes"

	flatbuffers "github.com/google/flatbuffers/go"
)

type EntrypointEntry struct {
	_tab flatbuffers.Table
}

func GetRootAsEntrypointEntry(buf []byte, offset flatbuffers.UOffsetT) *EntrypointEntry {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &EntrypointEntry{}
	x.Init(buf, n+offset)
	return x
}

func FinishEntrypointEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsEntrypointEntry(buf []byte, offset flatbuffers.UOffsetT) *EntrypointEntry {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &EntrypointEntry{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedEntrypointEntryBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *EntrypointEntry) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *EntrypointEntry) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *EntrypointEntry) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func EntrypointEntryKeyCompare(o1, o2 flatbuffers.UOffsetT, buf []byte) bool {
	obj1 := &EntrypointEntry{}
	obj2 := &EntrypointEntry{}
	obj1.Init(buf, flatbuffers.UOffsetT(len(buf))-o1)
	obj2.Init(buf, flatbuffers.UOffsetT(len(buf))-o2)
	return string(obj1.Name()) < string(obj2.Name())
}

func (rcv *EntrypointEntry) LookupByKey(key string, vectorLocation flatbuffers.UOffsetT, buf []byte) bool {
	span := flatbuffers.GetUOffsetT(buf[vectorLocation-4:])
	start := flatbuffers.UOffsetT(0)
	bKey := []byte(key)
	for span != 0 {
		middle := span / 2
		tableOffset := flatbuffers.GetIndirectOffset(buf, vectorLocation+4*(start+middle))
		obj := &EntrypointEntry{}
		obj.Init(buf, tableOffset)
		comp := bytes.Compare(obj.Name(), bKey)
		if comp > 0 {
			span = middle
		} else if comp < 0 {
			middle += 1
			start += middle
			span -= middle
		} else {
			rcv.Init(buf, tableOffset)
			return true
		}
	}
	return false
}

func (rcv *EntrypointEntry) FunctionIndex() uint16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetUint16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *EntrypointEntry) MutateFunctionIndex(n uint16) bool {
	return rcv._tab.MutateUint16Slot(6, n)
}

func EntrypointEntryStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func EntrypointEntryAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func EntrypointEntryAddFunctionIndex(builder *flatbuffers.Builder, functionIndex uint16) {
	builder.PrependUint16Slot(1, functionIndex, 0)
}
func EntrypointEntryEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
