// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Instruction struct {
	_tab flatbuffers.Struct
}

func (rcv *Instruction) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Instruction) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Instruction) Opcode() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Instruction) MutateOpcode(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *Instruction) A() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(1))
}
func (rcv *Instruction) MutateA(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(1), n)
}

func (rcv *Instruction) B() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(2))
}
func (rcv *Instruction) MutateB(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(2), n)
}

func (rcv *Instruction) C() byte {
	return rcv._tab.GetByte(rcv._tab.Pos + flatbuffers.UOffsetT(3))
}
func (rcv *Instruction) MutateC(n byte) bool {
	return rcv._tab.MutateByte(rcv._tab.Pos+flatbuffers.UOffsetT(3), n)
}

func CreateInstruction(builder *flatbuffers.Builder, opcode byte, a byte, b byte, c byte) flatbuffers.UOffsetT {
	builder.Prep(1, 4)
	builder.PrependByte(c)
	builder.PrependByte(b)
	builder.PrependByte(a)
	builder.PrependByte(opcode)
	return builder.Offset()
}
