// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import "strconv"

type RegisterKind int8

const (
	RegisterKindInt         RegisterKind = 0
	RegisterKindFloat       RegisterKind = 1
	RegisterKindString      RegisterKind = 2
	RegisterKindGeneral     RegisterKind = 3
	RegisterKindBool        RegisterKind = 4
	RegisterKindUint        RegisterKind = 5
	RegisterKindComplex     RegisterKind = 6
	RegisterKindSliceInt    RegisterKind = 7
	RegisterKindSliceFloat  RegisterKind = 8
	RegisterKindSliceString RegisterKind = 9
	RegisterKindSliceBool   RegisterKind = 10
	RegisterKindSliceUint   RegisterKind = 11
	RegisterKindSliceByte   RegisterKind = 12
)

var EnumNamesRegisterKind = map[RegisterKind]string{
	RegisterKindInt:         "Int",
	RegisterKindFloat:       "Float",
	RegisterKindString:      "String",
	RegisterKindGeneral:     "General",
	RegisterKindBool:        "Bool",
	RegisterKindUint:        "Uint",
	RegisterKindComplex:     "Complex",
	RegisterKindSliceInt:    "SliceInt",
	RegisterKindSliceFloat:  "SliceFloat",
	RegisterKindSliceString: "SliceString",
	RegisterKindSliceBool:   "SliceBool",
	RegisterKindSliceUint:   "SliceUint",
	RegisterKindSliceByte:   "SliceByte",
}

var EnumValuesRegisterKind = map[string]RegisterKind{
	"Int":         RegisterKindInt,
	"Float":       RegisterKindFloat,
	"String":      RegisterKindString,
	"General":     RegisterKindGeneral,
	"Bool":        RegisterKindBool,
	"Uint":        RegisterKindUint,
	"Complex":     RegisterKindComplex,
	"SliceInt":    RegisterKindSliceInt,
	"SliceFloat":  RegisterKindSliceFloat,
	"SliceString": RegisterKindSliceString,
	"SliceBool":   RegisterKindSliceBool,
	"SliceUint":   RegisterKindSliceUint,
	"SliceByte":   RegisterKindSliceByte,
}

func (v RegisterKind) String() string {
	if s, ok := EnumNamesRegisterKind[v]; ok {
		return s
	}
	return "RegisterKind(" + strconv.FormatInt(int64(v), 10) + ")"
}
