// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package schemagen

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypeDescriptor struct {
	_tab flatbuffers.Table
}

func GetRootAsTypeDescriptor(buf []byte, offset flatbuffers.UOffsetT) *TypeDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypeDescriptor{}
	x.Init(buf, n+offset)
	return x
}

func FinishTypeDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsTypeDescriptor(buf []byte, offset flatbuffers.UOffsetT) *TypeDescriptor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypeDescriptor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedTypeDescriptorBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *TypeDescriptor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypeDescriptor) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TypeDescriptor) Kind() TypeDescKind {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return TypeDescKind(rcv._tab.GetInt8(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *TypeDescriptor) MutateKind(n TypeDescKind) bool {
	return rcv._tab.MutateInt8Slot(4, int8(n))
}

func (rcv *TypeDescriptor) PackagePath() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeDescriptor) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *TypeDescriptor) BasicKind() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TypeDescriptor) MutateBasicKind(n byte) bool {
	return rcv._tab.MutateByteSlot(10, n)
}

func (rcv *TypeDescriptor) Element(obj *TypeDescriptor) *TypeDescriptor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeDescriptor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TypeDescriptor) Key(obj *TypeDescriptor) *TypeDescriptor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeDescriptor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TypeDescriptor) Value(obj *TypeDescriptor) *TypeDescriptor {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(16))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(TypeDescriptor)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *TypeDescriptor) Length() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(18))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TypeDescriptor) MutateLength(n int32) bool {
	return rcv._tab.MutateInt32Slot(18, n)
}

func (rcv *TypeDescriptor) Direction() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(20))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TypeDescriptor) MutateDirection(n int32) bool {
	return rcv._tab.MutateInt32Slot(20, n)
}

func (rcv *TypeDescriptor) Fields(obj *TypeDescField, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TypeDescriptor) FieldsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(22))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TypeDescriptor) Params(obj *TypeDescriptor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TypeDescriptor) ParamsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(24))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TypeDescriptor) Results(obj *TypeDescriptor, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *TypeDescriptor) ResultsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(26))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *TypeDescriptor) IsVariadic() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(28))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *TypeDescriptor) MutateIsVariadic(n bool) bool {
	return rcv._tab.MutateBoolSlot(28, n)
}

func TypeDescriptorStart(builder *flatbuffers.Builder) {
	builder.StartObject(13)
}
func TypeDescriptorAddKind(builder *flatbuffers.Builder, kind TypeDescKind) {
	builder.PrependInt8Slot(0, int8(kind), 0)
}
func TypeDescriptorAddPackagePath(builder *flatbuffers.Builder, packagePath flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(packagePath), 0)
}
func TypeDescriptorAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(name), 0)
}
func TypeDescriptorAddBasicKind(builder *flatbuffers.Builder, basicKind byte) {
	builder.PrependByteSlot(3, basicKind, 0)
}
func TypeDescriptorAddElement(builder *flatbuffers.Builder, element flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(element), 0)
}
func TypeDescriptorAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(key), 0)
}
func TypeDescriptorAddValue(builder *flatbuffers.Builder, value flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(6, flatbuffers.UOffsetT(value), 0)
}
func TypeDescriptorAddLength(builder *flatbuffers.Builder, length int32) {
	builder.PrependInt32Slot(7, length, 0)
}
func TypeDescriptorAddDirection(builder *flatbuffers.Builder, direction int32) {
	builder.PrependInt32Slot(8, direction, 0)
}
func TypeDescriptorAddFields(builder *flatbuffers.Builder, fields flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(9, flatbuffers.UOffsetT(fields), 0)
}
func TypeDescriptorStartFieldsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TypeDescriptorAddParams(builder *flatbuffers.Builder, params flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(10, flatbuffers.UOffsetT(params), 0)
}
func TypeDescriptorStartParamsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TypeDescriptorAddResults(builder *flatbuffers.Builder, results flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(11, flatbuffers.UOffsetT(results), 0)
}
func TypeDescriptorStartResultsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func TypeDescriptorAddIsVariadic(builder *flatbuffers.Builder, isVariadic bool) {
	builder.PrependBoolSlot(12, isVariadic, false)
}
func TypeDescriptorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
