// Copyright 2026 PolitePixels Limited
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This project stands against fascism, authoritarianism, and all forms of
// oppression. We built this to empower people, not to enable those who would
// strip others of their rights and dignity.

//go:build integration

package selfhost_test

import (
	"fmt"
	"runtime"
	"strings"
	"time"

	"pipit.sh/pipit/internal/debug"
	"pipit.sh/pipit/internal/engine/program"
)

const differenceContext = 3

type summary struct {
	setup                         time.Duration
	total                         time.Duration
	nativeTotal, interpretedTotal time.Duration
	cases                         int
	compared                      int
	identical                     int
	mismatched                    int
	interpretedFailed             int
	nativeFailed                  int
	unparsed                      int
}

func summarise(results []caseResult, setup, total time.Duration) summary {
	s := summary{setup: setup, total: total, nativeTotal: 0, interpretedTotal: 0,
		cases: len(results), compared: 0, identical: 0, mismatched: 0, interpretedFailed: 0, nativeFailed: 0, unparsed: 0}
	for _, result := range results {
		switch result.outcome {
		case outcomeIdentical:
			s.identical++
			s.compared++
			s.nativeTotal += result.nativeTime
			s.interpretedTotal += result.interpretedTime
		case outcomeMismatch:
			s.mismatched++
			s.compared++
			s.nativeTotal += result.nativeTime
			s.interpretedTotal += result.interpretedTime
		case outcomeInterpreted:
			s.interpretedFailed++
			s.compared++
		case outcomeNativeFailed:
			s.nativeFailed++
		case outcomeUnparsed:
			s.unparsed++
		}
	}
	return s
}

func (s summary) String() string {
	var builder strings.Builder
	fmt.Fprintf(&builder, "selfhost: %d programs, %d compared, %d identical, %d mismatched, %d interpreted failures, %d native failures, %d unparsed\n",
		s.cases, s.compared, s.identical, s.mismatched, s.interpretedFailed, s.nativeFailed, s.unparsed)
	fmt.Fprintf(&builder, "selfhost: setup %s, total %s, native compile %s, interpreted compile %s (%s)\n",
		s.setup.Round(time.Millisecond), s.total.Round(time.Millisecond), s.nativeTotal.Round(time.Millisecond),
		s.interpretedTotal.Round(time.Millisecond), slowdown(s.nativeTotal, s.interpretedTotal))
	return builder.String()
}

func slowdown(native, interpreted time.Duration) string {
	if native <= 0 {
		return "n/a"
	}
	return fmt.Sprintf("%.1fx slower", float64(interpreted)/float64(native))
}

func renderReport(s summary, results []caseResult) string {
	var b strings.Builder
	b.WriteString("# Self-hosting report\n\n")
	b.WriteString("pipit's compiler (`internal/compile`) run under pipit, compiling the snippet corpus, compared\n")
	b.WriteString("byte for byte against the native compiler's output. Generated by `make test-integration`.\n\n")
	fmt.Fprintf(&b, "- Date: %s\n- Go: %s\n", time.Now().UTC().Format(time.RFC3339), runtime.Version())
	fmt.Fprintf(&b, "- Programs: %d (compared %d, native failures %d, unparsed %d)\n", s.cases, s.compared, s.nativeFailed, s.unparsed)
	fmt.Fprintf(&b, "- Identical: %d of %d compared\n- Mismatched: %d\n- Interpreted compile failures: %d\n",
		s.identical, s.compared, s.mismatched, s.interpretedFailed)
	fmt.Fprintf(&b, "- Set-up (compiler loaded under the interpreter): %s\n", s.setup.Round(time.Millisecond))
	fmt.Fprintf(&b, "- Compile time: native %s, interpreted %s (%s)\n\n",
		s.nativeTotal.Round(time.Millisecond), s.interpretedTotal.Round(time.Millisecond), slowdown(s.nativeTotal, s.interpretedTotal))
	writeSection(&b, "Mismatches", results, outcomeMismatch)
	writeSection(&b, "Interpreted compile failures", results, outcomeInterpreted)
	writeSection(&b, "Native compile failures (not compared)", results, outcomeNativeFailed)
	writeSection(&b, "Unparsed", results, outcomeUnparsed)
	return b.String()
}

func writeSection(b *strings.Builder, title string, results []caseResult, outcome caseOutcome) {
	var selected []caseResult
	for _, result := range results {
		if result.outcome == outcome {
			selected = append(selected, result)
		}
	}
	fmt.Fprintf(b, "## %s (%d)\n\n", title, len(selected))
	if len(selected) == 0 {
		b.WriteString("None.\n\n")
		return
	}
	for _, result := range selected {
		fmt.Fprintf(b, "### %s\n\n```\n%s\n```\n\n", result.name, strings.TrimSpace(result.detail))
	}
}

func disassemble(fileSet *program.CompiledFileSet) string {
	return debug.DisassembleAssembly(fileSet)
}

func firstDifference(native, interpreted string) string {
	nativeLines := strings.Split(native, "\n")
	interpretedLines := strings.Split(interpreted, "\n")
	for i := 0; i < len(nativeLines) || i < len(interpretedLines); i++ {
		if i < len(nativeLines) && i < len(interpretedLines) && nativeLines[i] == interpretedLines[i] {
			continue
		}
		start := max(i-differenceContext, 0)
		var b strings.Builder
		fmt.Fprintf(&b, "first difference at listing line %d\n--- native\n%s\n--- interpreted\n%s",
			i+1, strings.Join(excerpt(nativeLines, start, i), "\n"), strings.Join(excerpt(interpretedLines, start, i), "\n"))
		return b.String()
	}
	return "the listings agree; the packed bytes differ in metadata"
}

func excerpt(lines []string, start, end int) []string {
	stop := min(end+differenceContext+1, len(lines))
	if start >= len(lines) {
		return nil
	}
	return lines[start:stop]
}
