// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	ring "container/ring"
	"reflect"
)

func init() {
	Symbols["container/ring"] = map[string]reflect.Value{"New": reflect.ValueOf(ring.New), "Ring": reflect.ValueOf((*ring.Ring)(nil))}
}
