// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	rand "math/rand/v2"
	"reflect"
)

func init() {
	Symbols["math/rand/v2"] = map[string]reflect.Value{"ChaCha8": reflect.ValueOf((*rand.ChaCha8)(nil)), "ExpFloat64": reflect.ValueOf(rand.ExpFloat64), "Float32": reflect.ValueOf(rand.Float32), "Float64": reflect.ValueOf(rand.Float64), "Int": reflect.ValueOf(rand.Int), "Int32": reflect.ValueOf(rand.Int32), "Int32N": reflect.ValueOf(rand.Int32N), "Int64": reflect.ValueOf(rand.Int64), "Int64N": reflect.ValueOf(rand.Int64N), "IntN": reflect.ValueOf(rand.IntN), "New": reflect.ValueOf(rand.New), "NewChaCha8": reflect.ValueOf(rand.NewChaCha8), "NewPCG": reflect.ValueOf(rand.NewPCG), "NewZipf": reflect.ValueOf(rand.NewZipf), "NormFloat64": reflect.ValueOf(rand.NormFloat64), "PCG": reflect.ValueOf((*rand.PCG)(nil)), "Perm": reflect.ValueOf(rand.Perm), "Rand": reflect.ValueOf((*rand.Rand)(nil)), "Shuffle": reflect.ValueOf(rand.Shuffle), "Source": reflect.ValueOf((*rand.Source)(nil)), "Uint": reflect.ValueOf(rand.Uint), "Uint32": reflect.ValueOf(rand.Uint32), "Uint32N": reflect.ValueOf(rand.Uint32N), "Uint64": reflect.ValueOf(rand.Uint64), "Uint64N": reflect.ValueOf(rand.Uint64N), "UintN": reflect.ValueOf(rand.UintN), "Zipf": reflect.ValueOf((*rand.Zipf)(nil))}
}
