// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	"reflect"
	utf16 "unicode/utf16"
)

func init() {
	Symbols["unicode/utf16"] = map[string]reflect.Value{"AppendRune": reflect.ValueOf(utf16.AppendRune), "Decode": reflect.ValueOf(utf16.Decode), "DecodeRune": reflect.ValueOf(utf16.DecodeRune), "Encode": reflect.ValueOf(utf16.Encode), "EncodeRune": reflect.ValueOf(utf16.EncodeRune), "IsSurrogate": reflect.ValueOf(utf16.IsSurrogate), "RuneLen": reflect.ValueOf(utf16.RuneLen)}
}
