// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	"maps"
	"reflect"
)

func wrappedMapsAll(m any) any {
	switch typedArg := m.(type) {
	case map[string]string:
		return maps.All(typedArg)
	case map[string]int:
		return maps.All(typedArg)
	case map[string]int32:
		return maps.All(typedArg)
	case map[string]int64:
		return maps.All(typedArg)
	case map[string]float64:
		return maps.All(typedArg)
	case map[string]bool:
		return maps.All(typedArg)
	case map[string]any:
		return maps.All(typedArg)
	case map[int]string:
		return maps.All(typedArg)
	case map[int]int:
		return maps.All(typedArg)
	case map[int]int32:
		return maps.All(typedArg)
	case map[int]int64:
		return maps.All(typedArg)
	case map[int]float64:
		return maps.All(typedArg)
	case map[int]bool:
		return maps.All(typedArg)
	case map[int]any:
		return maps.All(typedArg)
	case map[int32]string:
		return maps.All(typedArg)
	case map[int32]int:
		return maps.All(typedArg)
	case map[int32]int32:
		return maps.All(typedArg)
	case map[int32]int64:
		return maps.All(typedArg)
	case map[int32]float64:
		return maps.All(typedArg)
	case map[int32]bool:
		return maps.All(typedArg)
	case map[int32]any:
		return maps.All(typedArg)
	case map[int64]string:
		return maps.All(typedArg)
	case map[int64]int:
		return maps.All(typedArg)
	case map[int64]int32:
		return maps.All(typedArg)
	case map[int64]int64:
		return maps.All(typedArg)
	case map[int64]float64:
		return maps.All(typedArg)
	case map[int64]bool:
		return maps.All(typedArg)
	case map[int64]any:
		return maps.All(typedArg)
	default:
		return reflectMapsAll(m)
	}
}
func wrappedMapsClone(m any) any {
	switch typedArg := m.(type) {
	case map[string]string:
		return maps.Clone(typedArg)
	case map[string]int:
		return maps.Clone(typedArg)
	case map[string]int32:
		return maps.Clone(typedArg)
	case map[string]int64:
		return maps.Clone(typedArg)
	case map[string]float64:
		return maps.Clone(typedArg)
	case map[string]bool:
		return maps.Clone(typedArg)
	case map[string]any:
		return maps.Clone(typedArg)
	case map[int]string:
		return maps.Clone(typedArg)
	case map[int]int:
		return maps.Clone(typedArg)
	case map[int]int32:
		return maps.Clone(typedArg)
	case map[int]int64:
		return maps.Clone(typedArg)
	case map[int]float64:
		return maps.Clone(typedArg)
	case map[int]bool:
		return maps.Clone(typedArg)
	case map[int]any:
		return maps.Clone(typedArg)
	case map[int32]string:
		return maps.Clone(typedArg)
	case map[int32]int:
		return maps.Clone(typedArg)
	case map[int32]int32:
		return maps.Clone(typedArg)
	case map[int32]int64:
		return maps.Clone(typedArg)
	case map[int32]float64:
		return maps.Clone(typedArg)
	case map[int32]bool:
		return maps.Clone(typedArg)
	case map[int32]any:
		return maps.Clone(typedArg)
	case map[int64]string:
		return maps.Clone(typedArg)
	case map[int64]int:
		return maps.Clone(typedArg)
	case map[int64]int32:
		return maps.Clone(typedArg)
	case map[int64]int64:
		return maps.Clone(typedArg)
	case map[int64]float64:
		return maps.Clone(typedArg)
	case map[int64]bool:
		return maps.Clone(typedArg)
	case map[int64]any:
		return maps.Clone(typedArg)
	default:
		return reflectMapsClone(m)
	}
}
func wrappedMapsCopy(dst any, src any) {
	switch typedArg := dst.(type) {
	case map[string]string:
		maps.Copy(typedArg, src.(map[string]string))
	case map[string]int:
		maps.Copy(typedArg, src.(map[string]int))
	case map[string]int32:
		maps.Copy(typedArg, src.(map[string]int32))
	case map[string]int64:
		maps.Copy(typedArg, src.(map[string]int64))
	case map[string]float64:
		maps.Copy(typedArg, src.(map[string]float64))
	case map[string]bool:
		maps.Copy(typedArg, src.(map[string]bool))
	case map[string]any:
		maps.Copy(typedArg, src.(map[string]any))
	case map[int]string:
		maps.Copy(typedArg, src.(map[int]string))
	case map[int]int:
		maps.Copy(typedArg, src.(map[int]int))
	case map[int]int32:
		maps.Copy(typedArg, src.(map[int]int32))
	case map[int]int64:
		maps.Copy(typedArg, src.(map[int]int64))
	case map[int]float64:
		maps.Copy(typedArg, src.(map[int]float64))
	case map[int]bool:
		maps.Copy(typedArg, src.(map[int]bool))
	case map[int]any:
		maps.Copy(typedArg, src.(map[int]any))
	case map[int32]string:
		maps.Copy(typedArg, src.(map[int32]string))
	case map[int32]int:
		maps.Copy(typedArg, src.(map[int32]int))
	case map[int32]int32:
		maps.Copy(typedArg, src.(map[int32]int32))
	case map[int32]int64:
		maps.Copy(typedArg, src.(map[int32]int64))
	case map[int32]float64:
		maps.Copy(typedArg, src.(map[int32]float64))
	case map[int32]bool:
		maps.Copy(typedArg, src.(map[int32]bool))
	case map[int32]any:
		maps.Copy(typedArg, src.(map[int32]any))
	case map[int64]string:
		maps.Copy(typedArg, src.(map[int64]string))
	case map[int64]int:
		maps.Copy(typedArg, src.(map[int64]int))
	case map[int64]int32:
		maps.Copy(typedArg, src.(map[int64]int32))
	case map[int64]int64:
		maps.Copy(typedArg, src.(map[int64]int64))
	case map[int64]float64:
		maps.Copy(typedArg, src.(map[int64]float64))
	case map[int64]bool:
		maps.Copy(typedArg, src.(map[int64]bool))
	case map[int64]any:
		maps.Copy(typedArg, src.(map[int64]any))
	default:
		reflectMapsCopy(dst, src)
		return
	}
}
func wrappedMapsDeleteFunc(m any, del func(p0 any, p1 any) bool) {
	switch typedArg := m.(type) {
	case map[string]string:
		maps.DeleteFunc(typedArg, func(p0 string, p1 string) bool {
			return del(p0, p1)
		})
	case map[string]int:
		maps.DeleteFunc(typedArg, func(p0 string, p1 int) bool {
			return del(p0, p1)
		})
	case map[string]int32:
		maps.DeleteFunc(typedArg, func(p0 string, p1 int32) bool {
			return del(p0, p1)
		})
	case map[string]int64:
		maps.DeleteFunc(typedArg, func(p0 string, p1 int64) bool {
			return del(p0, p1)
		})
	case map[string]float64:
		maps.DeleteFunc(typedArg, func(p0 string, p1 float64) bool {
			return del(p0, p1)
		})
	case map[string]bool:
		maps.DeleteFunc(typedArg, func(p0 string, p1 bool) bool {
			return del(p0, p1)
		})
	case map[string]any:
		maps.DeleteFunc(typedArg, func(p0 string, p1 any) bool {
			return del(p0, p1)
		})
	case map[int]string:
		maps.DeleteFunc(typedArg, func(p0 int, p1 string) bool {
			return del(p0, p1)
		})
	case map[int]int:
		maps.DeleteFunc(typedArg, func(p0 int, p1 int) bool {
			return del(p0, p1)
		})
	case map[int]int32:
		maps.DeleteFunc(typedArg, func(p0 int, p1 int32) bool {
			return del(p0, p1)
		})
	case map[int]int64:
		maps.DeleteFunc(typedArg, func(p0 int, p1 int64) bool {
			return del(p0, p1)
		})
	case map[int]float64:
		maps.DeleteFunc(typedArg, func(p0 int, p1 float64) bool {
			return del(p0, p1)
		})
	case map[int]bool:
		maps.DeleteFunc(typedArg, func(p0 int, p1 bool) bool {
			return del(p0, p1)
		})
	case map[int]any:
		maps.DeleteFunc(typedArg, func(p0 int, p1 any) bool {
			return del(p0, p1)
		})
	case map[int32]string:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 string) bool {
			return del(p0, p1)
		})
	case map[int32]int:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 int) bool {
			return del(p0, p1)
		})
	case map[int32]int32:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 int32) bool {
			return del(p0, p1)
		})
	case map[int32]int64:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 int64) bool {
			return del(p0, p1)
		})
	case map[int32]float64:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 float64) bool {
			return del(p0, p1)
		})
	case map[int32]bool:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 bool) bool {
			return del(p0, p1)
		})
	case map[int32]any:
		maps.DeleteFunc(typedArg, func(p0 int32, p1 any) bool {
			return del(p0, p1)
		})
	case map[int64]string:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 string) bool {
			return del(p0, p1)
		})
	case map[int64]int:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 int) bool {
			return del(p0, p1)
		})
	case map[int64]int32:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 int32) bool {
			return del(p0, p1)
		})
	case map[int64]int64:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 int64) bool {
			return del(p0, p1)
		})
	case map[int64]float64:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 float64) bool {
			return del(p0, p1)
		})
	case map[int64]bool:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 bool) bool {
			return del(p0, p1)
		})
	case map[int64]any:
		maps.DeleteFunc(typedArg, func(p0 int64, p1 any) bool {
			return del(p0, p1)
		})
	default:
		reflectMapsDeleteFunc(m, del)
		return
	}
}
func wrappedMapsEqual(m1 any, m2 any) bool {
	switch typedArg := m1.(type) {
	case map[string]string:
		return maps.Equal(typedArg, m2.(map[string]string))
	case map[string]int:
		return maps.Equal(typedArg, m2.(map[string]int))
	case map[string]int32:
		return maps.Equal(typedArg, m2.(map[string]int32))
	case map[string]int64:
		return maps.Equal(typedArg, m2.(map[string]int64))
	case map[string]float64:
		return maps.Equal(typedArg, m2.(map[string]float64))
	case map[string]bool:
		return maps.Equal(typedArg, m2.(map[string]bool))
	case map[string]any:
		return maps.Equal(typedArg, m2.(map[string]any))
	case map[int]string:
		return maps.Equal(typedArg, m2.(map[int]string))
	case map[int]int:
		return maps.Equal(typedArg, m2.(map[int]int))
	case map[int]int32:
		return maps.Equal(typedArg, m2.(map[int]int32))
	case map[int]int64:
		return maps.Equal(typedArg, m2.(map[int]int64))
	case map[int]float64:
		return maps.Equal(typedArg, m2.(map[int]float64))
	case map[int]bool:
		return maps.Equal(typedArg, m2.(map[int]bool))
	case map[int]any:
		return maps.Equal(typedArg, m2.(map[int]any))
	case map[int32]string:
		return maps.Equal(typedArg, m2.(map[int32]string))
	case map[int32]int:
		return maps.Equal(typedArg, m2.(map[int32]int))
	case map[int32]int32:
		return maps.Equal(typedArg, m2.(map[int32]int32))
	case map[int32]int64:
		return maps.Equal(typedArg, m2.(map[int32]int64))
	case map[int32]float64:
		return maps.Equal(typedArg, m2.(map[int32]float64))
	case map[int32]bool:
		return maps.Equal(typedArg, m2.(map[int32]bool))
	case map[int32]any:
		return maps.Equal(typedArg, m2.(map[int32]any))
	case map[int64]string:
		return maps.Equal(typedArg, m2.(map[int64]string))
	case map[int64]int:
		return maps.Equal(typedArg, m2.(map[int64]int))
	case map[int64]int32:
		return maps.Equal(typedArg, m2.(map[int64]int32))
	case map[int64]int64:
		return maps.Equal(typedArg, m2.(map[int64]int64))
	case map[int64]float64:
		return maps.Equal(typedArg, m2.(map[int64]float64))
	case map[int64]bool:
		return maps.Equal(typedArg, m2.(map[int64]bool))
	case map[int64]any:
		return maps.Equal(typedArg, m2.(map[int64]any))
	default:
		return reflectMapsEqual(m1, m2)
	}
}
func wrappedMapsEqualFunc(m1 any, m2 any, eq func(p0 any, p1 any) bool) bool {
	switch typedArg := m1.(type) {
	case map[string]string:
		return maps.EqualFunc(typedArg, m2.(map[string]string), func(p0 string, p1 string) bool {
			return eq(p0, p1)
		})
	case map[string]int:
		return maps.EqualFunc(typedArg, m2.(map[string]int), func(p0 int, p1 int) bool {
			return eq(p0, p1)
		})
	case map[string]int32:
		return maps.EqualFunc(typedArg, m2.(map[string]int32), func(p0 int32, p1 int32) bool {
			return eq(p0, p1)
		})
	case map[string]int64:
		return maps.EqualFunc(typedArg, m2.(map[string]int64), func(p0 int64, p1 int64) bool {
			return eq(p0, p1)
		})
	case map[string]float64:
		return maps.EqualFunc(typedArg, m2.(map[string]float64), func(p0 float64, p1 float64) bool {
			return eq(p0, p1)
		})
	case map[string]bool:
		return maps.EqualFunc(typedArg, m2.(map[string]bool), func(p0 bool, p1 bool) bool {
			return eq(p0, p1)
		})
	case map[string]any:
		return maps.EqualFunc(typedArg, m2.(map[string]any), func(p0 any, p1 any) bool {
			return eq(p0, p1)
		})
	case map[int]string:
		return maps.EqualFunc(typedArg, m2.(map[int]string), func(p0 string, p1 string) bool {
			return eq(p0, p1)
		})
	case map[int]int:
		return maps.EqualFunc(typedArg, m2.(map[int]int), func(p0 int, p1 int) bool {
			return eq(p0, p1)
		})
	case map[int]int32:
		return maps.EqualFunc(typedArg, m2.(map[int]int32), func(p0 int32, p1 int32) bool {
			return eq(p0, p1)
		})
	case map[int]int64:
		return maps.EqualFunc(typedArg, m2.(map[int]int64), func(p0 int64, p1 int64) bool {
			return eq(p0, p1)
		})
	case map[int]float64:
		return maps.EqualFunc(typedArg, m2.(map[int]float64), func(p0 float64, p1 float64) bool {
			return eq(p0, p1)
		})
	case map[int]bool:
		return maps.EqualFunc(typedArg, m2.(map[int]bool), func(p0 bool, p1 bool) bool {
			return eq(p0, p1)
		})
	case map[int]any:
		return maps.EqualFunc(typedArg, m2.(map[int]any), func(p0 any, p1 any) bool {
			return eq(p0, p1)
		})
	case map[int32]string:
		return maps.EqualFunc(typedArg, m2.(map[int32]string), func(p0 string, p1 string) bool {
			return eq(p0, p1)
		})
	case map[int32]int:
		return maps.EqualFunc(typedArg, m2.(map[int32]int), func(p0 int, p1 int) bool {
			return eq(p0, p1)
		})
	case map[int32]int32:
		return maps.EqualFunc(typedArg, m2.(map[int32]int32), func(p0 int32, p1 int32) bool {
			return eq(p0, p1)
		})
	case map[int32]int64:
		return maps.EqualFunc(typedArg, m2.(map[int32]int64), func(p0 int64, p1 int64) bool {
			return eq(p0, p1)
		})
	case map[int32]float64:
		return maps.EqualFunc(typedArg, m2.(map[int32]float64), func(p0 float64, p1 float64) bool {
			return eq(p0, p1)
		})
	case map[int32]bool:
		return maps.EqualFunc(typedArg, m2.(map[int32]bool), func(p0 bool, p1 bool) bool {
			return eq(p0, p1)
		})
	case map[int32]any:
		return maps.EqualFunc(typedArg, m2.(map[int32]any), func(p0 any, p1 any) bool {
			return eq(p0, p1)
		})
	case map[int64]string:
		return maps.EqualFunc(typedArg, m2.(map[int64]string), func(p0 string, p1 string) bool {
			return eq(p0, p1)
		})
	case map[int64]int:
		return maps.EqualFunc(typedArg, m2.(map[int64]int), func(p0 int, p1 int) bool {
			return eq(p0, p1)
		})
	case map[int64]int32:
		return maps.EqualFunc(typedArg, m2.(map[int64]int32), func(p0 int32, p1 int32) bool {
			return eq(p0, p1)
		})
	case map[int64]int64:
		return maps.EqualFunc(typedArg, m2.(map[int64]int64), func(p0 int64, p1 int64) bool {
			return eq(p0, p1)
		})
	case map[int64]float64:
		return maps.EqualFunc(typedArg, m2.(map[int64]float64), func(p0 float64, p1 float64) bool {
			return eq(p0, p1)
		})
	case map[int64]bool:
		return maps.EqualFunc(typedArg, m2.(map[int64]bool), func(p0 bool, p1 bool) bool {
			return eq(p0, p1)
		})
	case map[int64]any:
		return maps.EqualFunc(typedArg, m2.(map[int64]any), func(p0 any, p1 any) bool {
			return eq(p0, p1)
		})
	default:
		return reflectMapsEqualFunc(m1, m2, eq)
	}
}
func wrappedMapsInsert(m any, seq func(yield func(k any, v any) bool)) {
	switch typedArg := m.(type) {
	case map[string]string:
		maps.Insert(typedArg, func(yield func(k string, v string) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[string](v))
			})
		})
	case map[string]int:
		maps.Insert(typedArg, func(yield func(k string, v int) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[int](v))
			})
		})
	case map[string]int32:
		maps.Insert(typedArg, func(yield func(k string, v int32) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[int32](v))
			})
		})
	case map[string]int64:
		maps.Insert(typedArg, func(yield func(k string, v int64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[int64](v))
			})
		})
	case map[string]float64:
		maps.Insert(typedArg, func(yield func(k string, v float64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[float64](v))
			})
		})
	case map[string]bool:
		maps.Insert(typedArg, func(yield func(k string, v bool) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[bool](v))
			})
		})
	case map[string]any:
		maps.Insert(typedArg, func(yield func(k string, v any) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[string](k), coerce[any](v))
			})
		})
	case map[int]string:
		maps.Insert(typedArg, func(yield func(k int, v string) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[string](v))
			})
		})
	case map[int]int:
		maps.Insert(typedArg, func(yield func(k int, v int) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[int](v))
			})
		})
	case map[int]int32:
		maps.Insert(typedArg, func(yield func(k int, v int32) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[int32](v))
			})
		})
	case map[int]int64:
		maps.Insert(typedArg, func(yield func(k int, v int64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[int64](v))
			})
		})
	case map[int]float64:
		maps.Insert(typedArg, func(yield func(k int, v float64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[float64](v))
			})
		})
	case map[int]bool:
		maps.Insert(typedArg, func(yield func(k int, v bool) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[bool](v))
			})
		})
	case map[int]any:
		maps.Insert(typedArg, func(yield func(k int, v any) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int](k), coerce[any](v))
			})
		})
	case map[int32]string:
		maps.Insert(typedArg, func(yield func(k int32, v string) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[string](v))
			})
		})
	case map[int32]int:
		maps.Insert(typedArg, func(yield func(k int32, v int) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[int](v))
			})
		})
	case map[int32]int32:
		maps.Insert(typedArg, func(yield func(k int32, v int32) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[int32](v))
			})
		})
	case map[int32]int64:
		maps.Insert(typedArg, func(yield func(k int32, v int64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[int64](v))
			})
		})
	case map[int32]float64:
		maps.Insert(typedArg, func(yield func(k int32, v float64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[float64](v))
			})
		})
	case map[int32]bool:
		maps.Insert(typedArg, func(yield func(k int32, v bool) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[bool](v))
			})
		})
	case map[int32]any:
		maps.Insert(typedArg, func(yield func(k int32, v any) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int32](k), coerce[any](v))
			})
		})
	case map[int64]string:
		maps.Insert(typedArg, func(yield func(k int64, v string) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[string](v))
			})
		})
	case map[int64]int:
		maps.Insert(typedArg, func(yield func(k int64, v int) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[int](v))
			})
		})
	case map[int64]int32:
		maps.Insert(typedArg, func(yield func(k int64, v int32) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[int32](v))
			})
		})
	case map[int64]int64:
		maps.Insert(typedArg, func(yield func(k int64, v int64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[int64](v))
			})
		})
	case map[int64]float64:
		maps.Insert(typedArg, func(yield func(k int64, v float64) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[float64](v))
			})
		})
	case map[int64]bool:
		maps.Insert(typedArg, func(yield func(k int64, v bool) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[bool](v))
			})
		})
	case map[int64]any:
		maps.Insert(typedArg, func(yield func(k int64, v any) bool) {
			seq(func(k any, v any) bool {
				return yield(coerce[int64](k), coerce[any](v))
			})
		})
	default:
		reflectMapsInsert(m, seq)
		return
	}
}
func wrappedMapsKeys(m any) any {
	switch typedArg := m.(type) {
	case map[string]string:
		return maps.Keys(typedArg)
	case map[string]int:
		return maps.Keys(typedArg)
	case map[string]int32:
		return maps.Keys(typedArg)
	case map[string]int64:
		return maps.Keys(typedArg)
	case map[string]float64:
		return maps.Keys(typedArg)
	case map[string]bool:
		return maps.Keys(typedArg)
	case map[string]any:
		return maps.Keys(typedArg)
	case map[int]string:
		return maps.Keys(typedArg)
	case map[int]int:
		return maps.Keys(typedArg)
	case map[int]int32:
		return maps.Keys(typedArg)
	case map[int]int64:
		return maps.Keys(typedArg)
	case map[int]float64:
		return maps.Keys(typedArg)
	case map[int]bool:
		return maps.Keys(typedArg)
	case map[int]any:
		return maps.Keys(typedArg)
	case map[int32]string:
		return maps.Keys(typedArg)
	case map[int32]int:
		return maps.Keys(typedArg)
	case map[int32]int32:
		return maps.Keys(typedArg)
	case map[int32]int64:
		return maps.Keys(typedArg)
	case map[int32]float64:
		return maps.Keys(typedArg)
	case map[int32]bool:
		return maps.Keys(typedArg)
	case map[int32]any:
		return maps.Keys(typedArg)
	case map[int64]string:
		return maps.Keys(typedArg)
	case map[int64]int:
		return maps.Keys(typedArg)
	case map[int64]int32:
		return maps.Keys(typedArg)
	case map[int64]int64:
		return maps.Keys(typedArg)
	case map[int64]float64:
		return maps.Keys(typedArg)
	case map[int64]bool:
		return maps.Keys(typedArg)
	case map[int64]any:
		return maps.Keys(typedArg)
	default:
		return reflectMapsKeys(m)
	}
}
func wrappedMapsValues(m any) any {
	switch typedArg := m.(type) {
	case map[string]string:
		return maps.Values(typedArg)
	case map[string]int:
		return maps.Values(typedArg)
	case map[string]int32:
		return maps.Values(typedArg)
	case map[string]int64:
		return maps.Values(typedArg)
	case map[string]float64:
		return maps.Values(typedArg)
	case map[string]bool:
		return maps.Values(typedArg)
	case map[string]any:
		return maps.Values(typedArg)
	case map[int]string:
		return maps.Values(typedArg)
	case map[int]int:
		return maps.Values(typedArg)
	case map[int]int32:
		return maps.Values(typedArg)
	case map[int]int64:
		return maps.Values(typedArg)
	case map[int]float64:
		return maps.Values(typedArg)
	case map[int]bool:
		return maps.Values(typedArg)
	case map[int]any:
		return maps.Values(typedArg)
	case map[int32]string:
		return maps.Values(typedArg)
	case map[int32]int:
		return maps.Values(typedArg)
	case map[int32]int32:
		return maps.Values(typedArg)
	case map[int32]int64:
		return maps.Values(typedArg)
	case map[int32]float64:
		return maps.Values(typedArg)
	case map[int32]bool:
		return maps.Values(typedArg)
	case map[int32]any:
		return maps.Values(typedArg)
	case map[int64]string:
		return maps.Values(typedArg)
	case map[int64]int:
		return maps.Values(typedArg)
	case map[int64]int32:
		return maps.Values(typedArg)
	case map[int64]int64:
		return maps.Values(typedArg)
	case map[int64]float64:
		return maps.Values(typedArg)
	case map[int64]bool:
		return maps.Values(typedArg)
	case map[int64]any:
		return maps.Values(typedArg)
	default:
		return reflectMapsValues(m)
	}
}
func init() {
	Symbols["maps"] = map[string]reflect.Value{"All": reflect.ValueOf(wrappedMapsAll), "Clone": reflect.ValueOf(wrappedMapsClone), "Copy": reflect.ValueOf(wrappedMapsCopy), "DeleteFunc": reflect.ValueOf(wrappedMapsDeleteFunc), "Equal": reflect.ValueOf(wrappedMapsEqual), "EqualFunc": reflect.ValueOf(wrappedMapsEqualFunc), "Insert": reflect.ValueOf(wrappedMapsInsert), "Keys": reflect.ValueOf(wrappedMapsKeys), "Values": reflect.ValueOf(wrappedMapsValues)}
}
