// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	heap "container/heap"
	"reflect"
)

func init() {
	Symbols["container/heap"] = map[string]reflect.Value{"Fix": reflect.ValueOf(heap.Fix), "Init": reflect.ValueOf(heap.Init), "Interface": reflect.ValueOf((*heap.Interface)(nil)), "Pop": reflect.ValueOf(heap.Pop), "Push": reflect.ValueOf(heap.Push), "Remove": reflect.ValueOf(heap.Remove)}
}
