// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	"log"
	"reflect"
)

func init() {
	Symbols["log"] = map[string]reflect.Value{"Default": reflect.ValueOf(log.Default), "Fatal": reflect.ValueOf(log.Fatal), "Fatalf": reflect.ValueOf(log.Fatalf), "Fatalln": reflect.ValueOf(log.Fatalln), "Flags": reflect.ValueOf(log.Flags), "LUTC": reflect.ValueOf(log.LUTC), "Ldate": reflect.ValueOf(log.Ldate), "Llongfile": reflect.ValueOf(log.Llongfile), "Lmicroseconds": reflect.ValueOf(log.Lmicroseconds), "Lmsgprefix": reflect.ValueOf(log.Lmsgprefix), "Logger": reflect.ValueOf((*log.Logger)(nil)), "Lshortfile": reflect.ValueOf(log.Lshortfile), "LstdFlags": reflect.ValueOf(log.LstdFlags), "Ltime": reflect.ValueOf(log.Ltime), "New": reflect.ValueOf(log.New), "Output": reflect.ValueOf(log.Output), "Panic": reflect.ValueOf(log.Panic), "Panicf": reflect.ValueOf(log.Panicf), "Panicln": reflect.ValueOf(log.Panicln), "Prefix": reflect.ValueOf(log.Prefix), "Print": reflect.ValueOf(log.Print), "Printf": reflect.ValueOf(log.Printf), "Println": reflect.ValueOf(log.Println), "SetFlags": reflect.ValueOf(log.SetFlags), "SetOutput": reflect.ValueOf(log.SetOutput), "SetPrefix": reflect.ValueOf(log.SetPrefix), "Writer": reflect.ValueOf(log.Writer)}
}
