// Code generated by 'pipit extract'. DO NOT EDIT.

package core

import (
	big "math/big"
	"reflect"
)

func init() {
	Symbols["math/big"] = map[string]reflect.Value{"Above": reflect.ValueOf(big.Above), "Accuracy": reflect.ValueOf((*big.Accuracy)(nil)), "AwayFromZero": reflect.ValueOf(big.AwayFromZero), "Below": reflect.ValueOf(big.Below), "Ceil": reflect.ValueOf(big.Ceil), "ErrNaN": reflect.ValueOf((*big.ErrNaN)(nil)), "Exact": reflect.ValueOf(big.Exact), "Float": reflect.ValueOf((*big.Float)(nil)), "Floor": reflect.ValueOf(big.Floor), "Int": reflect.ValueOf((*big.Int)(nil)), "Jacobi": reflect.ValueOf(big.Jacobi), "MaxBase": reflect.ValueOf(big.MaxBase), "MaxExp": reflect.ValueOf(big.MaxExp), "MaxPrec": reflect.ValueOf(big.MaxPrec), "MinExp": reflect.ValueOf(big.MinExp), "NewFloat": reflect.ValueOf(big.NewFloat), "NewInt": reflect.ValueOf(big.NewInt), "NewRat": reflect.ValueOf(big.NewRat), "ParseFloat": reflect.ValueOf(big.ParseFloat), "Rat": reflect.ValueOf((*big.Rat)(nil)), "Round": reflect.ValueOf(big.Round), "RoundingMode": reflect.ValueOf((*big.RoundingMode)(nil)), "ToNearestAway": reflect.ValueOf(big.ToNearestAway), "ToNearestEven": reflect.ValueOf(big.ToNearestEven), "ToNegativeInf": reflect.ValueOf(big.ToNegativeInf), "ToPositiveInf": reflect.ValueOf(big.ToPositiveInf), "ToZero": reflect.ValueOf(big.ToZero), "Trunc": reflect.ValueOf(big.Trunc), "Word": reflect.ValueOf((*big.Word)(nil))}
}
