// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	crc64 "hash/crc64"
	"reflect"
)

func init() {
	Symbols["hash/crc64"] = map[string]reflect.Value{"Checksum": reflect.ValueOf(crc64.Checksum), "MakeTable": reflect.ValueOf(crc64.MakeTable), "New": reflect.ValueOf(crc64.New), "Size": reflect.ValueOf(crc64.Size), "Table": reflect.ValueOf((*crc64.Table)(nil)), "Update": reflect.ValueOf(crc64.Update)}
}
