// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	json "encoding/json/v2"
	"reflect"
)

func init() {
	Symbols["encoding/json/v2"] = map[string]reflect.Value{"DefaultOptionsV2": reflect.ValueOf(json.DefaultOptionsV2), "Deterministic": reflect.ValueOf(json.Deterministic), "ErrUnknownName": reflect.ValueOf(&json.ErrUnknownName).Elem(), "FormatNilMapAsNull": reflect.ValueOf(json.FormatNilMapAsNull), "FormatNilSliceAsNull": reflect.ValueOf(json.FormatNilSliceAsNull), "JoinMarshalers": reflect.ValueOf(json.JoinMarshalers), "JoinOptions": reflect.ValueOf(json.JoinOptions), "JoinUnmarshalers": reflect.ValueOf(json.JoinUnmarshalers), "Marshal": reflect.ValueOf(json.Marshal), "MarshalEncode": reflect.ValueOf(json.MarshalEncode), "MarshalWrite": reflect.ValueOf(json.MarshalWrite), "Marshaler": reflect.ValueOf((*json.Marshaler)(nil)), "MarshalerTo": reflect.ValueOf((*json.MarshalerTo)(nil)), "Marshalers": reflect.ValueOf((*json.Marshalers)(nil)), "MatchCaseInsensitiveNames": reflect.ValueOf(json.MatchCaseInsensitiveNames), "OmitZeroStructFields": reflect.ValueOf(json.OmitZeroStructFields), "Options": reflect.ValueOf((*json.Options)(nil)), "RejectUnknownMembers": reflect.ValueOf(json.RejectUnknownMembers), "SemanticError": reflect.ValueOf((*json.SemanticError)(nil)), "StringifyNumbers": reflect.ValueOf(json.StringifyNumbers), "Unmarshal": reflect.ValueOf(json.Unmarshal), "UnmarshalDecode": reflect.ValueOf(json.UnmarshalDecode), "UnmarshalRead": reflect.ValueOf(json.UnmarshalRead), "Unmarshaler": reflect.ValueOf((*json.Unmarshaler)(nil)), "UnmarshalerFrom": reflect.ValueOf((*json.UnmarshalerFrom)(nil)), "Unmarshalers": reflect.ValueOf((*json.Unmarshalers)(nil)), "WithMarshalers": reflect.ValueOf(json.WithMarshalers), "WithUnmarshalers": reflect.ValueOf(json.WithUnmarshalers)}
}
