// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	flate "compress/flate"
	"reflect"
)

func init() {
	Symbols["compress/flate"] = map[string]reflect.Value{"BestCompression": reflect.ValueOf(flate.BestCompression), "BestSpeed": reflect.ValueOf(flate.BestSpeed), "CorruptInputError": reflect.ValueOf((*flate.CorruptInputError)(nil)), "DefaultCompression": reflect.ValueOf(flate.DefaultCompression), "HuffmanOnly": reflect.ValueOf(flate.HuffmanOnly), "InternalError": reflect.ValueOf((*flate.InternalError)(nil)), "NewReader": reflect.ValueOf(flate.NewReader), "NewReaderDict": reflect.ValueOf(flate.NewReaderDict), "NewWriter": reflect.ValueOf(flate.NewWriter), "NewWriterDict": reflect.ValueOf(flate.NewWriterDict), "NoCompression": reflect.ValueOf(flate.NoCompression), "ReadError": reflect.ValueOf((*flate.ReadError)(nil)), "Reader": reflect.ValueOf((*flate.Reader)(nil)), "Resetter": reflect.ValueOf((*flate.Resetter)(nil)), "WriteError": reflect.ValueOf((*flate.WriteError)(nil)), "Writer": reflect.ValueOf((*flate.Writer)(nil))}
}
