// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	"encoding"
	"reflect"
)

func init() {
	Symbols["encoding"] = map[string]reflect.Value{"BinaryAppender": reflect.ValueOf((*encoding.BinaryAppender)(nil)), "BinaryMarshaler": reflect.ValueOf((*encoding.BinaryMarshaler)(nil)), "BinaryUnmarshaler": reflect.ValueOf((*encoding.BinaryUnmarshaler)(nil)), "TextAppender": reflect.ValueOf((*encoding.TextAppender)(nil)), "TextMarshaler": reflect.ValueOf((*encoding.TextMarshaler)(nil)), "TextUnmarshaler": reflect.ValueOf((*encoding.TextUnmarshaler)(nil))}
}
