// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	binary "encoding/binary"
	"reflect"
)

func init() {
	Symbols["encoding/binary"] = map[string]reflect.Value{"Append": reflect.ValueOf(binary.Append), "AppendByteOrder": reflect.ValueOf((*binary.AppendByteOrder)(nil)), "AppendUvarint": reflect.ValueOf(binary.AppendUvarint), "AppendVarint": reflect.ValueOf(binary.AppendVarint), "BigEndian": reflect.ValueOf(&binary.BigEndian).Elem(), "ByteOrder": reflect.ValueOf((*binary.ByteOrder)(nil)), "Decode": reflect.ValueOf(binary.Decode), "Encode": reflect.ValueOf(binary.Encode), "LittleEndian": reflect.ValueOf(&binary.LittleEndian).Elem(), "MaxVarintLen16": reflect.ValueOf(binary.MaxVarintLen16), "MaxVarintLen32": reflect.ValueOf(binary.MaxVarintLen32), "MaxVarintLen64": reflect.ValueOf(binary.MaxVarintLen64), "NativeEndian": reflect.ValueOf(&binary.NativeEndian).Elem(), "PutUvarint": reflect.ValueOf(binary.PutUvarint), "PutVarint": reflect.ValueOf(binary.PutVarint), "Read": reflect.ValueOf(binary.Read), "ReadUvarint": reflect.ValueOf(binary.ReadUvarint), "ReadVarint": reflect.ValueOf(binary.ReadVarint), "Size": reflect.ValueOf(binary.Size), "Uvarint": reflect.ValueOf(binary.Uvarint), "Varint": reflect.ValueOf(binary.Varint), "Write": reflect.ValueOf(binary.Write)}
}
