// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	base32 "encoding/base32"
	"reflect"
)

func init() {
	Symbols["encoding/base32"] = map[string]reflect.Value{"CorruptInputError": reflect.ValueOf((*base32.CorruptInputError)(nil)), "Encoding": reflect.ValueOf((*base32.Encoding)(nil)), "HexEncoding": reflect.ValueOf(&base32.HexEncoding).Elem(), "NewDecoder": reflect.ValueOf(base32.NewDecoder), "NewEncoder": reflect.ValueOf(base32.NewEncoder), "NewEncoding": reflect.ValueOf(base32.NewEncoding), "NoPadding": reflect.ValueOf(base32.NoPadding), "StdEncoding": reflect.ValueOf(&base32.StdEncoding).Elem(), "StdPadding": reflect.ValueOf(base32.StdPadding)}
}
