// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	tar "archive/tar"
	"reflect"
)

func init() {
	Symbols["archive/tar"] = map[string]reflect.Value{"ErrFieldTooLong": reflect.ValueOf(&tar.ErrFieldTooLong).Elem(), "ErrHeader": reflect.ValueOf(&tar.ErrHeader).Elem(), "ErrInsecurePath": reflect.ValueOf(&tar.ErrInsecurePath).Elem(), "ErrWriteAfterClose": reflect.ValueOf(&tar.ErrWriteAfterClose).Elem(), "ErrWriteTooLong": reflect.ValueOf(&tar.ErrWriteTooLong).Elem(), "FileInfoHeader": reflect.ValueOf(tar.FileInfoHeader), "FileInfoNames": reflect.ValueOf((*tar.FileInfoNames)(nil)), "Format": reflect.ValueOf((*tar.Format)(nil)), "FormatGNU": reflect.ValueOf(tar.FormatGNU), "FormatPAX": reflect.ValueOf(tar.FormatPAX), "FormatUSTAR": reflect.ValueOf(tar.FormatUSTAR), "FormatUnknown": reflect.ValueOf(tar.FormatUnknown), "Header": reflect.ValueOf((*tar.Header)(nil)), "NewReader": reflect.ValueOf(tar.NewReader), "NewWriter": reflect.ValueOf(tar.NewWriter), "Reader": reflect.ValueOf((*tar.Reader)(nil)), "TypeBlock": reflect.ValueOf(tar.TypeBlock), "TypeChar": reflect.ValueOf(tar.TypeChar), "TypeCont": reflect.ValueOf(tar.TypeCont), "TypeDir": reflect.ValueOf(tar.TypeDir), "TypeFifo": reflect.ValueOf(tar.TypeFifo), "TypeGNULongLink": reflect.ValueOf(tar.TypeGNULongLink), "TypeGNULongName": reflect.ValueOf(tar.TypeGNULongName), "TypeGNUSparse": reflect.ValueOf(tar.TypeGNUSparse), "TypeLink": reflect.ValueOf(tar.TypeLink), "TypeReg": reflect.ValueOf(tar.TypeReg), "TypeRegA": reflect.ValueOf(tar.TypeRegA), "TypeSymlink": reflect.ValueOf(tar.TypeSymlink), "TypeXGlobalHeader": reflect.ValueOf(tar.TypeXGlobalHeader), "TypeXHeader": reflect.ValueOf(tar.TypeXHeader), "Writer": reflect.ValueOf((*tar.Writer)(nil))}
}
