// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	suffixarray "index/suffixarray"
	"reflect"
)

func init() {
	Symbols["index/suffixarray"] = map[string]reflect.Value{"Index": reflect.ValueOf((*suffixarray.Index)(nil)), "New": reflect.ValueOf(suffixarray.New)}
}
