// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	bzip2 "compress/bzip2"
	"reflect"
)

func init() {
	Symbols["compress/bzip2"] = map[string]reflect.Value{"NewReader": reflect.ValueOf(bzip2.NewReader), "StructuralError": reflect.ValueOf((*bzip2.StructuralError)(nil))}
}
