// Code generated by 'pipit extract'. DO NOT EDIT.

package codec

import (
	gob "encoding/gob"
	"reflect"
)

func init() {
	Symbols["encoding/gob"] = map[string]reflect.Value{"CommonType": reflect.ValueOf((*gob.CommonType)(nil)), "Decoder": reflect.ValueOf((*gob.Decoder)(nil)), "Encoder": reflect.ValueOf((*gob.Encoder)(nil)), "GobDecoder": reflect.ValueOf((*gob.GobDecoder)(nil)), "GobEncoder": reflect.ValueOf((*gob.GobEncoder)(nil)), "NewDecoder": reflect.ValueOf(gob.NewDecoder), "NewEncoder": reflect.ValueOf(gob.NewEncoder), "Register": reflect.ValueOf(gob.Register), "RegisterName": reflect.ValueOf(gob.RegisterName)}
}
