// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	"reflect"
	fstest "testing/fstest"
)

func init() {
	Symbols["testing/fstest"] = map[string]reflect.Value{"MapFS": reflect.ValueOf((*fstest.MapFS)(nil)), "MapFile": reflect.ValueOf((*fstest.MapFile)(nil)), "TestFS": reflect.ValueOf(fstest.TestFS)}
}
