// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	constraint "go/build/constraint"
	"reflect"
)

func init() {
	Symbols["go/build/constraint"] = map[string]reflect.Value{"AndExpr": reflect.ValueOf((*constraint.AndExpr)(nil)), "Expr": reflect.ValueOf((*constraint.Expr)(nil)), "GoVersion": reflect.ValueOf(constraint.GoVersion), "IsGoBuild": reflect.ValueOf(constraint.IsGoBuild), "IsPlusBuild": reflect.ValueOf(constraint.IsPlusBuild), "NotExpr": reflect.ValueOf((*constraint.NotExpr)(nil)), "OrExpr": reflect.ValueOf((*constraint.OrExpr)(nil)), "Parse": reflect.ValueOf(constraint.Parse), "PlusBuildLines": reflect.ValueOf(constraint.PlusBuildLines), "SyntaxError": reflect.ValueOf((*constraint.SyntaxError)(nil)), "TagExpr": reflect.ValueOf((*constraint.TagExpr)(nil))}
}
