// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	doc "go/doc"
	"reflect"
)

func init() {
	Symbols["go/doc"] = map[string]reflect.Value{"AllDecls": reflect.ValueOf(doc.AllDecls), "AllMethods": reflect.ValueOf(doc.AllMethods), "Example": reflect.ValueOf((*doc.Example)(nil)), "Examples": reflect.ValueOf(doc.Examples), "Filter": reflect.ValueOf((*doc.Filter)(nil)), "Func": reflect.ValueOf((*doc.Func)(nil)), "IllegalPrefixes": reflect.ValueOf(&doc.IllegalPrefixes).Elem(), "IsPredeclared": reflect.ValueOf(doc.IsPredeclared), "Mode": reflect.ValueOf((*doc.Mode)(nil)), "New": reflect.ValueOf(doc.New), "NewFromFiles": reflect.ValueOf(doc.NewFromFiles), "Note": reflect.ValueOf((*doc.Note)(nil)), "Package": reflect.ValueOf((*doc.Package)(nil)), "PreserveAST": reflect.ValueOf(doc.PreserveAST), "Synopsis": reflect.ValueOf(doc.Synopsis), "ToHTML": reflect.ValueOf(doc.ToHTML), "ToText": reflect.ValueOf(doc.ToText), "Type": reflect.ValueOf((*doc.Type)(nil)), "Value": reflect.ValueOf((*doc.Value)(nil))}
}
