// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	importer "go/importer"
	"reflect"
)

func init() {
	Symbols["go/importer"] = map[string]reflect.Value{"Default": reflect.ValueOf(importer.Default), "For": reflect.ValueOf(importer.For), "ForCompiler": reflect.ValueOf(importer.ForCompiler), "Lookup": reflect.ValueOf((*importer.Lookup)(nil))}
}
