// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	scanner "go/scanner"
	"reflect"
)

func init() {
	Symbols["go/scanner"] = map[string]reflect.Value{"Error": reflect.ValueOf((*scanner.Error)(nil)), "ErrorHandler": reflect.ValueOf((*scanner.ErrorHandler)(nil)), "ErrorList": reflect.ValueOf((*scanner.ErrorList)(nil)), "Mode": reflect.ValueOf((*scanner.Mode)(nil)), "PrintError": reflect.ValueOf(scanner.PrintError), "ScanComments": reflect.ValueOf(scanner.ScanComments), "Scanner": reflect.ValueOf((*scanner.Scanner)(nil))}
}
