// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	printer "go/printer"
	"reflect"
)

func init() {
	Symbols["go/printer"] = map[string]reflect.Value{"CommentedNode": reflect.ValueOf((*printer.CommentedNode)(nil)), "Config": reflect.ValueOf((*printer.Config)(nil)), "Fprint": reflect.ValueOf(printer.Fprint), "Mode": reflect.ValueOf((*printer.Mode)(nil)), "RawFormat": reflect.ValueOf(printer.RawFormat), "SourcePos": reflect.ValueOf(printer.SourcePos), "TabIndent": reflect.ValueOf(printer.TabIndent), "UseSpaces": reflect.ValueOf(printer.UseSpaces)}
}
