// Code generated by 'pipit extract'. DO NOT EDIT.

package gotool

import (
	"reflect"
	cryptotest "testing/cryptotest"
)

func init() {
	Symbols["testing/cryptotest"] = map[string]reflect.Value{"SetGlobalRandom": reflect.ValueOf(cryptotest.SetGlobalRandom)}
}
